"TEST-ONLY SURVEY FLAGS (1301) — never production"

;"No extra <GLOBAL>s: production Glulx is already at the 236-global ceiling.
  Rewind is a test-only TRYTAKEBIT on PLAYER."

<SYNTAX SURVEYKILL = V-SURVEY-KILL>
<SYNTAX SURVEYREWIND = V-SURVEY-REWIND>
<SYNTAX SVYMAZE = V-SVY-MAZE>
<SYNTAX SVYTEMPLE = V-SVY-TEMPLE>
<SYNTAX SVYDAMLOBBY = V-SVY-DAM-LOBBY>
<SYNTAX SVYSTREAM = V-SVY-STREAM>
<SYNTAX SVYHADES = V-SVY-HADES>
<SYNTAX SVYBARROW = V-SVY-BARROW>
<SYNTAX SVYROUND = V-SVY-ROUND>
<SYNTAX SVYPASSAGE = V-SVY-PASSAGE>
<SYNTAX SVYRIVER = V-SVY-RIVER>
<SYNTAX SVYMAINT = V-SVY-MAINT>
<SYNTAX SVYCANYON = V-SVY-CANYON>

<ROUTINE SVY-LIGHT ()
	<MOVE ,LAMP ,WINNER>
	<FSET ,LAMP ,ONBIT>
	<RTRUE>>

<ROUTINE V-SURVEY-KILL ()
	<SETG TROLL-FLAG T>
	<SETG CYCLOPS-FLAG T>
	<SETG ALWAYS-LIT T>
	<FCLEAR ,TROLL ,FIGHTBIT>
	<TELL "SURVEY FLAG --no-killing: lethal combat and enemy obstruction are set aside." CR>
	<RTRUE>>

<ROUTINE V-SURVEY-REWIND ()
	<FSET ,WINNER ,TRYTAKEBIT>
	<FSET ,PLAYER ,TRYTAKEBIT>
	<TELL "SURVEY FLAG --no-reset-on-death: a fatal command rewinds in place." CR>
	<RTRUE>>

<ROUTINE V-SVY-CANYON ()
	<GOTO ,CANYON-VIEW>
	<TELL "TEST PRECONDITION: canyon view." CR>
	<RTRUE>>

<ROUTINE V-SVY-MAZE ()
	<SVY-LIGHT>
	<GOTO ,MAZE-1>
	<TELL "TEST PRECONDITION: maze of twisty little passages." CR>
	<RTRUE>>

<ROUTINE V-SVY-TEMPLE ()
	<SVY-LIGHT>
	<GOTO ,NORTH-TEMPLE>
	<TELL "TEST PRECONDITION: north temple." CR>
	<RTRUE>>

<ROUTINE V-SVY-DAM-LOBBY ()
	<SVY-LIGHT>
	<GOTO ,DAM-LOBBY>
	<TELL "TEST PRECONDITION: dam waiting room." CR>
	<RTRUE>>

<ROUTINE V-SVY-STREAM ()
	<SVY-LIGHT>
	<MOVE ,WINNER ,IN-STREAM>
	<SETG HERE ,IN-STREAM>
	<TELL "TEST PRECONDITION: in the stream." CR>
	<RTRUE>>

<ROUTINE V-SVY-HADES ()
	<SVY-LIGHT>
	<GOTO ,LAND-OF-LIVING-DEAD>
	<TELL "TEST PRECONDITION: Land of the Living Dead." CR>
	<RTRUE>>

<ROUTINE V-SVY-BARROW ()
	<GOTO ,STONE-BARROW>
	<TELL "TEST PRECONDITION: stone barrow." CR>
	<RTRUE>>

<ROUTINE V-SVY-ROUND ()
	<SVY-LIGHT>
	<GOTO ,ROUND-ROOM>
	<TELL "TEST PRECONDITION: round room." CR>
	<RTRUE>>

<ROUTINE V-SVY-PASSAGE ()
	<SVY-LIGHT>
	<GOTO ,STRANGE-PASSAGE>
	<TELL "TEST PRECONDITION: strange passage." CR>
	<RTRUE>>

<ROUTINE V-SVY-RIVER ()
	<SVY-LIGHT>
	<MOVE ,WINNER ,RIVER-2>
	<SETG HERE ,RIVER-2>
	<TELL "TEST PRECONDITION: Frigid River rocks." CR>
	<RTRUE>>

<ROUTINE V-SVY-MAINT ()
	<SVY-LIGHT>
	<GOTO ,MAINTENANCE-ROOM>
	<TELL "TEST PRECONDITION: dam maintenance room." CR>
	<RTRUE>>
