"Test-only positioning, mutation, and reporting verbs for Release 1218 qualification."

<SYNTAX RDTROLL = V-ROOM-DENSITY-TEST-TROLL>
<SYNTAX RDGALLERY = V-ROOM-DENSITY-TEST-GALLERY>
<SYNTAX RDSTUDIO = V-ROOM-DENSITY-TEST-STUDIO>
<SYNTAX RDCHASM = V-ROOM-DENSITY-TEST-CHASM>
<SYNTAX RDPASSAGE = V-ROOM-DENSITY-TEST-PASSAGE>
<SYNTAX RDTREASURE = V-ROOM-DENSITY-TEST-TREASURE>
<SYNTAX RDPATH = V-ROOM-DENSITY-TEST-PATH>
<SYNTAX RDSTREAM = V-ROOM-DENSITY-TEST-STREAM>
<SYNTAX RDREPORT = V-ROOM-DENSITY-TEST-REPORT>
<SYNTAX RDMUTATE = V-ROOM-DENSITY-TEST-MUTATE>

<ROUTINE ROOM-DENSITY-TEST-CLEAR ()
    <SETG ROOM-DENSITY-TROLL-SEEN <>>
    <SETG ROOM-DENSITY-GALLERY-SEEN <>>
    <SETG ROOM-DENSITY-STUDIO-SEEN <>>
    <SETG ROOM-DENSITY-CHASM-SEEN <>>
    <SETG ROOM-DENSITY-PASSAGE-SEEN <>>
    <SETG ROOM-DENSITY-TREASURE-SEEN <>>
    <SETG ROOM-DENSITY-PATH-SEEN <>>
    <RTRUE>>

<ROUTINE ROOM-DENSITY-TEST-QUIET-WORLD ()
    <QUEUE I-THIEF 0>
    <SETG THIEF-HERE <>>
    <REMOVE-CAREFULLY ,THIEF>
    <REMOVE-CAREFULLY ,TROLL>
    <SETG TROLL-FLAG T>
    <MOVE ,LAMP ,WINNER>
    <FSET ,LAMP ,ONBIT>
    <RTRUE>>

<ROUTINE ROOM-DENSITY-TEST-GO (ROOM MARKER)
    <ROOM-DENSITY-TEST-QUIET-WORLD>
    <GOTO .ROOM>
    <SETG CLOCK-WAIT T>
    <TELL .MARKER CR>>

<ROUTINE V-ROOM-DENSITY-TEST-TROLL ()
    <ROOM-DENSITY-TEST-CLEAR>
    <ROOM-DENSITY-TEST-GO ,TROLL-ROOM "ROOM-DENSITY-SETUP:TROLL">>

<ROUTINE V-ROOM-DENSITY-TEST-GALLERY ()
    <ROOM-DENSITY-TEST-GO ,GALLERY "ROOM-DENSITY-SETUP:GALLERY">>

<ROUTINE V-ROOM-DENSITY-TEST-STUDIO ()
    <ROOM-DENSITY-TEST-GO ,STUDIO "ROOM-DENSITY-SETUP:STUDIO">>

<ROUTINE V-ROOM-DENSITY-TEST-CHASM ()
    <ROOM-DENSITY-TEST-GO ,EAST-OF-CHASM "ROOM-DENSITY-SETUP:CHASM">>

<ROUTINE V-ROOM-DENSITY-TEST-PASSAGE ()
    <ROOM-DENSITY-TEST-GO ,STRANGE-PASSAGE "ROOM-DENSITY-SETUP:PASSAGE">>

<ROUTINE V-ROOM-DENSITY-TEST-TREASURE ()
    <ROOM-DENSITY-TEST-GO ,TREASURE-ROOM "ROOM-DENSITY-SETUP:TREASURE">>

<ROUTINE V-ROOM-DENSITY-TEST-PATH ()
    <ROOM-DENSITY-TEST-GO ,PATH "ROOM-DENSITY-SETUP:PATH">>

<ROUTINE V-ROOM-DENSITY-TEST-STREAM ()
    <ROOM-DENSITY-TEST-GO ,STREAM-VIEW "ROOM-DENSITY-SETUP:STREAM">>

<ROUTINE V-ROOM-DENSITY-TEST-MUTATE ()
    <ROOM-DENSITY-TEST-CLEAR>
    <SETG CLOCK-WAIT T>
    <TELL "ROOM-DENSITY-STATE:MUTATED" CR>>

<ROUTINE V-ROOM-DENSITY-TEST-REPORT ()
    <TELL "ROOM-DENSITY-STATE:TROLL=">
    <COND (,ROOM-DENSITY-TROLL-SEEN <TELL "SEEN">) (T <TELL "CLEAR">)>
    <TELL ";GALLERY=">
    <COND (,ROOM-DENSITY-GALLERY-SEEN <TELL "SEEN">) (T <TELL "CLEAR">)>
    <TELL ";STUDIO=">
    <COND (,ROOM-DENSITY-STUDIO-SEEN <TELL "SEEN">) (T <TELL "CLEAR">)>
    <TELL ";CHASM=">
    <COND (,ROOM-DENSITY-CHASM-SEEN <TELL "SEEN">) (T <TELL "CLEAR">)>
    <TELL ";PASSAGE=">
    <COND (,ROOM-DENSITY-PASSAGE-SEEN <TELL "SEEN">) (T <TELL "CLEAR">)>
    <TELL ";TREASURE=">
    <COND (,ROOM-DENSITY-TREASURE-SEEN <TELL "SEEN">) (T <TELL "CLEAR">)>
    <TELL ";PATH=">
    <COND (,ROOM-DENSITY-PATH-SEEN <TELL "SEEN">) (T <TELL "CLEAR">)>
    <CRLF>>
