"Test-only setup verbs for Release 122 qualification."

<SYNTAX ALTSAFE = V-ALT-SAFE>
<SYNTAX ALTBREAK = V-ALT-BREAK>
<SYNTAX ALTCANON = V-ALT-CANON>
<SYNTAX ALTTROLL = V-ALT-TROLL-SETUP>
<SYNTAX ALTSTATUS = V-ALT-STATUS>

<ROUTINE ALT-TEST-NEST-BASE ()
	<MOVE ,TORCH ,WINNER>
	<FSET ,TORCH ,ONBIT>
	<FSET ,TORCH ,FLAMEBIT>
	<MOVE ,NEST ,UP-A-TREE>
	<MOVE ,EGG ,NEST>
	<MOVE ,CANARY ,EGG>
	<GOTO ,PATH>
	<RTRUE>>

<ROUTINE V-ALT-SAFE ()
	<ALT-TEST-NEST-BASE>
	<MOVE ,SANDWICH-BAG ,WINNER>
	<TELL "[Test-only prepared-catcher scenario.]" CR>>

<ROUTINE V-ALT-BREAK ()
	<ALT-TEST-NEST-BASE>
	<MOVE ,SANDWICH-BAG ,KITCHEN-TABLE>
	<TELL "[Test-only unprepared-fall scenario.]" CR>>

<ROUTINE V-ALT-CANON ()
	<MOVE ,NEST ,PATH>
	<MOVE ,EGG ,NEST>
	<MOVE ,CANARY ,EGG>
	<MOVE ,CANDLES ,WINNER>
	<FSET ,CANDLES ,ONBIT>
	<FSET ,CANDLES ,FLAMEBIT>
	<GOTO ,PATH>
	<TELL "[Test-only canonical nest-burning scenario.]" CR>>

<ROUTINE V-ALT-TROLL-SETUP ()
	<MOVE ,ROPE ,WINNER>
	<MOVE ,LAMP ,WINNER>
	<FSET ,LAMP ,ONBIT>
	<FSET ,LAMP ,LIGHTBIT>
	<FSET ,TROLL ,FIGHTBIT>
	<SETG ALT-TROLL-DISTRACTED <>>
	<SETG ALT-TROLL-TRICK-USED <>>
	<SETG ALT-TROLL-BOUND <>>
	<SETG TROLL-FLAG <>>
	<GOTO ,TROLL-ROOM>
	<TELL "[Test-only troll recovery scenario.]" CR>>

<ROUTINE V-ALT-STATUS ()
	<COND (<AND <FSET? ,TROLL ,FIGHTBIT>
	            <NOT ,ALT-TROLL-DISTRACTED>
	            <NOT ,ALT-TROLL-BOUND>>
	       <TELL "[Test-only troll hostility restored.]" CR>)
	      (T
	       <TELL "[Test-only troll hostility NOT restored.]" CR>)>>
