"Test-only setup verbs for Release 122 qualification."

<SYNTAX ALTSAFE = V-ALT-SAFE>
<SYNTAX ALTEMPTY = V-ALT-EMPTY>
<SYNTAX ALTBREAK = V-ALT-BREAK>
<SYNTAX ALTCANON = V-ALT-CANON>
<SYNTAX ALTTROLL = V-ALT-TROLL-SETUP>
<SYNTAX ALTCHECK = V-ALT-CHECK-RECOVERY>
<SYNTAX ALTUNARM = V-ALT-UNARMED-TROLL-SETUP>

<ROUTINE ALT-TEST-NEST-BASE ()
	<MOVE ,TORCH ,WINNER>
	<FSET ,TORCH ,ONBIT>
	<FSET ,TORCH ,FLAMEBIT>
	<MOVE ,NEST ,UP-A-TREE>
	<MOVE ,EGG ,NEST>
	<MOVE ,CANARY ,EGG>
	<SETG ALT-NEST-BURNED <>>
	<SETG ALT-EGG-CAUGHT <>>
	<SETG ALT-SACK-PREPARED <>>
	<GOTO ,PATH>
	<RTRUE>>

<ROUTINE V-ALT-SAFE ()
	<ALT-TEST-NEST-BASE>
	<MOVE ,SANDWICH-BAG ,WINNER>
	<MOVE ,LUNCH ,SANDWICH-BAG>
	<TELL "[Test-only prepared-catcher scenario.]" CR>>

<ROUTINE V-ALT-EMPTY ()
	<ALT-TEST-NEST-BASE>
	<MOVE ,SANDWICH-BAG ,WINNER>
	<MOVE ,LUNCH ,KITCHEN-TABLE>
	<TELL "[Test-only prepared empty-catcher scenario.]" CR>>

<ROUTINE V-ALT-BREAK ()
	<ALT-TEST-NEST-BASE>
	<MOVE ,SANDWICH-BAG ,PATH>
	<TELL "[Test-only unprepared-fall scenario with an unprepared sack beneath the tree.]" CR>>

<ROUTINE V-ALT-CANON ()
	<MOVE ,NEST ,PATH>
	<MOVE ,EGG ,NEST>
	<MOVE ,CANARY ,EGG>
	<MOVE ,CANDLES ,WINNER>
	<FSET ,CANDLES ,ONBIT>
	<FSET ,CANDLES ,FLAMEBIT>
	<GOTO ,PATH>
	<TELL "[Test-only canonical nest-burning scenario.]" CR>>

<ROUTINE V-ALT-TROLL-SETUP ()
	<MOVE ,ROPE ,WINNER>
	<MOVE ,LAMP ,WINNER>
	<FSET ,LAMP ,ONBIT>
	<FSET ,LAMP ,LIGHTBIT>
	<MOVE ,AXE ,TROLL>
	<FSET ,TROLL ,FIGHTBIT>
	<SETG ALT-TROLL-DISTRACTED <>>
	<SETG ALT-TROLL-TRICK-USED <>>
	<SETG ALT-TROLL-BOUND <>>
	<SETG TROLL-FLAG <>>
	<GOTO ,TROLL-ROOM>
	<SETG CLOCK-WAIT T>
	<TELL "[Test-only troll recovery scenario.]" CR>>

<ROUTINE V-ALT-CHECK-RECOVERY ()
	<COND (<OR ,ALT-TROLL-DISTRACTED
	           <NOT <FSET? ,TROLL ,FIGHTBIT>>>
	       <TELL "[Test-only failure: troll hostility was not restored after the abandoned opportunity.]" CR>)
	      (T
	       <TELL "[Test-only confirmed troll hostility restored after the abandoned opportunity.]" CR>
	       <FCLEAR ,TROLL ,FIGHTBIT>
	       <GOTO ,TROLL-ROOM>
	       <SETG CLOCK-WAIT T>)>>

<ROUTINE V-ALT-UNARMED-TROLL-SETUP ()
	<MOVE ,ROPE ,WINNER>
	<MOVE ,LAMP ,WINNER>
	<FSET ,LAMP ,ONBIT>
	<FSET ,LAMP ,LIGHTBIT>
	<MOVE ,AXE ,KITCHEN-TABLE>
	<FSET ,TROLL ,FIGHTBIT>
	<SETG ALT-TROLL-DISTRACTED <>>
	<SETG ALT-TROLL-TRICK-USED <>>
	<SETG ALT-TROLL-BOUND <>>
	<SETG TROLL-FLAG <>>
	<GOTO ,TROLL-ROOM>
	<SETG CLOCK-WAIT T>
	<TELL "[Test-only unarmed troll scenario.]" CR>>
