"TEST-ONLY RELEASE 1273 LIVING BIOMES PRECONDITIONS"

<SYNTAX BIOMEGEAR = V-BIOME-GEAR-TEST>
<SYNTAX BIOMEFOREST = V-BIOME-FOREST-TEST>
<SYNTAX BIOMEBEAVER = V-BIOME-BEAVER-TEST>
<SYNTAX BIOMEFOX = V-BIOME-FOX-TEST>
<SYNTAX BIOMEBASIN = V-BIOME-BASIN-TEST>
<SYNTAX BIOMEDRIP = V-BIOME-DRIP-TEST>
<SYNTAX BIOMEANTS = V-BIOME-ANTS-TEST>
<SYNTAX BIOMEFAUNA = V-BIOME-FAUNA-TEST>
<SYNTAX BIOMECAIMAN = V-BIOME-CAIMAN-TEST>
<SYNTAX BIOMECAIMANDEATH = V-BIOME-CAIMAN-DEATH-TEST>
<SYNTAX BIOMEVINES = V-BIOME-VINES-TEST>

<ROUTINE BIOME-TEST-RESET ()
    <SETG ALWAYS-LIT T>
    <WILDERNESS-PUT ,WB-BRUSH-CLEARED 0>
    <WILDERNESS-PUT ,WB-FOX-TRAIL-SEEN 0>
    <WILDERNESS-PUT ,WR-ANT-ROUTE-SEEN 0>
    <WILDERNESS-PUT ,WR-CAIMAN-AWAY 0>
    <WILDERNESS-PUT ,WR-CAIMAN-WARNED 0>
    <WILDERNESS-PUT ,WR-VINES-CUT 0>
    <DISABLE <INT I-WARMRAIN-CAIMAN-RETURN>>
    <RTRUE>>

<ROUTINE V-BIOME-GEAR-TEST ()
    <BIOME-TEST-RESET>
    <COND (<IN? ,WILDERNESS-MACHETE ,WINNER> <REMOVE-CAREFULLY ,WILDERNESS-MACHETE>)>
    <MOVE ,WILDERNESS-MACHETE ,ASHGLASS-WEST-COURT>
    <GOTO ,ASHGLASS-WEST-COURT>
    <TELL "TEST PRECONDITION: old forester's machete lies in the Ashglass outer court." CR>
    <RTRUE>>

<ROUTINE V-BIOME-FOREST-TEST ()
    <BIOME-TEST-RESET>
    <COND (<IN? ,WILDERNESS-MACHETE ,WINNER> <REMOVE-CAREFULLY ,WILDERNESS-MACHETE>)>
    <MOVE ,WILDERNESS-MACHETE ,WINNER>
    <GOTO ,FOREST-1>
    <TELL "TEST PRECONDITION: canonical Forest-1 western brush intact; real machete held." CR>
    <RTRUE>>

<ROUTINE V-BIOME-BEAVER-TEST ()
    <BIOME-TEST-RESET>
    <MOVE ,BACKCOUNTRY-BEAVER ,BACKCOUNTRY-BEAVER-MEADOW>
    <GOTO ,BACKCOUNTRY-BEAVER-MEADOW>
    <TELL "TEST PRECONDITION: living beaver and its authored dam occupy the wetland." CR>
    <RTRUE>>

<ROUTINE V-BIOME-FOX-TEST ()
    <BIOME-TEST-RESET>
    <GOTO ,BACKCOUNTRY-FOX-RUN>
    <TELL "TEST PRECONDITION: fox shortcut not yet observed." CR>
    <RTRUE>>

<ROUTINE V-BIOME-BASIN-TEST ()
    <BIOME-TEST-RESET>
    <GOTO ,BACKCOUNTRY-BASIN-OVERLOOK>
    <TELL "TEST PRECONDITION: transition from cold backcountry to warm enclosed rain forest ready." CR>
    <RTRUE>>

<ROUTINE V-BIOME-DRIP-TEST ()
    <BIOME-TEST-RESET>
    <COND (<IN? ,CANDLES ,WINNER> <REMOVE-CAREFULLY ,CANDLES>)>
    <MOVE ,CANDLES ,WINNER>
    <FSET ,CANDLES ,ONBIT>
    <CONSUMABLE-LIGHT-PUT ,CL-CANDLE-WET 0>
    <GOTO ,WARMRAIN-FERN-GALLERY>
    <TELL "TEST PRECONDITION: dry lit ritual candles held one step from canopy drainage." CR>
    <RTRUE>>

<ROUTINE V-BIOME-ANTS-TEST ()
    <BIOME-TEST-RESET>
    <GOTO ,WARMRAIN-ANT-RIDGE>
    <TELL "TEST PRECONDITION: leafcutter dry-root route not yet observed." CR>
    <RTRUE>>

<ROUTINE V-BIOME-FAUNA-TEST ()
    <BIOME-TEST-RESET>
    <GOTO ,WARMRAIN-FROG-POOL>
    <TELL "TEST PRECONDITION: harmless rain-forest fauna available as parser targets." CR>
    <RTRUE>>

<ROUTINE V-BIOME-CAIMAN-TEST ()
    <BIOME-TEST-RESET>
    <COND (<LOC ,DAM-SILVERFIN> <REMOVE-CAREFULLY ,DAM-SILVERFIN>)>
    <MOVE ,DAM-SILVERFIN ,WINNER>
    <MOVE ,WARMRAIN-CAIMAN ,WARMRAIN-CAIMAN-FORD>
    <GOTO ,WARMRAIN-CAIMAN-FORD>
    <TELL "TEST PRECONDITION: caiman owns ford; exact living dam silverfin held." CR>
    <RTRUE>>

<ROUTINE V-BIOME-CAIMAN-DEATH-TEST ()
    <BIOME-TEST-RESET>
    <MOVE ,WARMRAIN-CAIMAN ,WARMRAIN-CAIMAN-FORD>
    <GOTO ,WARMRAIN-CAIMAN-FORD>
    <TELL "TEST PRECONDITION: occupied caiman ford ready for repeated reckless entry." CR>
    <RTRUE>>

<ROUTINE V-BIOME-VINES-TEST ()
    <BIOME-TEST-RESET>
    <COND (<IN? ,WILDERNESS-MACHETE ,WINNER> <REMOVE-CAREFULLY ,WILDERNESS-MACHETE>)>
    <MOVE ,WILDERNESS-MACHETE ,WINNER>
    <GOTO ,WARMRAIN-VINE-COLONNADE>
    <TELL "TEST PRECONDITION: woody vine bypass closed; real machete held." CR>
    <RTRUE>>
