"TEST-ONLY ZORK PLUS VETERAN EXPEDITION PRECONDITIONS"

<SYNTAX VETSETLAMP = V-VETERAN-TEST-LAMP>
<SYNTAX VETSETROPE = V-VETERAN-TEST-ROPE>

<ROUTINE VETERAN-TEST-SEAL-A ()
    <SETG WON-FLAG T>
    <EXPEDITION-ENSURE>
    <COND (<NOT <EXPEDITION-HAS? ,ES-SEALED 1>>
           <EXPEDITION-CAPTURE-A>)>
    <MOVE ,WINNER ,ATTIC>
    <VETERAN-MATERIALIZE>
    <RTRUE>>

<ROUTINE V-VETERAN-TEST-LAMP ()
    <VETERAN-TEST-SEAL-A>
    <MOVE ,LAMP ,WINNER>
    <MOVE ,ROPE ,WINNER>
    <TELL "TEST PRECONDITION: sealed Expedition A, brass lantern and extra rope carried in the Attic." CR>
    <RTRUE>>

<ROUTINE V-VETERAN-TEST-ROPE ()
    <VETERAN-TEST-SEAL-A>
    <MOVE ,ROPE ,WINNER>
    <MOVE ,LAMP ,WINNER>
    <TELL "TEST PRECONDITION: sealed Expedition A, rope and extra brass lantern carried in the Attic." CR>
    <RTRUE>>
