"Test-only setup verbs for Shadow Logic qualification."

<SYNTAX SHADOWLAB = V-SHADOW-LAB>

<ROUTINE V-SHADOW-LAB ()
	<GOTO ,WEST-OF-HOUSE>
	<MOVE ,TORCH ,WINNER>
	<FSET ,TORCH ,ONBIT>
	<FSET ,TORCH ,FLAMEBIT>
	<FSET ,TORCH ,LIGHTBIT>
	<MOVE ,BOTTLE ,WINNER>
	<FSET ,BOTTLE ,OPENBIT>
	<MOVE ,WATER ,BOTTLE>
	<MOVE ,SWORD ,WINNER>
	<MOVE ,ROPE ,WINNER>
	<MOVE ,GARLIC ,WINNER>
	<MOVE ,OWNERS-MANUAL ,WINNER>
	<MOVE ,MIRROR-1 ,HERE>
	<SETG SHADOW-SELF-FIRE 0>
	<SETG SHADOW-SELF-TIED <>>
	<SETG SHADOW-GARLIC-SCENT <>>
	<SETG SHADOW-MELZAR-KNOWN <>>
	<SETG SHADOW-MIRROR-DIAGNOSED <>>
	<SETG SHADOW-FOLLY-TORCH <>>
	<SETG SHADOW-FOLLY-WEAPON <>>
	<SETG SHADOW-FOLLY-ROPE <>>
	<SETG SHADOW-FOLLY-CARRIED-FIRE <>>
	<SETG CLOCK-WAIT T>
	<TELL "[Test-only Shadow Logic laboratory prepared.]" CR>>
