"TEST-ONLY FIRE / SMOKE / STRUCTURAL PRECONDITIONS"

<SYNTAX FIREPREP = V-FIRE-PREP-TEST>
<SYNTAX FIRESTATUS = V-FIRE-STATUS-TEST>

<ROUTINE FIRE-TEST-RESET ()
    <FIRE-STRUCTURAL-RESET>
    <MOVE ,TORCH ,WINNER>
    <FSET ,TORCH ,ONBIT>
    <FSET ,TORCH ,FLAMEBIT>
    <MOVE ,BOTTLE ,WINNER>
    <FSET ,BOTTLE ,OPENBIT>
    <MOVE ,WATER ,BOTTLE>
    <GOTO ,TIMBER-ROOM>
    <RTRUE>>

<ROUTINE V-FIRE-PREP-TEST ()
    <FIRE-TEST-RESET>
    <TELL "TEST PRECONDITION: Timber Room, live ivory torch, open bottle, real water." CR>
    <RTRUE>>

<ROUTINE V-FIRE-STATUS-TEST ("AUX" STAGE)
    <SET STAGE <FIRE-STRUCTURAL-STAGE>>
    <TELL "TEST timber fire state: ">
    <COND (<EQUAL? .STAGE ,FIRE-TIMBER-COLD> <TELL "cold">)
          (<EQUAL? .STAGE ,FIRE-TIMBER-SMOLDER> <TELL "smoldering">)
          (<EQUAL? .STAGE ,FIRE-TIMBER-BURNING> <TELL "burning">)
          (<EQUAL? .STAGE ,FIRE-TIMBER-COLLAPSED-HOT> <TELL "collapsed-hot">)
          (<EQUAL? .STAGE ,FIRE-TIMBER-CHARRED> <TELL "charred">)
          (T <TELL "doused">)>
    <CRLF>
    <RTRUE>>
