"TEST-ONLY MARA HONESTY PRECONDITIONS"

<SYNTAX MARASETUP = V-MARA-HONEST-SETUP>
<SYNTAX MARASOLO = V-MARA-HONEST-SOLO>
<SYNTAX MARAHOME = V-MARA-HONEST-HOME>

<ROUTINE V-MARA-HONEST-SETUP ()
    <MOVE ,MARA ,DAM-BASE>
    <MARA-PUT ,MARA-SLOT-MET 1>
    <MARA-PUT ,MARA-SLOT-DAM-SURVEY 1>
    <MARA-PUT ,MARA-SLOT-HOUSE-VISITED 1>
    <MARA-PUT ,MARA-SLOT-FISH-WITNESSED 0>
    <MARA-PUT ,MARA-SLOT-FISH-RELEASED 0>
    <MARA-PUT ,MARA-SLOT-MODE ,MARA-MODE-WAITING>
    <GOTO ,DAM-BASE>
    <TELL "TEST PRECONDITION: Mara at Dam Base with a joint survey; she has not witnessed a new catch." CR>
    <RTRUE>>

<ROUTINE V-MARA-HONEST-SOLO ()
    <MOVE ,MARA ,LIVING-ROOM>
    <MARA-PUT ,MARA-SLOT-MODE ,MARA-MODE-WAITING>
    <MARA-PUT ,MARA-SLOT-FISH-WITNESSED 0>
    <GOTO ,DAM-BASE>
    <TELL "TEST PRECONDITION: Mara waiting in the Living Room; player at the river." CR>
    <RTRUE>>

<ROUTINE V-MARA-HONEST-HOME ()
    <GOTO ,LIVING-ROOM>
    <TELL "TEST PRECONDITION: Living Room with Mara if she was moved here." CR>
    <RTRUE>>
