"TEST-ONLY RELEASE 1266 LEARNED-MAGIC PRECONDITIONS"

<SYNTAX LMBASE = V-LEARNED-MAGIC-BASE-TEST>
<SYNTAX LMWET = V-LEARNED-MAGIC-WET-TEST>
<SYNTAX LMRITUAL = V-LEARNED-MAGIC-RITUAL-TEST>
<SYNTAX LMHOUSE = V-LEARNED-MAGIC-HOUSE-TEST>
<SYNTAX LMSTAT = V-LEARNED-MAGIC-STATUS-TEST>

<ROUTINE LEARNED-MAGIC-TEST-RESET ()
    <SETG LEARNED-STILLING-WARD <>>
    <SETG LEARNED-WARD-FAILED-UNTAUGHT <>>
    <SETG LEARNED-WARD-CANDLES-DRIED <>>
    <SETG LEARNED-WARD-HOT-BELL-COOLED <>>
    <SETG RITUAL-CEREMONY-KNOWN <>>
    <SETG RITUAL-BELL-ANSWERED <>>
    <SETG RITUAL-CANDLES-ANSWERED <>>
    <SETG RITUAL-PRAYER-COMPLETED <>>
    <SETG LLD-FLAG <>>
    <SETG XB <>>
    <SETG XC <>>
    <RTRUE>>

<ROUTINE V-LEARNED-MAGIC-BASE-TEST ()
    <LEARNED-MAGIC-TEST-RESET>
    <REMOVE-CAREFULLY ,HOT-BELL>
    <MOVE ,BOOK ,WINNER>
    <MOVE ,CANDLES ,WINNER>
    <MOVE ,LAMP ,WINNER>
    <FCLEAR ,CANDLES ,RMUNGBIT>
    <FCLEAR ,CANDLES ,ONBIT>
    <CONSUMABLE-LIGHT-PUT ,CL-CANDLE-WET 0>
    <GOTO ,LIVING-ROOM>
    <TELL "TEST PRECONDITION: black book and dry ritual candles held; ceremonial order and stilling ward are both unknown." CR>
    <RTRUE>>

<ROUTINE V-LEARNED-MAGIC-WET-TEST ()
    <LEARNED-MAGIC-TEST-RESET>
    <SETG RITUAL-CEREMONY-KNOWN T>
    <SETG LEARNED-STILLING-WARD T>
    <DISABLE <INT I-CANDLES>>
    <MOVE ,CANDLES ,WINNER>
    <FCLEAR ,CANDLES ,RMUNGBIT>
    <FCLEAR ,CANDLES ,ONBIT>
    <FSET ,CANDLES ,TOUCHBIT>
    <CONSUMABLE-LIGHT-PUT ,CL-CANDLE-STAGE ,LIGHT-WEAK>
    <CONSUMABLE-LIGHT-PUT ,CL-CANDLE-WET 4>
    <GOTO ,LIVING-ROOM>
    <TELL "TEST PRECONDITION: learned stilling ward and real waterlogged ritual candles held in a safe lit room." CR>
    <RTRUE>>

<ROUTINE V-LEARNED-MAGIC-RITUAL-TEST ()
    <LEARNED-MAGIC-TEST-RESET>
    <SETG RITUAL-CEREMONY-KNOWN T>
    <SETG LEARNED-STILLING-WARD T>
    <REMOVE-CAREFULLY ,HOT-BELL>
    <MOVE ,BELL ,WINNER>
    <MOVE ,CANDLES ,WINNER>
    <FCLEAR ,CANDLES ,ONBIT>
    <FCLEAR ,CANDLES ,RMUNGBIT>
    <MOVE ,BOOK ,WINNER>
    <GOTO ,ENTRANCE-TO-HADES>
    <TELL "TEST PRECONDITION: learned stilling ward at the untouched canonical Hades ceremony with the real bell, candles, and black book." CR>
    <RTRUE>>

<ROUTINE V-LEARNED-MAGIC-HOUSE-TEST ()
    <LEARNED-MAGIC-TEST-RESET>
    <SETG RITUAL-CEREMONY-KNOWN T>
    <SETG LEARNED-STILLING-WARD T>
    <MOVE ,GARLIC ,WINNER>
    <GOTO ,LIVING-ROOM>
    <TELL "TEST PRECONDITION: learned stilling ward in the white house with real garlic held and no forced supernatural incident." CR>
    <RTRUE>>

<ROUTINE V-LEARNED-MAGIC-STATUS-TEST ()
    <TELL "TEST learned magic state: known=" N <COND (,LEARNED-STILLING-WARD 1) (T 0)>
          " untaught-fail=" N <COND (,LEARNED-WARD-FAILED-UNTAUGHT 1) (T 0)>
          " candles-dried=" N <COND (,LEARNED-WARD-CANDLES-DRIED 1) (T 0)>
          " bell-cooled=" N <COND (,LEARNED-WARD-HOT-BELL-COOLED 1) (T 0)>
          " candle-wet=" N <CONSUMABLE-LIGHT-GET ,CL-CANDLE-WET>
          " candles-on=" N <COND (<FSET? ,CANDLES ,ONBIT> 1) (T 0)>
          " bell-present=" N <COND (<ACCESSIBLE? ,BELL> 1) (T 0)>
          " hot-bell-present=" N <COND (<ACCESSIBLE? ,HOT-BELL> 1) (T 0)>
          " xb=" N <COND (,XB 1) (T 0)> CR>
    <RTRUE>>
