"Test-only setup, mutation, and reporting verbs for Release 1216 save/restore qualification."

<SYNTAX PTROLL = V-PERSIST-TROLL-SET>
<SYNTAX UTROLL = V-PERSIST-TROLL-MUTATE>
<SYNTAX RTROLL = V-PERSIST-TROLL-REPORT>
<SYNTAX PECAT = V-PERSIST-EGG-CAUGHT-SET>
<SYNTAX PEBRK = V-PERSIST-EGG-BROKEN-SET>
<SYNTAX UEGG = V-PERSIST-EGG-MUTATE>
<SYNTAX REGG = V-PERSIST-EGG-REPORT>
<SYNTAX PDAM = V-PERSIST-DAM-SET>
<SYNTAX UDAM = V-PERSIST-DAM-MUTATE>
<SYNTAX RDAM = V-PERSIST-DAM-REPORT>
<SYNTAX PRITE = V-PERSIST-RITUAL-SET>
<SYNTAX URITE = V-PERSIST-RITUAL-MUTATE>
<SYNTAX RRITE = V-PERSIST-RITUAL-REPORT>
<SYNTAX PTIMER = V-PERSIST-TIMER-SET>
<SYNTAX UTIMER = V-PERSIST-TIMER-MUTATE>
<SYNTAX RTIMER = V-PERSIST-TIMER-REPORT>

<ROUTINE PERSIST-COMMON ()
	<QUEUE I-THIEF 0>
	<SETG THIEF-HERE <>>
	<REMOVE-CAREFULLY ,THIEF>
	<MOVE ,LAMP ,WINNER>
	<FSET ,LAMP ,ONBIT>
	<FSET ,LAMP ,LIGHTBIT>
	<RTRUE>>

<ROUTINE PERSIST-BOOL (VALUE)
	<COND (.VALUE <TELL "yes">)
	      (T <TELL "no">)>>

<ROUTINE V-PERSIST-TROLL-SET ()
	<PERSIST-COMMON>
	<DISABLE <INT I-GLULX-ALT-TROLL-RECOVER>>
	<MOVE ,TROLL ,TROLL-ROOM>
	<MOVE ,ROPE ,TROLL>
	<MOVE ,AXE ,TROLL-ROOM>
	<FSET ,ROPE ,NDESCBIT>
	<FCLEAR ,TROLL ,FIGHTBIT>
	<SETG GLULX-ALT-TROLL-DISTRACTED <>>
	<SETG GLULX-ALT-TROLL-TRICK-USED T>
	<SETG GLULX-ALT-TROLL-BOUND T>
	<SETG TROLL-FLAG T>
	<PUTP ,TROLL ,P?LDESC
"A nasty-looking troll is tied securely with the rope and wedged resentfully against the wall. All passages are open.">
	<GOTO ,TROLL-ROOM>
	<SETG CLOCK-WAIT T>
	<TELL "[Test-only bound-troll persistence state established.]" CR>>

<ROUTINE V-PERSIST-TROLL-MUTATE ()
	<GLULX-ALT-UNTIE-TROLL>
	<SETG CLOCK-WAIT T>
	<TELL "[Test-only troll state mutated after save.]" CR>>

<ROUTINE V-PERSIST-TROLL-REPORT ()
	<TELL "[PERSIST troll bound=">
	<PERSIST-BOOL ,GLULX-ALT-TROLL-BOUND>
	<TELL " passage=">
	<COND (,TROLL-FLAG <TELL "open">) (T <TELL "blocked">)>
	<TELL " rope=">
	<COND (<IN? ,ROPE ,TROLL> <TELL "troll">)
	      (<IN? ,ROPE ,WINNER> <TELL "player">)
	      (<IN? ,ROPE ,HERE> <TELL "room">)
	      (T <TELL "elsewhere">)>
	<TELL " axe=">
	<COND (<IN? ,AXE ,TROLL> <TELL "troll">)
	      (<IN? ,AXE ,HERE> <TELL "room">)
	      (<IN? ,AXE ,WINNER> <TELL "player">)
	      (T <TELL "elsewhere">)>
	<TELL "]" CR>
	<SETG CLOCK-WAIT T>>

<ROUTINE PERSIST-EGG-BASE ()
	<PERSIST-COMMON>
	<MOVE ,TORCH ,WINNER>
	<FSET ,TORCH ,ONBIT>
	<FSET ,TORCH ,FLAMEBIT>
	<MOVE ,NEST ,UP-A-TREE>
	<MOVE ,EGG ,NEST>
	<MOVE ,CANARY ,EGG>
	<MOVE ,SANDWICH-BAG ,PATH>
	<MOVE ,LUNCH ,SANDWICH-BAG>
	<FSET ,SANDWICH-BAG ,OPENBIT>
	<FSET ,SANDWICH-BAG ,SEARCHBIT>
	<SETG GLULX-ALT-NEST-BURNED <>>
	<SETG GLULX-ALT-EGG-CAUGHT <>>
	<SETG GLULX-ALT-SACK-PREPARED <>>
	<GOTO ,UP-A-TREE>
	<RTRUE>>

<ROUTINE V-PERSIST-EGG-CAUGHT-SET ()
	<PERSIST-EGG-BASE>
	<SETG GLULX-ALT-SACK-PREPARED T>
	<SETG PRSO ,NEST>
	<SETG PRSI ,TORCH>
	<GLULX-ALT-BURN-NEST>
	<SETG CLOCK-WAIT T>
	<TELL "[Test-only intact-egg persistence state established.]" CR>>

<ROUTINE V-PERSIST-EGG-BROKEN-SET ()
	<PERSIST-EGG-BASE>
	<SETG GLULX-ALT-SACK-PREPARED <>>
	<SETG PRSO ,NEST>
	<SETG PRSI ,TORCH>
	<GLULX-ALT-BURN-NEST>
	<SETG CLOCK-WAIT T>
	<TELL "[Test-only broken-egg persistence state established.]" CR>>

<ROUTINE V-PERSIST-EGG-MUTATE ()
	<MOVE ,NEST ,UP-A-TREE>
	<MOVE ,EGG ,NEST>
	<MOVE ,CANARY ,EGG>
	<REMOVE-CAREFULLY ,BROKEN-EGG>
	<REMOVE-CAREFULLY ,BROKEN-CANARY>
	<SETG GLULX-ALT-NEST-BURNED <>>
	<SETG GLULX-ALT-EGG-CAUGHT <>>
	<SETG GLULX-ALT-SACK-PREPARED <>>
	<SETG CLOCK-WAIT T>
	<TELL "[Test-only egg state reset after save.]" CR>>

<ROUTINE V-PERSIST-EGG-REPORT ()
	<TELL "[PERSIST egg burned=">
	<PERSIST-BOOL ,GLULX-ALT-NEST-BURNED>
	<TELL " caught=">
	<PERSIST-BOOL ,GLULX-ALT-EGG-CAUGHT>
	<TELL " intact-in-sack=">
	<PERSIST-BOOL <IN? ,EGG ,SANDWICH-BAG>>
	<TELL " broken-present=">
	<PERSIST-BOOL <OR <IN? ,BROKEN-EGG ,HERE> <IN? ,BROKEN-EGG ,PATH>>>
	<TELL " nest-in-tree=">
	<PERSIST-BOOL <IN? ,NEST ,UP-A-TREE>>
	<TELL "]" CR>
	<SETG CLOCK-WAIT T>>

<ROUTINE V-PERSIST-DAM-SET ()
	<PERSIST-COMMON>
	<QUEUE I-RFILL 0>
	<QUEUE I-REMPTY 0>
	<QUEUE I-MAINT-ROOM 0>
	<SETG GATE-FLAG T>
	<SETG GATES-OPEN T>
	<SETG LOW-TIDE T>
	<SETG WATER-LEVEL 3>
	<FCLEAR ,LEAK ,INVISIBLE>
	<FSET ,MAINTENANCE-ROOM ,ONBIT>
	<SETG DAM-MECH-PANEL-DIAGNOSED T>
	<SETG DAM-MECH-INTERLOCK-SEEN T>
	<SETG DAM-MECH-BOLT-ATTEMPTED T>
	<SETG DAM-MECH-GATES-CYCLED T>
	<SETG DAM-MECH-LIGHTS-TOGGLED T>
	<SETG DAM-MECH-LEAK-TRIGGERED T>
	<SETG DAM-MECH-LEAK-REPAIRED <>>
	<SETG DAM-MECH-TOOL-PROBED T>
	<GOTO ,MAINTENANCE-ROOM>
	<SETG CLOCK-WAIT T>
	<TELL "[Test-only active-dam persistence state established.]" CR>>

<ROUTINE V-PERSIST-DAM-MUTATE ()
	<SETG GATE-FLAG <>>
	<SETG GATES-OPEN <>>
	<SETG LOW-TIDE <>>
	<SETG WATER-LEVEL -1>
	<FSET ,LEAK ,INVISIBLE>
	<FCLEAR ,MAINTENANCE-ROOM ,ONBIT>
	<SETG DAM-MECH-PANEL-DIAGNOSED <>>
	<SETG DAM-MECH-INTERLOCK-SEEN <>>
	<SETG DAM-MECH-BOLT-ATTEMPTED <>>
	<SETG DAM-MECH-GATES-CYCLED <>>
	<SETG DAM-MECH-LIGHTS-TOGGLED <>>
	<SETG DAM-MECH-LEAK-TRIGGERED <>>
	<SETG DAM-MECH-LEAK-REPAIRED T>
	<SETG DAM-MECH-TOOL-PROBED <>>
	<SETG CLOCK-WAIT T>
	<TELL "[Test-only dam state mutated after save.]" CR>>

<ROUTINE V-PERSIST-DAM-REPORT ()
	<TELL "[PERSIST dam interlock=">
	<COND (,GATE-FLAG <TELL "armed">) (T <TELL "disarmed">)>
	<TELL " gates=">
	<COND (,GATES-OPEN <TELL "open">) (T <TELL "closed">)>
	<TELL " tide=">
	<COND (,LOW-TIDE <TELL "low">) (T <TELL "high">)>
	<TELL " water=" N ,WATER-LEVEL " leak-visible=">
	<PERSIST-BOOL <NOT <FSET? ,LEAK ,INVISIBLE>>>
	<TELL " room-lit=">
	<PERSIST-BOOL <FSET? ,MAINTENANCE-ROOM ,ONBIT>>
	<TELL " repaired=">
	<PERSIST-BOOL ,DAM-MECH-LEAK-REPAIRED>
	<TELL "]" CR>
	<SETG CLOCK-WAIT T>>

<ROUTINE V-PERSIST-RITUAL-SET ()
	<PERSIST-COMMON>
	<QUEUE I-XB 0>
	<QUEUE I-XC 0>
	<QUEUE I-XBH 0>
	<SETG XB <>>
	<SETG XC T>
	<SETG LLD-FLAG T>
	<REMOVE-CAREFULLY ,GHOSTS>
	<REMOVE-CAREFULLY ,HOT-BELL>
	<MOVE ,BELL ,WINNER>
	<MOVE ,BOOK ,WINNER>
	<MOVE ,CANDLES ,WINNER>
	<SETG RITUAL-CEREMONY-KNOWN T>
	<SETG RITUAL-BELL-RESONANCE-HEARD T>
	<SETG RITUAL-BELL-ANSWERED T>
	<SETG RITUAL-CANDLES-ANSWERED T>
	<SETG RITUAL-PRAYER-COMPLETED T>
	<SETG RITUAL-MIRROR-RESONANCE T>
	<SETG RITUAL-HOT-BELL-COOLED T>
	<SETG RITUAL-WRONG-ORDER-SEEN T>
	<GOTO ,ENTRANCE-TO-HADES>
	<SETG CLOCK-WAIT T>
	<TELL "[Test-only completed-ritual persistence state established.]" CR>>

<ROUTINE V-PERSIST-RITUAL-MUTATE ()
	<SETG XB T>
	<SETG XC <>>
	<SETG LLD-FLAG <>>
	<MOVE ,GHOSTS ,ENTRANCE-TO-HADES>
	<REMOVE-CAREFULLY ,BELL>
	<MOVE ,HOT-BELL ,ENTRANCE-TO-HADES>
	<SETG RITUAL-CEREMONY-KNOWN <>>
	<SETG RITUAL-BELL-RESONANCE-HEARD <>>
	<SETG RITUAL-BELL-ANSWERED <>>
	<SETG RITUAL-CANDLES-ANSWERED <>>
	<SETG RITUAL-PRAYER-COMPLETED <>>
	<SETG RITUAL-MIRROR-RESONANCE <>>
	<SETG RITUAL-HOT-BELL-COOLED <>>
	<SETG RITUAL-WRONG-ORDER-SEEN <>>
	<SETG CLOCK-WAIT T>
	<TELL "[Test-only ritual state mutated after save.]" CR>>

<ROUTINE V-PERSIST-RITUAL-REPORT ()
	<TELL "[PERSIST ritual known=">
	<PERSIST-BOOL ,RITUAL-CEREMONY-KNOWN>
	<TELL " xb=">
	<PERSIST-BOOL ,XB>
	<TELL " xc=">
	<PERSIST-BOOL ,XC>
	<TELL " complete=">
	<PERSIST-BOOL ,LLD-FLAG>
	<TELL " ghosts-present=">
	<PERSIST-BOOL <IN? ,GHOSTS ,ENTRANCE-TO-HADES>>
	<TELL " bell=">
	<COND (<IN? ,BELL ,WINNER> <TELL "cool-held">)
	      (<IN? ,BELL ,HERE> <TELL "cool-room">)
	      (<IN? ,HOT-BELL ,HERE> <TELL "hot-room">)
	      (T <TELL "elsewhere">)>
	<TELL "]" CR>
	<SETG CLOCK-WAIT T>>

<ROUTINE V-PERSIST-TIMER-SET ()
	<PERSIST-COMMON>
	<DISABLE <INT I-GLULX-ALT-TROLL-RECOVER>>
	<MOVE ,TROLL ,TROLL-ROOM>
	<MOVE ,AXE ,TROLL>
	<MOVE ,ROPE ,WINNER>
	<FSET ,TROLL ,FIGHTBIT>
	<SETG GLULX-ALT-TROLL-BOUND <>>
	<SETG GLULX-ALT-TROLL-TRICK-USED T>
	<SETG GLULX-ALT-TROLL-DISTRACTED T>
	<FCLEAR ,TROLL ,FIGHTBIT>
	<ENABLE <QUEUE I-GLULX-ALT-TROLL-RECOVER 3>>
	<GOTO ,TROLL-ROOM>
	<SETG CLOCK-WAIT T>
	<TELL "[Test-only troll-recovery interrupt established.]" CR>>

<ROUTINE V-PERSIST-TIMER-MUTATE ()
	<DISABLE <INT I-GLULX-ALT-TROLL-RECOVER>>
	<SETG GLULX-ALT-TROLL-DISTRACTED <>>
	<FSET ,TROLL ,FIGHTBIT>
	<SETG CLOCK-WAIT T>
	<TELL "[Test-only interrupt state mutated after save.]" CR>>

<ROUTINE V-PERSIST-TIMER-REPORT ()
	<TELL "[PERSIST timer distracted=">
	<PERSIST-BOOL ,GLULX-ALT-TROLL-DISTRACTED>
	<TELL " fight=">
	<PERSIST-BOOL <FSET? ,TROLL ,FIGHTBIT>>
	<TELL "]" CR>
	<SETG CLOCK-WAIT T>>