"MARA EARNED ROMANCE TEST VERBS — test story only"

<SYNTAX ROMSAFE = V-ROM-SAFE>
<SYNTAX ROMHALF = V-ROM-HALF>
<SYNTAX ROMRUPTURE = V-ROM-RUPTURE>
<SYNTAX ROMFRIEND = V-ROM-FRIEND>

<ROUTINE V-ROM-HALF ()
    <MARA-ENSURE>
    <MOVE ,MARA ,HERE>
    <MARA-PUT ,MARA-SLOT-MEAL-SHARED 1>
    <MARA-PUT ,MARA-SLOT-DAM-SURVEY 1>
    <MARA-PUT ,MARA-SLOT-BIO-RESCUED-MARA 0>
    <MARA-PUT ,MARA-SLOT-BIO-ROPE-RETURNED 0>
    <MARA-PUT ,MARA-SLOT-BIO-MARA-RESCUED-YOU 0>
    <MARA-PUT ,MARA-SLOT-RUPTURE-OPEN 0>
    <MARA-PUT ,MARA-SLOT-PARTNERSHIP-ACCEPTED 0>
    <MARA-PUT ,MARA-SLOT-PARTNERSHIP-POSTPONED 0>
    <TELL "[TEST] Mara is here with meal and Dam history, but not reciprocal rescue." CR>>

<ROUTINE V-ROM-SAFE ()
    <MARA-ENSURE>
    <MOVE ,MARA ,HERE>
    <MARA-PUT ,MARA-SLOT-MEAL-SHARED 1>
    <MARA-PUT ,MARA-SLOT-DAM-SURVEY 1>
    <MARA-PUT ,MARA-SLOT-BIO-RESCUED-MARA 1>
    <MARA-PUT ,MARA-SLOT-BIO-ROPE-RETURNED 1>
    <MARA-PUT ,MARA-SLOT-BIO-MARA-RESCUED-YOU 1>
    <MARA-PUT ,MARA-SLOT-RUPTURE-OPEN 0>
    <TELL "[TEST] Mara is here with earned Dam, meal, and reciprocal-rescue history." CR>>

<ROUTINE V-ROM-RUPTURE ()
    <MARA-ENSURE>
    <MOVE ,MARA ,HERE>
    <MARA-PUT ,MARA-SLOT-RUPTURE-OPEN 1>
    <MARA-PUT ,MARA-SLOT-INTENTIONAL-HARM 1>
    <TELL "[TEST] Rupture is open." CR>>

<ROUTINE V-ROM-FRIEND ()
    <MARA-ENSURE>
    <MOVE ,MARA ,HERE>
    <MARA-PUT ,MARA-SLOT-PARTNERSHIP-REFUSED 1>
    <MARA-PUT ,MARA-SLOT-RUPTURE-OPEN 0>
    <TELL "[TEST] Partnership refused; colleague work remains." CR>>
