"TEST-ONLY THIEF RETALIATION PRECONDITIONS"

<SYNTAX THIEFSABOTAGE = V-THIEF-SABOTAGE-TEST>
<SYNTAX THIEFSTEAL = V-THIEF-STEAL-TEST>
<SYNTAX THIEFAVOID = V-THIEF-AVOID-TEST>
<SYNTAX THIEFAPPEASE = V-THIEF-APPEASE-TEST>
<SYNTAX THIEFSTATUS = V-THIEF-STATUS-TEST>

<ROUTINE THIEF-RETALIATION-TEST-RESET ()
    <DISABLE <INT I-THIEF>>
    <MOVE ,THIEF ,ROUND-ROOM>
    <MOVE ,LARGE-BAG ,THIEF>
    <MOVE ,STILETTO ,THIEF>
    <FSET ,STILETTO ,NDESCBIT>
    <FCLEAR ,THIEF ,FIGHTBIT>
    <FSET ,THIEF ,INVISIBLE>
    <SETG THIEF-HERE <>>
    <SETG THIEF-RETALIATING T>
    <PUTP ,THIEF ,P?STRENGTH 5>
    <MOVE ,LAMP ,WINNER>
    <FSET ,LAMP ,ONBIT>
    <MOVE ,SANDWICH-BAG ,WINNER>
    <MOVE ,LUNCH ,SANDWICH-BAG>
    <MOVE ,GARLIC ,SANDWICH-BAG>
    <MOVE ,WRENCH ,MAINTENANCE-ROOM>
    <MOVE ,SCREWDRIVER ,MAINTENANCE-ROOM>
    <MOVE ,KEYS ,MAZE-5>
    <MOVE ,MATCH ,DAM-LOBBY>
    <MOVE ,SHOVEL ,SANDY-BEACH>
    <MOVE ,SWORD ,LIVING-ROOM>
    <MOVE ,KNIFE ,ATTIC-TABLE>
    <MOVE ,RUSTY-KNIFE ,MAZE-5>
    <GOTO ,ROUND-ROOM>
    <RFALSE>>

<ROUTINE V-THIEF-SABOTAGE-TEST ()
    <THIEF-RETALIATION-TEST-RESET>
    <THIEF-RETALIATION-STRIKE>
    <TELL "TEST PRECONDITION: retaliatory sack sabotage executed without destroying any object." CR>
    <RTRUE>>

<ROUTINE V-THIEF-STEAL-TEST ()
    <THIEF-RETALIATION-TEST-RESET>
    <MOVE ,LUNCH ,KITCHEN-TABLE>
    <MOVE ,GARLIC ,KITCHEN-TABLE>
    <MOVE ,WRENCH ,WINNER>
    <THIEF-RETALIATION-STRIKE>
    <TELL "TEST PRECONDITION: retaliatory selective tool theft executed." CR>
    <RTRUE>>

<ROUTINE V-THIEF-AVOID-TEST ()
    <THIEF-RETALIATION-TEST-RESET>
    <MOVE ,SWORD ,WINNER>
    <THIEF-RETALIATION-STRIKE>
    <TELL "TEST PRECONDITION: visible steel deterrence executed." CR>
    <RTRUE>>

<ROUTINE V-THIEF-APPEASE-TEST ()
    <THIEF-RETALIATION-TEST-RESET>
    <FCLEAR ,THIEF ,INVISIBLE>
    <SETG THIEF-HERE T>
    <MOVE ,PAINTING ,WINNER>
    <PERFORM ,V?GIVE ,PAINTING ,THIEF>
    <TELL "TEST PRECONDITION: valuable-gift appeasement executed." CR>
    <RTRUE>>

<ROUTINE V-THIEF-STATUS-TEST ()
    <COND (,THIEF-RETALIATING
           <TELL "TEST thief retaliation: active" CR>)
          (T <TELL "TEST thief retaliation: settled" CR>)>
    <COND (<IN? ,WRENCH ,THIEF>
           <TELL "TEST wrench custody: thief" CR>)>
    <COND (<FSET? ,THIEF ,INVISIBLE>
           <TELL "TEST thief visibility: hidden" CR>)
          (T <TELL "TEST thief visibility: visible" CR>)>
    <RTRUE>>
