"RELEASE 1309 MARA BOUNDARY TEST SETUP — test story only"

<SYNTAX BNDCOAT = V-BND-COAT>
<SYNTAX BNDFOOD = V-BND-FOOD>
<SYNTAX BNDHERE = V-BND-HERE>
<SYNTAX BNDAUTO = V-BND-AUTO>

<ROUTINE BND-CLEAR ()
    <MARA-ENSURE>
    <MOVE ,MARA ,HERE>
    <MOVE ,MARA-TRAVEL-COAT ,MARA>
    <REMOVE ,MARA-FIELD-RATION>
    <SETG MARA-BOUNDARY-RUPTURE-KIND ,MARA-BOUNDARY-NONE>
    <SETG MARA-CLOTHING-BOUNDARY-COUNT 0>
    <SETG MARA-FOOD-BOUNDARY-COUNT 0>
    <SETG MARA-AUTONOMY-BOUNDARY-COUNT 0>
    <SETG MARA-RATION-STOLEN 0>
    <SETG MARA-RATION-CONSUMED 0>
    <MARA-PUT ,MARA-SLOT-RUPTURE-OPEN 0>
    <MARA-PUT ,MARA-SLOT-RUPTURE-REPAIRED 0>
    <MARA-PUT ,MARA-SLOT-APOLOGY-ACKNOWLEDGED 0>
    <MARA-PUT ,MARA-SLOT-BOUNDARY-RESPECTED 0>
    <MARA-PUT ,MARA-SLOT-INTENTIONAL-HARM 0>
    <MARA-PUT ,MARA-SLOT-PARTNERSHIP-ACCEPTED 1>
    <MARA-PUT ,MARA-SLOT-PARTNERSHIP-REFUSED 0>
    <MARA-PUT ,MARA-SLOT-MODE ,MARA-MODE-WAITING>
    <RTRUE>>

<ROUTINE V-BND-COAT ()
    <BND-CLEAR>
    <TELL "[TEST] Mara is here; coat boundary history is clear." CR>
    <RFATAL>>

<ROUTINE V-BND-FOOD ()
    <BND-CLEAR>
    <MOVE ,MARA-FIELD-RATION ,HERE>
    <MOVE ,MARA ,KITCHEN>
    <TELL "[TEST] Mara's ration is physically here; Mara is elsewhere." CR>
    <RFATAL>>

<ROUTINE V-BND-HERE ()
    <MOVE ,MARA ,HERE>
    <TELL "[TEST] Mara is physically here." CR>
    <RFATAL>>

<ROUTINE V-BND-AUTO ()
    <BND-CLEAR>
    <MARA-PUT ,MARA-SLOT-MODE ,MARA-MODE-INDEPENDENT>
    <TELL "[TEST] Mara is here and has made an independent choice." CR>
    <RFATAL>>
