"Short, prefix-unique parser aliases for persistence qualification commands."

<SYNTAX PTREADY = V-PERSIST-TROLL-READY>
<SYNTAX PTREPORT = V-PERSIST-TROLL-REPORT>
<SYNTAX PTMUTATE = V-PERSIST-TROLL-MUTATE>

<SYNTAX PEREADY = V-PERSIST-EGG-READY>
<SYNTAX PEREPORT = V-PERSIST-EGG-REPORT>
<SYNTAX PEMUTATE = V-PERSIST-EGG-MUTATE>

<SYNTAX PDREADY = V-PERSIST-DAM-READY>
<SYNTAX PDTOP = V-PERSIST-DAM-TOP>
<SYNTAX PDREPORT = V-PERSIST-DAM-REPORT>
<SYNTAX PDMUTATE = V-PERSIST-DAM-MUTATE>
<SYNTAX PDTIMER = V-PERSIST-DAM-TIMER>

<SYNTAX PLREADY = V-PERSIST-LEAK-READY>
<SYNTAX PLREPORT = V-PERSIST-LEAK-REPORT>
<SYNTAX PLMUTATE = V-PERSIST-LEAK-MUTATE>

<SYNTAX PRREADY = V-PERSIST-RITUAL-READY>
<SYNTAX PRREPORT = V-PERSIST-RITUAL-REPORT>
<SYNTAX PRMUTATE = V-PERSIST-RITUAL-MUTATE>
<SYNTAX PRTIMER = V-PERSIST-RITUAL-TIMER>
