"Test-only setup, mutation, and observation verbs for real SAVE/RESTORE qualification."

<SYNTAX PERSISTTROLLREADY = V-PERSIST-TROLL-READY>
<SYNTAX PERSISTTROLLREPORT = V-PERSIST-TROLL-REPORT>
<SYNTAX PERSISTTROLLMUTATE = V-PERSIST-TROLL-MUTATE>
<SYNTAX PERSISTEGGREADY = V-PERSIST-EGG-READY>
<SYNTAX PERSISTEGGREPORT = V-PERSIST-EGG-REPORT>
<SYNTAX PERSISTEGGMUTATE = V-PERSIST-EGG-MUTATE>
<SYNTAX PERSISTDAMREADY = V-PERSIST-DAM-READY>
<SYNTAX PERSISTDAMTOP = V-PERSIST-DAM-TOP>
<SYNTAX PERSISTDAMREPORT = V-PERSIST-DAM-REPORT>
<SYNTAX PERSISTDAMMUTATE = V-PERSIST-DAM-MUTATE>
<SYNTAX PERSISTDAMTIMER = V-PERSIST-DAM-TIMER>
<SYNTAX PERSISTLEAKREADY = V-PERSIST-LEAK-READY>
<SYNTAX PERSISTLEAKREPORT = V-PERSIST-LEAK-REPORT>
<SYNTAX PERSISTLEAKMUTATE = V-PERSIST-LEAK-MUTATE>
<SYNTAX PERSISTRITUALREADY = V-PERSIST-RITUAL-READY>
<SYNTAX PERSISTRITUALREPORT = V-PERSIST-RITUAL-REPORT>
<SYNTAX PERSISTRITUALMUTATE = V-PERSIST-RITUAL-MUTATE>
<SYNTAX PERSISTRITUALTIMER = V-PERSIST-RITUAL-TIMER>

<ROUTINE PERSIST-QUIET-THIEF ()
	<QUEUE I-THIEF 0>
	<SETG THIEF-HERE <>>
	<REMOVE-CAREFULLY ,THIEF>
	<RTRUE>>

<ROUTINE V-PERSIST-TROLL-READY ()
	<PERSIST-QUIET-THIEF>
	<QUEUE I-GLULX-ALT-TROLL-RECOVER 0>
	<SETG GLULX-ALT-TROLL-DISTRACTED T>
	<SETG GLULX-ALT-TROLL-TRICK-USED T>
	<SETG GLULX-ALT-TROLL-BOUND <>>
	<SETG TROLL-FLAG <>>
	<MOVE ,AXE ,TROLL>
	<MOVE ,ROPE ,WINNER>
	<FSET ,TROLL ,FIGHTBIT>
	<GOTO <LOC ,TROLL>>
	<TELL "PERSIST-SETUP:TROLL-READY" CR>>

<ROUTINE V-PERSIST-TROLL-REPORT ()
	<COND (<AND ,GLULX-ALT-TROLL-BOUND
	            ,TROLL-FLAG
	            <IN? ,ROPE ,TROLL>
	            <NOT <IN? ,AXE ,TROLL>>>
	       <TELL "PERSIST:TROLL=BOUND-ROPE-COMMITTED-AXE-DROPPED-PASSAGES-OPEN" CR>)
	      (T
	       <TELL "PERSIST:TROLL=OTHER" CR>)>>

<ROUTINE V-PERSIST-TROLL-MUTATE ()
	<QUEUE I-GLULX-ALT-TROLL-RECOVER 0>
	<SETG GLULX-ALT-TROLL-DISTRACTED <>>
	<SETG GLULX-ALT-TROLL-BOUND <>>
	<SETG TROLL-FLAG <>>
	<MOVE ,ROPE ,WINNER>
	<FCLEAR ,ROPE ,NDESCBIT>
	<MOVE ,AXE ,TROLL>
	<FSET ,TROLL ,FIGHTBIT>
	<TELL "PERSIST-MUTATED:TROLL" CR>>

<ROUTINE V-PERSIST-EGG-READY ()
	<PERSIST-QUIET-THIEF>
	<SETG GLULX-ALT-NEST-BURNED <>>
	<SETG GLULX-ALT-EGG-CAUGHT <>>
	<SETG GLULX-ALT-SACK-PREPARED <>>
	<MOVE ,SANDWICH-BAG ,WINNER>
	<FSET ,SANDWICH-BAG ,OPENBIT>
	<MOVE ,TORCH ,WINNER>
	<FSET ,TORCH ,ONBIT>
	<FSET ,TORCH ,FLAMEBIT>
	<MOVE ,NEST ,UP-A-TREE>
	<MOVE ,EGG ,NEST>
	<GOTO ,PATH>
	<TELL "PERSIST-SETUP:EGG-READY" CR>>

<ROUTINE V-PERSIST-EGG-REPORT ()
	<COND (<AND ,GLULX-ALT-NEST-BURNED
	            ,GLULX-ALT-EGG-CAUGHT
	            <IN? ,EGG ,SANDWICH-BAG>
	            <IN? ,SANDWICH-BAG ,PATH>>
	       <TELL "PERSIST:EGG=INTACT-IN-PREPARED-SACK" CR>)
	      (T
	       <TELL "PERSIST:EGG=OTHER" CR>)>>

<ROUTINE V-PERSIST-EGG-MUTATE ()
	<SETG GLULX-ALT-NEST-BURNED <>>
	<SETG GLULX-ALT-EGG-CAUGHT <>>
	<SETG GLULX-ALT-SACK-PREPARED <>>
	<MOVE ,EGG ,WINNER>
	<MOVE ,NEST ,UP-A-TREE>
	<MOVE ,SANDWICH-BAG ,WINNER>
	<TELL "PERSIST-MUTATED:EGG" CR>>

<ROUTINE V-PERSIST-DAM-READY ()
	<PERSIST-QUIET-THIEF>
	<QUEUE I-RFILL 0>
	<QUEUE I-REMPTY 0>
	<QUEUE I-MAINT-ROOM 0>
	<SETG GATE-FLAG <>>
	<SETG GATES-OPEN <>>
	<SETG LOW-TIDE <>>
	<SETG WATER-LEVEL 0>
	<FSET ,LEAK ,INVISIBLE>
	<FSET ,MAINTENANCE-ROOM ,ONBIT>
	<MOVE ,WRENCH ,WINNER>
	<MOVE ,LAMP ,WINNER>
	<FSET ,LAMP ,ONBIT>
	<GOTO ,MAINTENANCE-ROOM>
	<TELL "PERSIST-SETUP:DAM-READY" CR>>

<ROUTINE V-PERSIST-DAM-TOP ()
	<GOTO ,DAM-ROOM>
	<TELL "PERSIST-SETUP:DAM-TOP" CR>>

<ROUTINE V-PERSIST-DAM-REPORT ()
	<COND (<AND ,GATE-FLAG ,GATES-OPEN>
	       <TELL "PERSIST:DAM=INTERLOCKED-GATES-OPEN" CR>)
	      (T
	       <TELL "PERSIST:DAM=OTHER" CR>)>>

<ROUTINE V-PERSIST-DAM-MUTATE ()
	<QUEUE I-RFILL 0>
	<QUEUE I-REMPTY 0>
	<SETG GATE-FLAG <>>
	<SETG GATES-OPEN <>>
	<SETG LOW-TIDE <>>
	<TELL "PERSIST-MUTATED:DAM" CR>>

<ROUTINE V-PERSIST-DAM-TIMER ()
	<COND (,LOW-TIDE
	       <TELL "PERSIST:DAM-TIMER=COMPLETED" CR>)
	      (T
	       <TELL "PERSIST:DAM-TIMER=PENDING" CR>)>>

<ROUTINE V-PERSIST-LEAK-READY ()
	<PERSIST-QUIET-THIEF>
	<QUEUE I-MAINT-ROOM 0>
	<SETG WATER-LEVEL 0>
	<FSET ,LEAK ,INVISIBLE>
	<FSET ,MAINTENANCE-ROOM ,ONBIT>
	<MOVE ,PUTTY ,WINNER>
	<MOVE ,LAMP ,WINNER>
	<FSET ,LAMP ,ONBIT>
	<GOTO ,MAINTENANCE-ROOM>
	<TELL "PERSIST-SETUP:LEAK-READY" CR>>

<ROUTINE V-PERSIST-LEAK-REPORT ()
	<COND (<FSET? ,LEAK ,INVISIBLE>
	       <TELL "PERSIST:LEAK=SEALED" CR>)
	      (<G? ,WATER-LEVEL 0>
	       <TELL "PERSIST:LEAK=ACTIVE-AND-RISING" CR>)
	      (T
	       <TELL "PERSIST:LEAK=ACTIVE" CR>)>>

<ROUTINE V-PERSIST-LEAK-MUTATE ()
	<QUEUE I-MAINT-ROOM 0>
	<SETG WATER-LEVEL 0>
	<FSET ,LEAK ,INVISIBLE>
	<TELL "PERSIST-MUTATED:LEAK" CR>>

<ROUTINE V-PERSIST-RITUAL-READY ()
	<PERSIST-QUIET-THIEF>
	<QUEUE I-XB 0>
	<QUEUE I-XC 0>
	<QUEUE I-XBH 0>
	<QUEUE I-CANDLES 0>
	<QUEUE I-MATCH 0>
	<SETG XB <>>
	<SETG XC <>>
	<SETG LLD-FLAG <>>
	<SETG MATCH-COUNT 6>
	<REMOVE-CAREFULLY ,HOT-BELL>
	<MOVE ,GHOSTS ,ENTRANCE-TO-HADES>
	<MOVE ,BELL ,WINNER>
	<MOVE ,BOOK ,WINNER>
	<MOVE ,CANDLES ,WINNER>
	<FCLEAR ,CANDLES ,ONBIT>
	<FCLEAR ,CANDLES ,RMUNGBIT>
	<MOVE ,MATCH ,WINNER>
	<FCLEAR ,MATCH ,ONBIT>
	<FCLEAR ,MATCH ,FLAMEBIT>
	<MOVE ,LAMP ,WINNER>
	<FSET ,LAMP ,ONBIT>
	<SETG RITUAL-CEREMONY-KNOWN T>
	<SETG RITUAL-BELL-RESONANCE-HEARD <>>
	<SETG RITUAL-BELL-ANSWERED <>>
	<SETG RITUAL-CANDLES-ANSWERED <>>
	<SETG RITUAL-PRAYER-COMPLETED <>>
	<SETG RITUAL-MIRROR-RESONANCE T>
	<SETG RITUAL-HOT-BELL-COOLED <>>
	<SETG RITUAL-WRONG-ORDER-SEEN T>
	<GOTO ,ENTRANCE-TO-HADES>
	<TELL "PERSIST-SETUP:RITUAL-READY" CR>>

<ROUTINE V-PERSIST-RITUAL-REPORT ()
	<COND (<AND ,LLD-FLAG
	            ,RITUAL-PRAYER-COMPLETED
	            ,RITUAL-BELL-ANSWERED
	            ,RITUAL-CANDLES-ANSWERED
	            ,RITUAL-WRONG-ORDER-SEEN
	            ,RITUAL-MIRROR-RESONANCE
	            <NOT <IN? ,GHOSTS ,ENTRANCE-TO-HADES>>>
	       <TELL "PERSIST:RITUAL=COMPLETED-KNOWLEDGE-AND-GHOST-REMOVAL" CR>)
	      (T
	       <TELL "PERSIST:RITUAL=OTHER" CR>)>>

<ROUTINE V-PERSIST-RITUAL-MUTATE ()
	<QUEUE I-XB 0>
	<QUEUE I-XC 0>
	<QUEUE I-XBH 0>
	<SETG XB <>>
	<SETG XC <>>
	<SETG LLD-FLAG <>>
	<SETG RITUAL-BELL-ANSWERED <>>
	<SETG RITUAL-CANDLES-ANSWERED <>>
	<SETG RITUAL-PRAYER-COMPLETED <>>
	<SETG RITUAL-MIRROR-RESONANCE <>>
	<SETG RITUAL-WRONG-ORDER-SEEN <>>
	<REMOVE-CAREFULLY ,HOT-BELL>
	<MOVE ,BELL ,WINNER>
	<MOVE ,GHOSTS ,ENTRANCE-TO-HADES>
	<TELL "PERSIST-MUTATED:RITUAL" CR>>

<ROUTINE V-PERSIST-RITUAL-TIMER ()
	<COND (<AND <IN? ,BELL ,ENTRANCE-TO-HADES>
	            <NOT <IN? ,HOT-BELL ,ENTRANCE-TO-HADES>>>
	       <TELL "PERSIST:RITUAL-TIMER=HOT-BELL-COOLED" CR>)
	      (T
	       <TELL "PERSIST:RITUAL-TIMER=PENDING" CR>)>>
