"Test-only setup, progression, corruption, and reporting for Release 1228 qualification."

<SYNTAX RSETUP = V-REST-TEST-SETUP>
<SYNTAX RREPORT = V-REST-TEST-REPORT>
<SYNTAX RFOREST = V-REST-TEST-FOREST>
<SYNTAX RDAM = V-REST-TEST-DAM>
<SYNTAX RATTIC = V-REST-TEST-ATTIC>
<SYNTAX RMUTATE = V-REST-TEST-MUTATE>

<ROUTINE REST-TEST-REMOVE (OBJ)
    <COND (<LOC .OBJ> <REMOVE-CAREFULLY .OBJ>)>
    <RTRUE>>

<ROUTINE REST-TEST-RESET ("AUX" (I 0))
    <REPEAT ()
        <COND (<G? .I ,RS-EVENT-RESTORE> <RETURN>)>
        <REST-PUT .I 0>
        <SET I <+ .I 1>>>
    <REST-PUT ,RS-VERSION ,REST-SCHEMA>
    <RTRUE>>

<ROUTINE REST-TEST-CLEAR-MAIL ()
    <MAIL-PUT ,MS-QUEUED 0>
    <MAIL-PUT ,MS-DELIVERED 0>
    <MAIL-PUT ,MS-READ 0>
    <MAIL-PUT ,MS-REPLIED 0>
    <MAIL-PUT ,MS-SENT 0>
    <MAIL-PUT ,MS-REPLY-TARGET 0>
    <MAIL-PUT ,MS-VISITOR-QUEUED 0>
    <MAIL-PUT ,MS-VISITOR-ACTIVE 0>
    <MAIL-PUT ,MS-VISITOR-MISSED 0>
    <MAIL-PUT ,MS-VISITOR-REFUSED 0>
    <MAIL-PUT ,MS-VISITOR-COMPLETE 0>
    <REST-TEST-REMOVE ,MAIL-COURIER-NOTICE>
    <REST-TEST-REMOVE ,MAIL-SURVEYOR-NOTICE>
    <REST-TEST-REMOVE ,MAIL-COURIER>
    <REST-TEST-REMOVE ,MAIL-SURVEYOR>
    <RTRUE>>

<ROUTINE V-REST-TEST-SETUP ()
    <REST-TEST-REMOVE ,REST-OVERNIGHT-REPORT>
    <COND (<NOT <EQUAL? <LOC ,REST-DREAM-NOTEBOOK> ,BEDROOM>>
           <MOVE ,REST-DREAM-NOTEBOOK ,BEDROOM>)>
    <REST-TEST-RESET>
    <REST-TEST-CLEAR-MAIL>

    <SETG HOUSE-EVENT-ENTERED T>
    <SETG HOUSE-EVENT-RETURN T>
    <AREA-PUT ,AREA-SLOT-FOREST 0>
    <SETG DAM-MECH-PANEL-DIAGNOSED <>>
    <SETG DAM-MECH-INTERLOCK-SEEN <>>
    <SETG DAM-MECH-LEAK-REPAIRED <>>
    <SETG RITUAL-BELL-ANSWERED <>>
    <SETG RITUAL-WRONG-ORDER-SEEN <>>
    <SETG RITUAL-PRAYER-COMPLETED <>>
    <NPC-PUT ,NS-SEEN 0>
    <PLAYBACK-PUT ,PB-SLOT-COUNT 0>
    <AREA-PUT ,AREA-SLOT-COMPLETE 0>
    <SETG MUSEUM-EVENT-DISPLAYED <>>
    <SETG MUSEUM-EVENT-CASE <>>
    <SETG MUSEUM-THEFT-OCCURRED <>>
    <CELLAR-PUT ,CS-EVENT-INTRUSION <>>

    <PUTP ,WINNER ,P?STRENGTH -2>
    <FSET ,WINNER ,STAGGERED>
    <SETG SHADOW-GARLIC-SCENT T>
    <SETG SHADOW-SELF-FIRE 0>
    <SETG SHADOW-SELF-TIED <>>

    <MAIL-PUT ,MS-VISITOR-QUEUED ,MAIL-VISITOR-COURIER>
    <MOVE ,LAMP ,WINNER>
    <FSET ,LAMP ,ONBIT>
    <GOTO ,BEDROOM>
    <SETG CLOCK-WAIT T>
    <TELL "REST-SETUP:READY" CR>>

<ROUTINE REST-TEST-PRESENT (OBJ)
    <COND (<LOC .OBJ> <TELL "Y">) (T <TELL "N">)>>

<ROUTINE V-REST-TEST-REPORT ()
    <TELL "REST:VERSION=" N <REST-GET ,RS-VERSION>
          ";CYCLES=" N <REST-GET ,RS-CYCLES>
          ";LASTSIG=" N <REST-GET ,RS-LAST-SIGNATURE>
          ";DREAMED=" N <REST-GET ,RS-DREAMED>
          ";OVERNIGHT=" N <REST-GET ,RS-OVERNIGHT>
          ";FILED=" N <REST-GET ,RS-FILED>
          ";STRENGTH=" N <GETP ,WINNER ,P?STRENGTH>
          ";STAGGERED=">
    <COND (<FSET? ,WINNER ,STAGGERED> <TELL "Y">) (T <TELL "N">)>
    <TELL ";GARLIC=">
    <COND (,SHADOW-GARLIC-SCENT <TELL "Y">) (T <TELL "N">)>
    <TELL ";NOTE=">
    <REST-TEST-PRESENT ,REST-DREAM-NOTEBOOK>
    <TELL ";REPORT=">
    <REST-TEST-PRESENT ,REST-OVERNIGHT-REPORT>
    <TELL ";REPORT-CABINET=">
    <COND (<IN? ,REST-OVERNIGHT-REPORT ,ARCHIVE-CABINET> <TELL "Y">) (T <TELL "N">)>
    <TELL ";NOTICE=">
    <REST-TEST-PRESENT ,MAIL-COURIER-NOTICE>
    <CRLF>
    <SETG CLOCK-WAIT T>>

<ROUTINE V-REST-TEST-FOREST ()
    <AREA-PUT ,AREA-SLOT-FOREST ,AREA-FOREST-ONE>
    <GOTO ,BEDROOM>
    <SETG CLOCK-WAIT T>
    <TELL "REST-DISCOVERY:FOREST" CR>>

<ROUTINE V-REST-TEST-DAM ()
    <SETG DAM-MECH-PANEL-DIAGNOSED T>
    <GOTO ,BEDROOM>
    <SETG CLOCK-WAIT T>
    <TELL "REST-DISCOVERY:DAM" CR>>

<ROUTINE V-REST-TEST-ATTIC ()
    <GOTO ,ATTIC>
    <SETG CLOCK-WAIT T>
    <TELL "REST-TEST:ATTIC" CR>>

<ROUTINE V-REST-TEST-MUTATE ()
    <REST-TEST-REMOVE ,REST-DREAM-NOTEBOOK>
    <REST-TEST-REMOVE ,REST-OVERNIGHT-REPORT>
    <REST-TEST-REMOVE ,MAIL-COURIER-NOTICE>
    <REST-TEST-RESET>
    <REST-TEST-CLEAR-MAIL>
    <SETG HOUSE-EVENT-ENTERED <>>
    <SETG HOUSE-EVENT-RETURN <>>
    <AREA-PUT ,AREA-SLOT-FOREST 0>
    <SETG DAM-MECH-PANEL-DIAGNOSED <>>
    <PUTP ,WINNER ,P?STRENGTH -5>
    <FSET ,WINNER ,STAGGERED>
    <SETG SHADOW-GARLIC-SCENT T>
    <GOTO ,NORTH-OF-HOUSE>
    <SETG CLOCK-WAIT T>
    <TELL "REST:MUTATED" CR>
    <V-REST-TEST-REPORT>>
