"Test-only regional evidence setup, mutation, and reporting for Release 1226 qualification."

<SYNTAX APARTIAL = V-AREA-TEST-PARTIAL>
<SYNTAX ACOMPLETE = V-AREA-TEST-COMPLETE>
<SYNTAX AREPORT = V-AREA-TEST-REPORT>
<SYNTAX AMUTATE = V-AREA-TEST-MUTATE>

<ROUTINE AREA-TEST-REMOVE (OBJ)
    <COND (<LOC .OBJ> <REMOVE-CAREFULLY .OBJ>)>
    <RTRUE>>

<ROUTINE AREA-TEST-RESET ()
    <AREA-PUT ,AREA-SLOT-VERSION 1>
    <AREA-PUT ,AREA-SLOT-SEEN 0>
    <AREA-PUT ,AREA-SLOT-DAM 0>
    <AREA-PUT ,AREA-SLOT-HADES 0>
    <AREA-PUT ,AREA-SLOT-HOUSE 0>
    <AREA-PUT ,AREA-SLOT-FOREST 0>
    <AREA-PUT ,AREA-SLOT-UNDERGROUND 0>
    <AREA-PUT ,AREA-SLOT-COMPLETE 0>
    <AREA-PUT ,AREA-SLOT-FILED 0>
    <AREA-PUT ,AREA-SLOT-EVENT-MODEL <>>
    <AREA-PUT ,AREA-SLOT-EVENT-PARTIAL <>>
    <AREA-PUT ,AREA-SLOT-EVENT-SYNTHESIS <>>
    <AREA-PUT ,AREA-SLOT-EVENT-RESTORE <>>
    <AREA-PUT ,AREA-SLOT-EVENT-CROSS <>>
    <AREA-PUT ,AREA-SLOT-LAST 0>
    <RTRUE>>

<ROUTINE AREA-TEST-CLEAR-RECORDS ()
    <AREA-TEST-REMOVE ,AREA-DAM-CASE>
    <AREA-TEST-REMOVE ,AREA-HADES-CASE>
    <AREA-TEST-REMOVE ,AREA-HOUSE-CASE>
    <AREA-TEST-REMOVE ,AREA-FOREST-CASE>
    <AREA-TEST-REMOVE ,AREA-UNDERGROUND-CASE>
    <AREA-TEST-REMOVE ,AREA-SYNTHESIS-PRINTOUT>
    <RTRUE>>

<ROUTINE AREA-TEST-CLEAR-SOURCES ()
    <AREA-TEST-REMOVE ,ARCHIVE-THRESHOLD-FOLDER>
    <AREA-TEST-REMOVE ,ARCHIVE-DISPLAY-CARD>
    <AREA-TEST-REMOVE ,ARCHIVE-DAM-PRINTOUT>
    <AREA-TEST-REMOVE ,ARCHIVE-VISITOR-FICHE>
    <AREA-TEST-REMOVE ,ARCHIVE-CHRONOLOGY-CASSETTE>

    <AREA-TEST-REMOVE ,MAIL-CELLAR-NOTE>
    <AREA-TEST-REMOVE ,MAIL-MUSEUM-NOTE>
    <AREA-TEST-REMOVE ,MAIL-DAM-NOTE>
    <AREA-TEST-REMOVE ,MAIL-COURIER-NOTICE>
    <AREA-TEST-REMOVE ,MAIL-SURVEYOR-NOTICE>
    <AREA-TEST-REMOVE ,MAIL-RETURN-RECEIPT>
    <AREA-TEST-REMOVE ,MAIL-SURVEY-TAG>

    <MAIL-PUT ,MS-QUEUED 0>
    <MAIL-PUT ,MS-DELIVERED 0>
    <MAIL-PUT ,MS-READ 0>
    <MAIL-PUT ,MS-REPLIED 0>
    <MAIL-PUT ,MS-SENT 0>
    <MAIL-PUT ,MS-REPLY-TARGET 0>
    <MAIL-PUT ,MS-VISITOR-QUEUED 0>
    <MAIL-PUT ,MS-VISITOR-ACTIVE 0>
    <MAIL-PUT ,MS-VISITOR-MISSED 0>
    <MAIL-PUT ,MS-VISITOR-REFUSED 0>
    <MAIL-PUT ,MS-VISITOR-COMPLETE 0>
    <MAIL-PUT ,MS-EVENT-QUEUE <>>
    <MAIL-PUT ,MS-EVENT-PROVENANCE <>>
    <MAIL-PUT ,MS-EVENT-MAILBOX <>>
    <MAIL-PUT ,MS-EVENT-REPLY <>>
    <MAIL-PUT ,MS-EVENT-VISITOR <>>
    <MAIL-PUT ,MS-EVENT-MISSED <>>
    <MAIL-PUT ,MS-LAST-DELIVERY 0>
    <RTRUE>>

<ROUTINE V-AREA-TEST-PARTIAL ()
    <AREA-TEST-CLEAR-RECORDS>
    <AREA-TEST-RESET>
    <SETG DAM-MECH-PANEL-DIAGNOSED T>
    <FSET ,DAM-ROOM ,TOUCHBIT>
    <GOTO ,FOREST-1>
    <AREA-OBSERVE-WORLD>
    <MOVE ,LAMP ,WINNER>
    <FSET ,LAMP ,ONBIT>
    <GOTO ,ATTIC>
    <SETG CLOCK-WAIT T>
    <TELL "AREA-PARTIAL:READY" CR>>

<ROUTINE AREA-TEST-PRESENT (OBJ)
    <COND (<LOC .OBJ> <TELL "Y">) (T <TELL "N">)>>

<ROUTINE V-AREA-TEST-COMPLETE ()
    <AREA-TEST-CLEAR-RECORDS>
    <AREA-TEST-RESET>

    <FSET ,DAM-ROOM ,TOUCHBIT>
    <FSET ,MAINTENANCE-ROOM ,TOUCHBIT>
    <SETG DAM-MECH-PANEL-DIAGNOSED T>
    <SETG DAM-MECH-INTERLOCK-SEEN T>
    <SETG DAM-MECH-BOLT-ATTEMPTED T>
    <SETG DAM-MECH-GATES-CYCLED T>
    <SETG DAM-MECH-LEAK-TRIGGERED T>
    <SETG DAM-MECH-LEAK-REPAIRED T>
    <SETG DAM-MECH-TOOL-PROBED T>
    <SETG WATER-LEVEL -1>

    <FSET ,ENTRANCE-TO-HADES ,TOUCHBIT>
    <FSET ,NORTH-TEMPLE ,TOUCHBIT>
    <FSET ,SOUTH-TEMPLE ,TOUCHBIT>
    <FSET ,GHOSTS ,TOUCHBIT>
    <SETG RITUAL-CEREMONY-KNOWN T>
    <SETG RITUAL-BELL-RESONANCE-HEARD T>
    <SETG RITUAL-BELL-ANSWERED T>
    <SETG RITUAL-CANDLES-ANSWERED T>
    <SETG RITUAL-WRONG-ORDER-SEEN T>
    <SETG RITUAL-MIRROR-RESONANCE T>
    <SETG RITUAL-PRAYER-COMPLETED T>
    <SETG LLD-FLAG T>

    <SETG HOUSE-EVENT-ENTERED T>
    <SETG HOUSE-EVENT-ATTIC T>
    <SETG HOUSE-EVENT-CELLAR T>
    <SETG HOUSE-EVENT-RETURN T>
    <SETG HOUSE-EVENT-COLLECTION T>
    <SETG HOUSE-EVENT-DISTURBANCE T>

    <FSET ,FOREST-1 ,TOUCHBIT>
    <FSET ,FOREST-2 ,TOUCHBIT>
    <FSET ,FOREST-3 ,TOUCHBIT>
    <FSET ,CLEARING ,TOUCHBIT>
    <FSET ,SONGBIRD ,TOUCHBIT>

    <NPC-PUT ,NS-SEEN 7>
    <COND (<NOT <LOC ,ARCHIVE-DAM-PRINTOUT>>
           <MOVE ,ARCHIVE-DAM-PRINTOUT ,ARCHIVE-CABINET>)>
    <COND (<NOT <LOC ,ARCHIVE-THRESHOLD-FOLDER>>
           <MOVE ,ARCHIVE-THRESHOLD-FOLDER ,ARCHIVE-CABINET>)>
    <COND (<NOT <LOC ,ARCHIVE-DISPLAY-CARD>>
           <MOVE ,ARCHIVE-DISPLAY-CARD ,ARCHIVE-CABINET>)>
    <COND (<NOT <LOC ,ARCHIVE-CHRONOLOGY-CASSETTE>>
           <MOVE ,ARCHIVE-CHRONOLOGY-CASSETTE ,ARCHIVE-CABINET>)>

    <AREA-OBSERVE-WORLD>
    <GOTO ,ATTIC>
    <SETG CLOCK-WAIT T>
    <TELL "AREA-COMPLETE:READY" CR>>

<ROUTINE V-AREA-TEST-REPORT ()
    <TELL "AREA:VERSION=" N <AREA-GET ,AREA-SLOT-VERSION>
          ";SEEN=" N <AREA-GET ,AREA-SLOT-SEEN>
          ";DAM=" N <AREA-GET ,AREA-SLOT-DAM>
          ";HADES=" N <AREA-GET ,AREA-SLOT-HADES>
          ";HOUSE=" N <AREA-GET ,AREA-SLOT-HOUSE>
          ";FOREST=" N <AREA-GET ,AREA-SLOT-FOREST>
          ";UNDER=" N <AREA-GET ,AREA-SLOT-UNDERGROUND>
          ";COMPLETE=" N <AREA-GET ,AREA-SLOT-COMPLETE>
          ";FILED=" N <AREA-GET ,AREA-SLOT-FILED>
          ";DAMFILE=">
    <AREA-TEST-PRESENT ,AREA-DAM-CASE>
    <TELL ";HADESFILE="><AREA-TEST-PRESENT ,AREA-HADES-CASE>
    <TELL ";HOUSEFILE="><AREA-TEST-PRESENT ,AREA-HOUSE-CASE>
    <TELL ";FORESTFILE="><AREA-TEST-PRESENT ,AREA-FOREST-CASE>
    <TELL ";UNDERFILE="><AREA-TEST-PRESENT ,AREA-UNDERGROUND-CASE>
    <TELL ";SYNTH="><AREA-TEST-PRESENT ,AREA-SYNTHESIS-PRINTOUT>
    <TELL ";DAM-CABINET=">
    <COND (<IN? ,AREA-DAM-CASE ,ARCHIVE-CABINET> <TELL "Y">) (T <TELL "N">)>
    <CRLF>>

<ROUTINE V-AREA-TEST-MUTATE ()
    <AREA-TEST-CLEAR-RECORDS>
    <AREA-TEST-RESET>

    <SETG DAM-MECH-PANEL-DIAGNOSED <>>
    <SETG DAM-MECH-INTERLOCK-SEEN <>>
    <SETG DAM-MECH-BOLT-ATTEMPTED <>>
    <SETG DAM-MECH-GATES-CYCLED <>>
    <SETG DAM-MECH-LEAK-TRIGGERED <>>
    <SETG DAM-MECH-LEAK-REPAIRED <>>
    <SETG DAM-MECH-TOOL-PROBED <>>
    <SETG WATER-LEVEL 0>

    <SETG RITUAL-CEREMONY-KNOWN <>>
    <SETG RITUAL-BELL-RESONANCE-HEARD <>>
    <SETG RITUAL-BELL-ANSWERED <>>
    <SETG RITUAL-CANDLES-ANSWERED <>>
    <SETG RITUAL-WRONG-ORDER-SEEN <>>
    <SETG RITUAL-MIRROR-RESONANCE <>>
    <SETG RITUAL-PRAYER-COMPLETED <>>
    <SETG LLD-FLAG <>>

    <SETG HOUSE-EVENT-ENTERED <>>
    <SETG HOUSE-EVENT-ATTIC <>>
    <SETG HOUSE-EVENT-CELLAR <>>
    <SETG HOUSE-EVENT-RETURN <>>
    <SETG HOUSE-EVENT-COLLECTION <>>
    <SETG HOUSE-EVENT-DISTURBANCE <>>

    <FCLEAR ,DAM-ROOM ,TOUCHBIT>
    <FCLEAR ,MAINTENANCE-ROOM ,TOUCHBIT>
    <FCLEAR ,ENTRANCE-TO-HADES ,TOUCHBIT>
    <FCLEAR ,NORTH-TEMPLE ,TOUCHBIT>
    <FCLEAR ,SOUTH-TEMPLE ,TOUCHBIT>
    <FCLEAR ,GHOSTS ,TOUCHBIT>
    <FCLEAR ,FOREST-1 ,TOUCHBIT>
    <FCLEAR ,FOREST-2 ,TOUCHBIT>
    <FCLEAR ,FOREST-3 ,TOUCHBIT>
    <FCLEAR ,CLEARING ,TOUCHBIT>
    <FCLEAR ,SONGBIRD ,TOUCHBIT>

    <NPC-PUT ,NS-SEEN 0>
    <AREA-TEST-CLEAR-SOURCES>
    <GOTO ,NORTH-OF-HOUSE>
    <SETG CLOCK-WAIT T>
    <TELL "AREA:MUTATED" CR>>
