"TEST-ONLY MUSEUM ECOLOGY PRECONDITIONS"

<SYNTAX ANGLER = V-MUSEUM-FISH-TEST-RIVER>
<SYNTAX TIDEUP = V-MUSEUM-FISH-TEST-TIDE>
<SYNTAX GOHOME = V-MUSEUM-FISH-TEST-HOME>

<ROUTINE V-MUSEUM-FISH-TEST-RIVER ()
    <SETG LOW-TIDE <>>
    <REMOVE ,DAM-SILVERFIN>
    <AQUATIC-PUT ,AQUATIC-SLOT-OBSERVED 0>
    <AQUATIC-PUT ,AQUATIC-SLOT-RELEASED 0>
    <MOVE ,MUSEUM-FISHING-ROD ,WINNER>
    <MOVE ,MUSEUM-FIELD-JAR ,WINNER>
    <GOTO ,DAM-BASE>
    <TELL "TEST PRECONDITION: ordinary River Frigid fishing site; museum rod and field jar carried." CR>
    <RTRUE>>

<ROUTINE V-MUSEUM-FISH-TEST-TIDE ()
    <SETG LOW-TIDE T>
    <MOVE ,MUSEUM-FISHING-ROD ,WINNER>
    <MOVE ,MUSEUM-FIELD-JAR ,WINNER>
    <GOTO ,DAM-BASE>
    <TELL "TEST PRECONDITION: reservoir at low tide; spillway fishing site ready." CR>
    <RTRUE>>

<ROUTINE V-MUSEUM-FISH-TEST-HOME ()
    <GOTO ,LIVING-ROOM>
    <TELL "TEST PRECONDITION: returned physically to the Living Room museum." CR>
    <RTRUE>>
