"TEST-ONLY LEAFLET-SPINE PRECONDITIONS"

<SYNTAX LSPDAM = V-LSP-TEST-DAM>
<SYNTAX LSPCYCLOPS = V-LSP-TEST-CYCLOPS>
<SYNTAX LSPRAINBOW = V-LSP-TEST-RAINBOW>
<SYNTAX LSPHADES = V-LSP-TEST-HADES>
<SYNTAX LSPTIMBER = V-LSP-TEST-TIMBER>
<SYNTAX LSPTHIEF = V-LSP-TEST-THIEF>

<ROUTINE LSP-LIGHT ()
	<MOVE ,LAMP ,WINNER>
	<FSET ,LAMP ,ONBIT>
	<RTRUE>>

<ROUTINE V-LSP-TEST-DAM ()
	<LSP-LIGHT>
	<GOTO ,DAM-ROOM>
	<TELL "TEST PRECONDITION: Flood Control Dam #3 crown." CR>
	<RTRUE>>

<ROUTINE V-LSP-TEST-CYCLOPS ()
	<LSP-LIGHT>
	<GOTO ,CYCLOPS-ROOM>
	<TELL "TEST PRECONDITION: cyclops room with the hungry actor." CR>
	<RTRUE>>

<ROUTINE V-LSP-TEST-RAINBOW ()
	<LSP-LIGHT>
	<SETG RAINBOW-FLAG T>
	<GOTO ,ARAGAIN-FALLS>
	<TELL "TEST PRECONDITION: Aragain Falls with the rainbow already walkable." CR>
	<RTRUE>>

<ROUTINE V-LSP-TEST-HADES ()
	<LSP-LIGHT>
	<GOTO ,ENTRANCE-TO-HADES>
	<TELL "TEST PRECONDITION: Entrance to Hades." CR>
	<RTRUE>>

<ROUTINE V-LSP-TEST-TIMBER ()
	<LSP-LIGHT>
	<GOTO ,TIMBER-ROOM>
	<TELL "TEST PRECONDITION: Timber Room." CR>
	<RTRUE>>

<ROUTINE V-LSP-TEST-THIEF ()
	<LSP-LIGHT>
	<GOTO ,TREASURE-ROOM>
	<TELL "TEST PRECONDITION: thief's treasure room." CR>
	<RTRUE>>
