"TEST-ONLY RELEASE 1271 CREATURE SYSTEMIC PRECONDITIONS"

<SYNTAX CREATETROLL = V-CREATURE-TROLL-TEST>
<SYNTAX CREATECYCLOPS = V-CREATURE-CYCLOPS-TEST>
<SYNTAX CREATEGRUE = V-CREATURE-GRUE-BRIGHT-TEST>
<SYNTAX CREATEGRUEWEAK = V-CREATURE-GRUE-WEAK-TEST>
<SYNTAX CREATETHIEF = V-CREATURE-THIEF-TEST>
<SYNTAX CREATEDRAGON = V-CREATURE-DRAGON-TEST>

<ROUTINE V-CREATURE-TROLL-TEST ()
    <SETG ALWAYS-LIT T>
    <SETG TROLL-FLAG <>>
    <SETG GLULX-ALT-TROLL-BOUND <>>
    <SETG GLULX-ALT-TROLL-DISTRACTED <>>
    <SETG GLULX-ALT-TROLL-TRICK-USED <>>
    <MOVE ,TROLL ,TROLL-ROOM>
    <FSET ,TROLL ,FIGHTBIT>
    <GOTO ,TROLL-ROOM>
    <TELL "TEST PRECONDITION: alert living troll blocks both passages with deception unused." CR>
    <RTRUE>>

<ROUTINE V-CREATURE-CYCLOPS-TEST ()
    <SETG ALWAYS-LIT T>
    <SETG CYCLOPS-FLAG <>>
    <SETG CYCLOWRATH 0>
    <DISABLE <INT I-CYCLOPS>>
    <COND (<IN? ,LUNCH ,WINNER> <REMOVE-CAREFULLY ,LUNCH>)>
    <MOVE ,LUNCH ,WINNER>
    <MOVE ,CYCLOPS ,CYCLOPS-ROOM>
    <FSET ,CYCLOPS ,FIGHTBIT>
    <GOTO ,CYCLOPS-ROOM>
    <TELL "TEST PRECONDITION: hungry awake cyclops guards the stair; hot-pepper lunch is held." CR>
    <RTRUE>>

<ROUTINE CREATURE-TEST-GRUE-COMMON ()
    <SETG ALWAYS-LIT T>
    <CONSUMABLE-LIGHT-RESET>
    <COND (<IN? ,TORCH ,WINNER> <REMOVE-CAREFULLY ,TORCH>)>
    <COND (<IN? ,LAMP ,WINNER> <REMOVE-CAREFULLY ,LAMP>)>
    <MOVE ,GRUE-SURVEY-TUBE ,DEAD-END-5>
    <FSET ,GRUE-SURVEY-TUBE ,INVISIBLE>
    <PUTP ,GRUE-FISSURES ,P?VALUE 0>
    <RTRUE>>

<ROUTINE V-CREATURE-GRUE-BRIGHT-TEST ()
    <CREATURE-TEST-GRUE-COMMON>
    <MOVE ,TORCH ,WINNER>
    <FSET ,TORCH ,ONBIT>
    <GOTO ,DEAD-END-5>
    <TELL "TEST PRECONDITION: bright ivory torch is held at the unrevealed grue fissures." CR>
    <RTRUE>>

<ROUTINE V-CREATURE-GRUE-WEAK-TEST ()
    <CREATURE-TEST-GRUE-COMMON>
    <MOVE ,LAMP ,WINNER>
    <FSET ,LAMP ,ONBIT>
    <CONSUMABLE-LIGHT-PUT ,CL-LAMP-STAGE ,LIGHT-WEAK>
    <PUTP ,GRUE-FISSURES ,P?VALUE 1>
    <FCLEAR ,GRUE-SURVEY-TUBE ,INVISIBLE>
    <GOTO ,DEAD-END-5>
    <TELL "TEST PRECONDITION: survey tube is known and visible, but only weak light reaches the colony." CR>
    <RTRUE>>

<ROUTINE V-CREATURE-THIEF-TEST ()
    <SETG ALWAYS-LIT T>
    <SETG THIEF-ENGROSSED <>>
    <PUTP ,THIEF ,P?VALUE 1>
    <FCLEAR ,THIEF ,INVISIBLE>
    <MOVE ,THIEF ,ROUND-ROOM>
    <COND (<IN? ,CHALICE ,WINNER> <REMOVE-CAREFULLY ,CHALICE>)>
    <MOVE ,CHALICE ,WINNER>
    <GOTO ,ROUND-ROOM>
    <TELL "TEST PRECONDITION: visible thief has a personal grudge; valuable chalice is held." CR>
    <RTRUE>>

<ROUTINE V-CREATURE-DRAGON-TEST ()
    <SETG ALWAYS-LIT T>
    <STRUCTURAL-DIFFICULTY-RESET>
    <DRAGON-RESET>
    <STRUCTURAL-DIFFICULTY-SET ,SD-CLASSIC>
    <COND (<IN? ,CHALICE ,WINNER> <REMOVE-CAREFULLY ,CHALICE>)>
    <MOVE ,CHALICE ,WINNER>
    <GOTO ,DRAGON-GALLERY>
    <TELL "TEST PRECONDITION: canonical Classic dragon bargain situation ready." CR>
    <RTRUE>>
