"Test-only correspondence positioning, mutation, and reporting verbs for Release 1223 qualification."

<SYNTAX MSETUP = V-MAIL-TEST-SETUP>
<SYNTAX MREPORT = V-MAIL-TEST-REPORT>
<SYNTAX MMUTATE = V-MAIL-TEST-MUTATE>

<ROUTINE MAIL-TEST-REMOVE (OBJ)
    <COND (<LOC .OBJ> <REMOVE-CAREFULLY .OBJ>)>
    <RTRUE>>

<ROUTINE MAIL-TEST-RESET-STATE ()
    <MAIL-PUT ,MS-VERSION 1>
    <MAIL-PUT ,MS-QUEUED 0>
    <MAIL-PUT ,MS-DELIVERED 0>
    <MAIL-PUT ,MS-READ 0>
    <MAIL-PUT ,MS-REPLIED 0>
    <MAIL-PUT ,MS-SENT 0>
    <MAIL-PUT ,MS-REPLY-TARGET 0>
    <MAIL-PUT ,MS-VISITOR-QUEUED 0>
    <MAIL-PUT ,MS-VISITOR-ACTIVE 0>
    <MAIL-PUT ,MS-VISITOR-MISSED 0>
    <MAIL-PUT ,MS-VISITOR-REFUSED 0>
    <MAIL-PUT ,MS-VISITOR-COMPLETE 0>
    <MAIL-PUT ,MS-EVENT-QUEUE <>>
    <MAIL-PUT ,MS-EVENT-PROVENANCE <>>
    <MAIL-PUT ,MS-EVENT-MAILBOX <>>
    <MAIL-PUT ,MS-EVENT-REPLY <>>
    <MAIL-PUT ,MS-EVENT-VISITOR <>>
    <MAIL-PUT ,MS-EVENT-MISSED <>>
    <MAIL-PUT ,MS-LAST-DELIVERY 0>
    <RTRUE>>

<ROUTINE V-MAIL-TEST-SETUP ()
    <QUEUE I-THIEF 0>
    <SETG THIEF-HERE <>>
    <REMOVE-CAREFULLY ,THIEF>
    <MAIL-TEST-REMOVE ,MAIL-CELLAR-NOTE>
    <MAIL-TEST-REMOVE ,MAIL-MUSEUM-NOTE>
    <MAIL-TEST-REMOVE ,MAIL-DAM-NOTE>
    <MAIL-TEST-REMOVE ,MAIL-REPLY-CARD>
    <MAIL-TEST-REMOVE ,MAIL-COURIER-NOTICE>
    <MAIL-TEST-REMOVE ,MAIL-SURVEYOR-NOTICE>
    <MAIL-TEST-REMOVE ,MAIL-RETURN-RECEIPT>
    <MAIL-TEST-REMOVE ,MAIL-SURVEY-TAG>
    <MAIL-TEST-REMOVE ,MAIL-COURIER>
    <MAIL-TEST-REMOVE ,MAIL-SURVEYOR>
    <MAIL-TEST-RESET-STATE>
    <MOVE ,ADVERTISEMENT ,MAILBOX>
    <FSET ,MAILBOX ,OPENBIT>
    <CELLAR-PUT ,CS-EVENT-INTRUSION T>
    <SETG MUSEUM-THEFT-OCCURRED T>
    <SETG WATER-LEVEL -1>
    <GOTO ,WEST-OF-HOUSE>
    <MAIL-DERIVE-QUEUE>
    <MAIL-DELIVER-NEXT>
    <SETG CLOCK-WAIT T>
    <TELL "MAIL-SETUP:READY" CR>>

<ROUTINE MAIL-TEST-PRINT-BOOL (VALUE)
    <COND (.VALUE <TELL "Y">) (T <TELL "N">)>>

<ROUTINE V-MAIL-TEST-REPORT ()
    <TELL "MAIL:VERSION=" N <MAIL-GET ,MS-VERSION>
          ";QUEUED=" N <MAIL-GET ,MS-QUEUED>
          ";DELIVERED=" N <MAIL-GET ,MS-DELIVERED>
          ";READ=" N <MAIL-GET ,MS-READ>
          ";REPLIED=" N <MAIL-GET ,MS-REPLIED>
          ";SENT=" N <MAIL-GET ,MS-SENT>
          ";VISITOR-QUEUED=" N <MAIL-GET ,MS-VISITOR-QUEUED>
          ";VISITOR-ACTIVE=" N <MAIL-GET ,MS-VISITOR-ACTIVE>
          ";MISSED=" N <MAIL-GET ,MS-VISITOR-MISSED>
          ";REFUSED=" N <MAIL-GET ,MS-VISITOR-REFUSED>
          ";COMPLETE=" N <MAIL-GET ,MS-VISITOR-COMPLETE>
          ";LEAFLET-MAILBOX=">
    <MAIL-TEST-PRINT-BOOL <IN? ,ADVERTISEMENT ,MAILBOX>>
    <TELL ";CELLAR-EXISTS=">
    <MAIL-TEST-PRINT-BOOL <LOC ,MAIL-CELLAR-NOTE>>
    <TELL ";MUSEUM-EXISTS=">
    <MAIL-TEST-PRINT-BOOL <LOC ,MAIL-MUSEUM-NOTE>>
    <TELL ";DAM-EXISTS=">
    <MAIL-TEST-PRINT-BOOL <LOC ,MAIL-DAM-NOTE>>
    <TELL ";REPLY-EXISTS=">
    <MAIL-TEST-PRINT-BOOL <LOC ,MAIL-REPLY-CARD>>
    <TELL ";COURIER-NOTICE=">
    <MAIL-TEST-PRINT-BOOL <LOC ,MAIL-COURIER-NOTICE>>
    <TELL ";SURVEYOR-NOTICE=">
    <MAIL-TEST-PRINT-BOOL <LOC ,MAIL-SURVEYOR-NOTICE>>
    <TELL ";RECEIPT=">
    <MAIL-TEST-PRINT-BOOL <LOC ,MAIL-RETURN-RECEIPT>>
    <TELL ";SURVEY-TAG=">
    <MAIL-TEST-PRINT-BOOL <LOC ,MAIL-SURVEY-TAG>>
    <CRLF>>

<ROUTINE V-MAIL-TEST-MUTATE ()
    <MAIL-TEST-REMOVE ,MAIL-CELLAR-NOTE>
    <MAIL-TEST-REMOVE ,MAIL-MUSEUM-NOTE>
    <MAIL-TEST-REMOVE ,MAIL-DAM-NOTE>
    <MAIL-TEST-REMOVE ,MAIL-REPLY-CARD>
    <MAIL-TEST-REMOVE ,MAIL-COURIER-NOTICE>
    <MAIL-TEST-REMOVE ,MAIL-SURVEYOR-NOTICE>
    <MAIL-TEST-REMOVE ,MAIL-RETURN-RECEIPT>
    <MAIL-TEST-REMOVE ,MAIL-SURVEY-TAG>
    <MAIL-TEST-REMOVE ,MAIL-COURIER>
    <MAIL-TEST-REMOVE ,MAIL-SURVEYOR>
    <CELLAR-PUT ,CS-EVENT-INTRUSION <>>
    <SETG MUSEUM-THEFT-OCCURRED <>>
    <SETG WATER-LEVEL 0>
    <MAIL-TEST-RESET-STATE>
    <MOVE ,ADVERTISEMENT ,MAILBOX>
    <GOTO ,NORTH-OF-HOUSE>
    <SETG CLOCK-WAIT T>
    <TELL "MAIL:MUTATED" CR>>
