"TEST-ONLY MUSEUM TROLL PRECONDITIONS"

<SYNTAX TROLLSUBDUE = V-MUSEUM-TROLL-TEST-SUBDUE>
<SYNTAX TROLLKILL = V-MUSEUM-TROLL-TEST-KILL>
<SYNTAX MUSEUMHOME = V-MUSEUM-TROLL-TEST-HOME>

<ROUTINE MUSEUM-TROLL-TEST-RESET ()
    <REMOVE ,TROLL-FUR>
    <PUT ,TROLL-TRACE-STATE 0 ,TROLL-OUTCOME-NONE>
    <MOVE ,TROLL ,TROLL-ROOM>
    <MOVE ,AXE ,TROLL>
    <FSET ,AXE ,NDESCBIT>
    <FSET ,AXE ,WEAPONBIT>
    <FCLEAR ,TROLL ,FIGHTBIT>
    <SETG TROLL-FLAG <>>
    <MOVE ,LAMP ,WINNER>
    <FSET ,LAMP ,ONBIT>
    <GOTO ,TROLL-ROOM>
    <RFALSE>>

<ROUTINE V-MUSEUM-TROLL-TEST-SUBDUE ()
    <MUSEUM-TROLL-TEST-RESET>
    <TROLL-FCN ,F-UNCONSCIOUS>
    <TELL "TEST PRECONDITION: the canonical troll was rendered unconscious in the Troll Room." CR>
    <RTRUE>>

<ROUTINE V-MUSEUM-TROLL-TEST-KILL ()
    <MUSEUM-TROLL-TEST-RESET>
    <REMOVE ,TROLL>
    <TROLL-FCN ,F-DEAD>
    <TELL "TEST PRECONDITION: the canonical troll was killed in the Troll Room." CR>
    <RTRUE>>

<ROUTINE V-MUSEUM-TROLL-TEST-HOME ()
    <GOTO ,LIVING-ROOM>
    <TELL "TEST PRECONDITION: returned physically to the Living Room museum." CR>
    <RTRUE>>
