"LIVING COLLECTION SYNTAX — must load before mara_companion so V?PREPARE exists"

<SYNTAX TAKE OBJECT TO OBJECT = V-LC-TAKE-TO>
<SYNTAX ASK OBJECT (FIND ACTORBIT) TO OBJECT = V-LC-ASK-TO>
<SYNTAX FILE = V-LC-MARA-FILE>
<SYNTAX PREPARE = V-LC-MARA-PREPARE>
<SYNTAX REST = V-LC-MARA-REST>
<SYNTAX SLEEP = V-LC-MARA-REST>
