"LIVING COLLECTION SYNTAX — must load before mara_companion so V?COOK exists"

<SYNTAX TAKE OBJECT TO OBJECT = V-LC-TAKE-TO>
<SYNTAX ASK OBJECT (FIND ACTORBIT) TO OBJECT = V-LC-ASK-TO>
;"FILE/PREPARE/REST/SLEEP are prepositions or collide; player-facing ASK MARA TO
  PREPARE still uses ASK OBJECT TO OBJECT. Mara-as-winner uses COOK/NAP/ARCHIVE."
<SYNTAX COOK = V-LC-MARA-PREPARE>
<SYNTAX NAP = V-LC-MARA-REST>
<SYNTAX ARCHIVE = V-LC-MARA-FILE>
