"TEST-ONLY RELEASE 1272 ASHGLASS SCENARIO PRECONDITIONS"

<SYNTAX ASHFOREST = V-ASH-FOREST-TEST>
<SYNTAX ASHCANYON = V-ASH-CANYON-TEST>
<SYNTAX ASHFOCUS = V-ASH-FOCUS-TEST>
<SYNTAX ASHVENT = V-ASH-VENT-TEST>
<SYNTAX ASHCANDLES = V-ASH-CANDLES-TEST>
<SYNTAX ASHROOK = V-ASH-ROOK-TEST>
<SYNTAX ASHSHAFT = V-ASH-SHAFT-TEST>
<SYNTAX ASHBRAKE = V-ASH-BRAKE-TEST>
<SYNTAX ASHHEAVY = V-ASH-HEAVY-TEST>
<SYNTAX ASHDEATH = V-ASH-DEATH-TEST>

<ROUTINE ASH-TEST-RESET ()
    <SETG ALWAYS-LIT T>
    <ASHGLASS-PUT ,AR-FOREST-OPEN 0>
    <ASHGLASS-PUT ,AR-CANYON-OPEN 0>
    <ASHGLASS-PUT ,AR-FOCUS-KNOWN 0>
    <ASHGLASS-PUT ,AR-LENS-ALIGNED 0>
    <ASHGLASS-PUT ,AR-VENT-READ 0>
    <ASHGLASS-PUT ,AR-VENT-OPEN 0>
    <ASHGLASS-PUT ,AR-ROOK-AWAY 0>
    <ASHGLASS-PUT ,AR-BRAKE-SET 0>
    <ASHGLASS-PUT ,AR-VAULT-OPEN 0>
    <ASHGLASS-PUT ,AR-GLASS-WARNED 0>
    <DISABLE <INT I-ASHGLASS-ROOK-RETURN>>
    <RTRUE>>

<ROUTINE V-ASH-FOREST-TEST ()
    <ASH-TEST-RESET>
    <COND (<IN? ,AXE ,WINNER> <REMOVE-CAREFULLY ,AXE>)>
    <MOVE ,AXE ,WINNER>
    <GOTO ,FOREST-3>
    <TELL "TEST PRECONDITION: Forest-3 stormfall closed; canonical axe held." CR>
    <RTRUE>>

<ROUTINE V-ASH-CANYON-TEST ()
    <ASH-TEST-RESET>
    <GOTO ,CANYON-VIEW>
    <TELL "TEST PRECONDITION: Canyon View milestone unworked; no Ashglass route state set." CR>
    <RTRUE>>

<ROUTINE V-ASH-FOCUS-TEST ()
    <ASH-TEST-RESET>
    <GOTO ,ASHGLASS-SCRIPTORIUM>
    <TELL "TEST PRECONDITION: archive slate unread; focus operation unknown." CR>
    <RTRUE>>

<ROUTINE V-ASH-VENT-TEST ()
    <ASH-TEST-RESET>
    <CLUE-KNOWLEDGE-PUT ,CK-AIR-PASSAGE-MOTIF 1>
    <GOTO ,ASHGLASS-BROKEN-GALLERY>
    <TELL "TEST PRECONDITION: known old air-passage motif; Ashglass service panel still shut." CR>
    <RTRUE>>

<ROUTINE V-ASH-CANDLES-TEST ()
    <ASH-TEST-RESET>
    <LEARNED-MAGIC-PUT ,LM-STILLING-KNOWN 1>
    <COND (<IN? ,CANDLES ,WINNER> <REMOVE-CAREFULLY ,CANDLES>)>
    <MOVE ,CANDLES ,WINNER>
    <FCLEAR ,CANDLES ,RMUNGBIT>
    <FSET ,CANDLES ,ONBIT>
    <CONSUMABLE-LIGHT-PUT ,CL-CANDLE-WET 0>
    <GOTO ,ASHGLASS-LOW-CISTERN>
    <TELL "TEST PRECONDITION: lit dry ritual candles held; stilling ward genuinely known." CR>
    <RTRUE>>

<ROUTINE V-ASH-ROOK-TEST ()
    <ASH-TEST-RESET>
    <COND (<IN? ,GRUE-SURVEY-TUBE ,WINNER> <REMOVE-CAREFULLY ,GRUE-SURVEY-TUBE>)>
    <MOVE ,GRUE-SURVEY-TUBE ,WINNER>
    <FCLEAR ,GRUE-SURVEY-TUBE ,INVISIBLE>
    <MOVE ,ASHGLASS-ROOK ,ASHGLASS-ROOKERY>
    <GOTO ,ASHGLASS-ROOKERY>
    <TELL "TEST PRECONDITION: rook controls east stair; recovered brass survey tube held." CR>
    <RTRUE>>

<ROUTINE V-ASH-SHAFT-TEST ()
    <ASH-TEST-RESET>
    <CONSUMABLE-LIGHT-RESET>
    <COND (<IN? ,TORCH ,WINNER> <REMOVE-CAREFULLY ,TORCH>)>
    <MOVE ,TORCH ,WINNER>
    <FSET ,TORCH ,ONBIT>
    <GOTO ,ASHGLASS-LOWER-SHAFT>
    <TELL "TEST PRECONDITION: bright ivory torch held at damaged lower shaft." CR>
    <RTRUE>>

<ROUTINE V-ASH-BRAKE-TEST ()
    <ASH-TEST-RESET>
    <GOTO ,ASHGLASS-COUNTERWEIGHT-ROOM>
    <TELL "TEST PRECONDITION: counterweight unarrested; brake and chain untouched." CR>
    <RTRUE>>

<ROUTINE V-ASH-HEAVY-TEST ()
    <ASH-TEST-RESET>
    <COND (<IN? ,COFFIN ,WINNER> <REMOVE-CAREFULLY ,COFFIN>)>
    <MOVE ,COFFIN ,WINNER>
    <GOTO ,ASHGLASS-GLASS-FLOOR>
    <TELL "TEST PRECONDITION: deliberately excessive carried load placed on ashglass bridge approach." CR>
    <RTRUE>>

<ROUTINE V-ASH-DEATH-TEST ()
    <ASH-TEST-RESET>
    <GOTO ,ASHGLASS-COUNTERWEIGHT-ROOM>
    <TELL "TEST PRECONDITION: unarrested counterweight ready for unsafe chain release." CR>
    <RTRUE>>
