"Test-only positioning, mutation, migration, and reporting verbs for Release 1219 qualification."

<SYNTAX HSLIVING = V-HOUSE-STATE-TEST-LIVING>
<SYNTAX HSKITCHEN = V-HOUSE-STATE-TEST-KITCHEN>
<SYNTAX HSATTIC = V-HOUSE-STATE-TEST-ATTIC>
<SYNTAX HSCELLAR = V-HOUSE-STATE-TEST-CELLAR>
<SYNTAX HSRETURN = V-HOUSE-STATE-TEST-RETURN>
<SYNTAX HSCOLLECT = V-HOUSE-STATE-TEST-COLLECT>
<SYNTAX HSREPORT = V-HOUSE-STATE-TEST-REPORT>
<SYNTAX HSMUTATE = V-HOUSE-STATE-TEST-MUTATE>
<SYNTAX HSMIGRATE = V-HOUSE-STATE-TEST-MIGRATE>

<ROUTINE HOUSE-STATE-TEST-QUIET-WORLD ()
    <QUEUE I-THIEF 0>
    <SETG THIEF-HERE <>>
    <REMOVE-CAREFULLY ,THIEF>
    <REMOVE-CAREFULLY ,TROLL>
    <SETG TROLL-FLAG T>
    <MOVE ,LAMP ,WINNER>
    <FSET ,LAMP ,ONBIT>
    <RTRUE>>

<ROUTINE HOUSE-STATE-TEST-GO (ROOM MARKER)
    <HOUSE-STATE-TEST-QUIET-WORLD>
    <GOTO .ROOM>
    <HOUSE-STATE-TEST-QUIET-WORLD>
    <SETG CLOCK-WAIT T>
    <TELL .MARKER CR>>

<ROUTINE V-HOUSE-STATE-TEST-LIVING ()
    <HOUSE-STATE-TEST-GO ,LIVING-ROOM "HOUSE-STATE-SETUP:LIVING">>

<ROUTINE V-HOUSE-STATE-TEST-KITCHEN ()
    <HOUSE-STATE-TEST-GO ,KITCHEN "HOUSE-STATE-SETUP:KITCHEN">>

<ROUTINE V-HOUSE-STATE-TEST-ATTIC ()
    <HOUSE-STATE-TEST-GO ,ATTIC "HOUSE-STATE-SETUP:ATTIC">>

<ROUTINE V-HOUSE-STATE-TEST-CELLAR ()
    <HOUSE-STATE-TEST-GO ,CELLAR "HOUSE-STATE-SETUP:CELLAR">>

<ROUTINE V-HOUSE-STATE-TEST-RETURN ()
    <HOUSE-STATE-TEST-GO ,LIVING-ROOM "HOUSE-STATE-SETUP:RETURN">>

<ROUTINE V-HOUSE-STATE-TEST-COLLECT ()
    <HOUSE-STATE-TEST-GO ,LIVING-ROOM "HOUSE-STATE-SETUP:COLLECTION">
    <MOVE ,PAINTING ,WINNER>
    <FCLEAR ,PAINTING ,TOUCHBIT>
    <THIS-IS-IT ,PAINTING>
    <SETG CLOCK-WAIT T>>

<ROUTINE HOUSE-STATE-TEST-PRINT-BOOL (VALUE)
    <COND (.VALUE <TELL "Y">) (T <TELL "N">)>>

<ROUTINE V-HOUSE-STATE-TEST-REPORT ()
    <TELL "HOUSE-STATE:VERSION=" N ,HOUSE-STATE-VERSION
          ";CONDITION=" N ,HOUSE-STATE-CONDITION
          ";COLLECTION=" N ,HOUSE-STATE-COLLECTION
          ";KNOWLEDGE=" N ,HOUSE-STATE-KNOWLEDGE
          ";SECURITY=" N ,HOUSE-STATE-SECURITY
          ";ATMOSPHERE=" N ,HOUSE-STATE-ATMOSPHERE
          ";ENTERED=">
    <HOUSE-STATE-TEST-PRINT-BOOL ,HOUSE-EVENT-ENTERED>
    <TELL ";ATTIC=">
    <HOUSE-STATE-TEST-PRINT-BOOL ,HOUSE-EVENT-ATTIC>
    <TELL ";CELLAR=">
    <HOUSE-STATE-TEST-PRINT-BOOL ,HOUSE-EVENT-CELLAR>
    <TELL ";RETURN=">
    <HOUSE-STATE-TEST-PRINT-BOOL ,HOUSE-EVENT-RETURN>
    <TELL ";COLLECTED=">
    <HOUSE-STATE-TEST-PRINT-BOOL ,HOUSE-EVENT-COLLECTION>
    <TELL ";DISTURBED=">
    <HOUSE-STATE-TEST-PRINT-BOOL ,HOUSE-EVENT-DISTURBANCE>
    <CRLF>>

<ROUTINE HOUSE-STATE-TEST-CLEAR ()
    <SETG HOUSE-STATE-VERSION 1>
    <SETG HOUSE-STATE-CONDITION 0>
    <SETG HOUSE-STATE-COLLECTION 0>
    <SETG HOUSE-STATE-KNOWLEDGE 0>
    <SETG HOUSE-STATE-SECURITY 0>
    <SETG HOUSE-STATE-ATMOSPHERE 0>
    <SETG HOUSE-EVENT-ENTERED <>>
    <SETG HOUSE-EVENT-ATTIC <>>
    <SETG HOUSE-EVENT-CELLAR <>>
    <SETG HOUSE-EVENT-RETURN <>>
    <SETG HOUSE-EVENT-COLLECTION <>>
    <SETG HOUSE-EVENT-DISTURBANCE <>>
    <RTRUE>>

<ROUTINE V-HOUSE-STATE-TEST-MUTATE ()
    <HOUSE-STATE-TEST-CLEAR>
    <MOVE ,PAINTING ,GALLERY>
    <SETG RUG-MOVED <>>
    <FCLEAR ,TRAP-DOOR ,OPENBIT>
    <FCLEAR ,TRAP-DOOR ,TOUCHBIT>
    <FSET ,TRAP-DOOR ,INVISIBLE>
    <FCLEAR ,KITCHEN-WINDOW ,OPENBIT>
    <SETG CLOCK-WAIT T>
    <TELL "HOUSE-STATE:MUTATED" CR>>

<ROUTINE V-HOUSE-STATE-TEST-MIGRATE ()
    <HOUSE-STATE-TEST-CLEAR>
    <SETG HOUSE-STATE-VERSION 0>
    <FSET ,KITCHEN ,TOUCHBIT>
    <FSET ,LIVING-ROOM ,TOUCHBIT>
    <FSET ,ATTIC ,TOUCHBIT>
    <FSET ,CELLAR ,TOUCHBIT>
    <HOUSE-STATE-REFRESH>
    <SETG CLOCK-WAIT T>
    <TELL "HOUSE-STATE:MIGRATED" CR>
    <V-HOUSE-STATE-TEST-REPORT>>
