"TEST-ONLY RELEASE 1265 CONSUMABLE-LIGHT PRECONDITIONS"

<SYNTAX CLBRIGHT = V-CONSUMABLE-BRIGHT-TEST>
<SYNTAX CLWEAK = V-CONSUMABLE-WEAK-TEST>
<SYNTAX CLEMBER = V-CONSUMABLE-EMBER-TEST>
<SYNTAX CLWET = V-CONSUMABLE-WET-TEST>
<SYNTAX CLSMOKE = V-CONSUMABLE-SMOKE-TEST>
<SYNTAX CLTORCH = V-CONSUMABLE-TORCH-TEST>
<SYNTAX CLSTAT = V-CONSUMABLE-STATUS-TEST>

<ROUTINE CONSUMABLE-TEST-COLONY-BASE ()
    <PUTP ,GRUE-FISSURES ,P?VALUE 0>
    <REMOVE-CAREFULLY ,MATCH>
    <DISABLE <INT I-CANDLES>>
    <REMOVE-CAREFULLY ,CANDLES>
    <REMOVE-CAREFULLY ,TORCH>
    <MOVE ,LAMP ,WINNER>
    <FCLEAR ,LAMP ,RMUNGBIT>
    <FCLEAR ,LAMP ,ONBIT>
    <GOTO ,DEAD-END-5>
    <PUTP ,GRUE-FISSURES ,P?VALUE 0>
    <RTRUE>>

<ROUTINE V-CONSUMABLE-BRIGHT-TEST ()
    <CONSUMABLE-LIGHT-RESET>
    <CONSUMABLE-TEST-COLONY-BASE>
    <FSET ,LAMP ,ONBIT>
    <CONSUMABLE-LIGHT-PUT ,CL-LAMP-STAGE ,LIGHT-BRIGHT>
    <SETG LIT <LIT? ,HERE>>
    <TELL "TEST PRECONDITION: fresh bright canonical lamp held in the unrevealed grue-colony dead end." CR>
    <RTRUE>>

<ROUTINE V-CONSUMABLE-WEAK-TEST ()
    <CONSUMABLE-LIGHT-RESET>
    <CONSUMABLE-TEST-COLONY-BASE>
    <FSET ,LAMP ,ONBIT>
    <CONSUMABLE-LIGHT-PUT ,CL-LAMP-STAGE ,LIGHT-WEAK>
    <SETG LIT <LIT? ,HERE>>
    <TELL "TEST PRECONDITION: weakened canonical lamp held in the unrevealed grue-colony dead end." CR>
    <RTRUE>>

<ROUTINE V-CONSUMABLE-EMBER-TEST ()
    <CONSUMABLE-LIGHT-RESET>
    <CONSUMABLE-TEST-COLONY-BASE>
    <MOVE ,MATCH ,WINNER>
    <FSET ,LAMP ,ONBIT>
    <CONSUMABLE-LIGHT-PUT ,CL-LAMP-STAGE ,LIGHT-BRIGHT>
    <SETG LIT <LIT? ,HERE>>
    <TELL "TEST PRECONDITION: bright lamp and real matchbook held in the unrevealed grue-colony dead end." CR>
    <RTRUE>>

<ROUTINE V-CONSUMABLE-WET-TEST ()
    <CONSUMABLE-LIGHT-RESET>
    <DISABLE <INT I-CANDLES>>
    <FCLEAR ,CANDLES ,ONBIT>
    <FCLEAR ,CANDLES ,RMUNGBIT>
    <FSET ,CANDLES ,FLAMEBIT>
    <MOVE ,CANDLES ,WINNER>
    <MOVE ,MATCH ,WINNER>
    <FCLEAR ,MATCH ,ONBIT>
    <FCLEAR ,MATCH ,FLAMEBIT>
    <MOVE ,BOTTLE ,WINNER>
    <FSET ,BOTTLE ,OPENBIT>
    <MOVE ,WATER ,BOTTLE>
    <CONSUMABLE-LIGHT-PUT ,CL-CANDLE-STAGE ,LIGHT-WEAK>
    <CONSUMABLE-LIGHT-PUT ,CL-CANDLE-WET 0>
    <GOTO ,LIVING-ROOM>
    <TELL "TEST PRECONDITION: dry shortened candles, real matches, and open bottled water held in a safe lit room." CR>
    <RTRUE>>

<ROUTINE V-CONSUMABLE-SMOKE-TEST ()
    <CONSUMABLE-LIGHT-RESET>
    <FIRE-STRUCTURAL-RESET>
    <MOVE ,LAMP ,WINNER>
    <FSET ,LAMP ,ONBIT>
    <GOTO ,TIMBER-ROOM>
    <FCLEAR ,LAMP ,ONBIT>
    <MOVE ,LAMP ,LIVING-ROOM>
    <MOVE ,CANDLES ,WINNER>
    <FSET ,CANDLES ,ONBIT>
    <FSET ,CANDLES ,FLAMEBIT>
    <FCLEAR ,CANDLES ,RMUNGBIT>
    <FSET ,CANDLES ,TOUCHBIT>
    <DISABLE <INT I-CANDLES>>
    <CONSUMABLE-LIGHT-PUT ,CL-CANDLE-STAGE ,LIGHT-EMBER>
    <CONSUMABLE-LIGHT-PUT ,CL-CANDLE-WET 0>
    <FIRE-STRUCTURAL-SET-STAGE ,FIRE-TIMBER-BURNING>
    <FIRE-STRUCTURAL-PUT ,FS-TIMBER-TIMER 3>
    <SETG LIT <LIT? ,HERE>>
    <TELL "TEST PRECONDITION: ember-stage candles held in the actively burning, smoke-filled Timber Room." CR>
    <RTRUE>>

<ROUTINE V-CONSUMABLE-TORCH-TEST ()
    <CONSUMABLE-LIGHT-RESET>
    <CONSUMABLE-TEST-COLONY-BASE>
    <MOVE ,TORCH ,WINNER>
    <FSET ,TORCH ,ONBIT>
    <FSET ,TORCH ,FLAMEBIT>
    <SETG LIT <LIT? ,HERE>>
    <TELL "TEST PRECONDITION: canonical flaming ivory torch held in the unrevealed grue-colony dead end." CR>
    <RTRUE>>

<ROUTINE V-CONSUMABLE-STATUS-TEST ()
    <TELL "TEST consumable light state: lamp-stage=" N <CONSUMABLE-LIGHT-GET ,CL-LAMP-STAGE>
          " candle-stage=" N <CONSUMABLE-LIGHT-GET ,CL-CANDLE-STAGE>
          " candle-wet=" N <CONSUMABLE-LIGHT-GET ,CL-CANDLE-WET>
          " current-level=" N <CONSUMABLE-CURRENT-LIGHT-LEVEL>
          " lamp-on=" N <COND (<FSET? ,LAMP ,ONBIT> 1) (T 0)>
          " candles-on=" N <COND (<FSET? ,CANDLES ,ONBIT> 1) (T 0)>
          " match-on=" N <COND (<FSET? ,MATCH ,ONBIT> 1) (T 0)>
          " fire-stage=" N <FIRE-STRUCTURAL-STAGE>
          " grue-revealed=" N <COND (<GRUE-COLONY-REVEALED?> 1) (T 0)> CR>
    <RTRUE>>
