"Test-only playback setup, mutation, integrity, and reporting for Release 1227 qualification."

<SYNTAX PSETUP = V-PLAYBACK-TEST-SETUP>
<SYNTAX POBSERVE = V-PLAYBACK-TEST-OBSERVE>
<SYNTAX PREADY = V-PLAYBACK-TEST-READY>
<SYNTAX PREPORT = V-PLAYBACK-TEST-REPORT>
<SYNTAX PSTATE = V-PLAYBACK-TEST-STATE>
<SYNTAX PMUTATE = V-PLAYBACK-TEST-MUTATE>

<GLOBAL PB-TEST-HERE 0>
<GLOBAL PB-TEST-SCORE 0>
<GLOBAL PB-TEST-IT 0>
<GLOBAL PB-TEST-TROLL-LOC 0>
<GLOBAL PB-TEST-CYCLOPS-LOC 0>
<GLOBAL PB-TEST-THIEF-LOC 0>
<GLOBAL PB-TEST-RECORD-LOC 0>

<ROUTINE PLAYBACK-TEST-REMOVE (OBJ)
    <COND (<LOC .OBJ> <REMOVE-CAREFULLY .OBJ>)>
    <RTRUE>>

<ROUTINE PLAYBACK-TEST-RESET ("AUX" (I 0))
    <PLAYBACK-PUT ,PB-SLOT-VERSION 1>
    <PLAYBACK-PUT ,PB-SLOT-CAPTURED 0>
    <PLAYBACK-PUT ,PB-SLOT-COUNT 0>
    <PLAYBACK-PUT ,PB-SLOT-FILED 0>
    <PLAYBACK-PUT ,PB-SLOT-EVENT-CAPTURE <>>
    <PLAYBACK-PUT ,PB-SLOT-EVENT-PRINTER <>>
    <PLAYBACK-PUT ,PB-SLOT-EVENT-CASSETTE <>>
    <PLAYBACK-PUT ,PB-SLOT-EVENT-SCENE <>>
    <PLAYBACK-PUT ,PB-SLOT-EVENT-FORENSIC <>>
    <PLAYBACK-PUT ,PB-SLOT-EVENT-RESTORE <>>
    <PLAYBACK-PUT ,PB-SLOT-LAST 0>
    <PLAYBACK-PUT ,PB-SLOT-PRIOR-IT <>>
    <REPEAT ()
        <COND (<NOT <L? .I ,PLAYBACK-MAX-EVENTS>> <RETURN>)>
        <PUT ,PLAYBACK-SEQUENCE .I 0>
        <SET I <+ .I 1>>>
    <RTRUE>>

<ROUTINE PLAYBACK-TEST-CLEAR-RECORDS ()
    <PLAYBACK-TEST-REMOVE ,PLAYBACK-PRINTOUT>
    <PLAYBACK-TEST-REMOVE ,PLAYBACK-CASSETTE>
    <PLAYBACK-TEST-REMOVE ,PLAYBACK-INCIDENT-CARD>
    <PLAYBACK-TEST-REMOVE ,PLAYBACK-ACTOR-CARD>
    <PLAYBACK-TEST-REMOVE ,PLAYBACK-PLACE-CARD>
    <PLAYBACK-TEST-REMOVE ,PLAYBACK-CHRONOLOGY-CARD>
    <PLAYBACK-TEST-REMOVE ,PLAYBACK-FORENSIC-STRIP>
    <RTRUE>>

<ROUTINE V-PLAYBACK-TEST-SETUP ()
    <PLAYBACK-TEST-CLEAR-RECORDS>
    <PLAYBACK-TEST-RESET>

    <SETG HOUSE-EVENT-ENTERED T>
    <SETG HOUSE-EVENT-RETURN T>
    <AREA-PUT ,AREA-SLOT-FOREST ,AREA-FOREST-ONE>

    <SETG DAM-MECH-PANEL-DIAGNOSED T>
    <SETG DAM-MECH-INTERLOCK-SEEN T>
    <SETG DAM-MECH-LEAK-REPAIRED T>

    <SETG RITUAL-BELL-ANSWERED T>
    <SETG RITUAL-WRONG-ORDER-SEEN T>
    <SETG RITUAL-PRAYER-COMPLETED T>

    <NPC-PUT ,NS-SEEN 7>
    <AREA-SET ,AREA-SLOT-COMPLETE ,AREA-BIT-SYNTHESIS>

    <PLAYBACK-OBSERVE>
    <MOVE ,LAMP ,WINNER>
    <FSET ,LAMP ,ONBIT>
    <GOTO ,ATTIC>
    <SETG CLOCK-WAIT T>
    <TELL "PLAYBACK-SETUP:READY" CR>>

<ROUTINE V-PLAYBACK-TEST-OBSERVE ()
    <PLAYBACK-OBSERVE>
    <SETG CLOCK-WAIT T>
    <TELL "PLAYBACK-OBSERVE:DONE" CR>>

<ROUTINE V-PLAYBACK-TEST-READY ()
    <SETG P-IT-OBJECT ,LAMP>
    <PLAYBACK-PUT ,PB-SLOT-PRIOR-IT ,LAMP>
    <SETG SHADOW-SELF-FIRE 1>
    <SETG PB-TEST-HERE ,HERE>
    <SETG PB-TEST-SCORE ,SCORE>
    <SETG PB-TEST-IT ,LAMP>
    <SETG PB-TEST-TROLL-LOC <LOC ,TROLL>>
    <SETG PB-TEST-CYCLOPS-LOC <LOC ,CYCLOPS>>
    <SETG PB-TEST-THIEF-LOC <LOC ,THIEF>>
    <SETG PB-TEST-RECORD-LOC <LOC ,PLAYBACK-CASSETTE>>
    <SETG CLOCK-WAIT T>
    <TELL "PLAYBACK-INTEGRITY:ARMED" CR>>

<ROUTINE PLAYBACK-TEST-PRESENT (OBJ)
    <COND (<LOC .OBJ> <TELL "Y">) (T <TELL "N">)>>

<ROUTINE V-PLAYBACK-TEST-REPORT ()
    <TELL "PLAYBACK:VERSION=" N <PLAYBACK-GET ,PB-SLOT-VERSION>
          ";CAPTURED=" N <PLAYBACK-GET ,PB-SLOT-CAPTURED>
          ";COUNT=" N <PLAYBACK-GET ,PB-SLOT-COUNT>
          ";FILED=" N <PLAYBACK-GET ,PB-SLOT-FILED>
          ";PRINTOUT=">
    <PLAYBACK-TEST-PRESENT ,PLAYBACK-PRINTOUT>
    <TELL ";CASSETTE="><PLAYBACK-TEST-PRESENT ,PLAYBACK-CASSETTE>
    <TELL ";INCIDENT="><PLAYBACK-TEST-PRESENT ,PLAYBACK-INCIDENT-CARD>
    <TELL ";ACTOR="><PLAYBACK-TEST-PRESENT ,PLAYBACK-ACTOR-CARD>
    <TELL ";PLACE="><PLAYBACK-TEST-PRESENT ,PLAYBACK-PLACE-CARD>
    <TELL ";CHRONOLOGY="><PLAYBACK-TEST-PRESENT ,PLAYBACK-CHRONOLOGY-CARD>
    <TELL ";FORENSIC="><PLAYBACK-TEST-PRESENT ,PLAYBACK-FORENSIC-STRIP>
    <TELL ";PRINT-CABINET=">
    <COND (<IN? ,PLAYBACK-PRINTOUT ,ARCHIVE-CABINET> <TELL "Y">) (T <TELL "N">)>
    <CRLF>
    <SETG CLOCK-WAIT T>>

<ROUTINE V-PLAYBACK-TEST-STATE ("AUX" OK)
    <SET OK T>
    <COND (<NOT <EQUAL? ,HERE ,PB-TEST-HERE>> <SET OK <>>)>
    <COND (<NOT <EQUAL? ,SCORE ,PB-TEST-SCORE>> <SET OK <>>)>
    <COND (<NOT <EQUAL? ,P-IT-OBJECT ,PB-TEST-IT>> <SET OK <>>)>
    <COND (<NOT <EQUAL? <LOC ,TROLL> ,PB-TEST-TROLL-LOC>> <SET OK <>>)>
    <COND (<NOT <EQUAL? <LOC ,CYCLOPS> ,PB-TEST-CYCLOPS-LOC>> <SET OK <>>)>
    <COND (<NOT <EQUAL? <LOC ,THIEF> ,PB-TEST-THIEF-LOC>> <SET OK <>>)>
    <COND (<NOT <EQUAL? <LOC ,PLAYBACK-CASSETTE> ,PB-TEST-RECORD-LOC>> <SET OK <>>)>
    <COND (<NOT <EQUAL? ,SHADOW-SELF-FIRE 1>> <SET OK <>>)>
    <TELL "PLAYBACK-INTEGRITY=">
    <COND (.OK <TELL "Y">) (T <TELL "N">)>
    <TELL ";HERE=" D ,HERE
          ";SCORE=" N ,SCORE
          ";PRONOUN=" D ,P-IT-OBJECT
          ";TIMER=" N ,SHADOW-SELF-FIRE CR>
    <SETG CLOCK-WAIT T>>

<ROUTINE V-PLAYBACK-TEST-MUTATE ()
    <PLAYBACK-TEST-CLEAR-RECORDS>
    <PLAYBACK-TEST-RESET>
    <SETG HOUSE-EVENT-ENTERED <>>
    <SETG HOUSE-EVENT-RETURN <>>
    <AREA-PUT ,AREA-SLOT-FOREST 0>
    <SETG DAM-MECH-PANEL-DIAGNOSED <>>
    <SETG DAM-MECH-INTERLOCK-SEEN <>>
    <SETG DAM-MECH-LEAK-REPAIRED <>>
    <SETG RITUAL-BELL-ANSWERED <>>
    <SETG RITUAL-WRONG-ORDER-SEEN <>>
    <SETG RITUAL-PRAYER-COMPLETED <>>
    <NPC-PUT ,NS-SEEN 0>
    <AREA-PUT ,AREA-SLOT-COMPLETE 0>
    <SETG P-IT-OBJECT <>>
    <SETG SHADOW-SELF-FIRE 0>
    <GOTO ,NORTH-OF-HOUSE>
    <SETG CLOCK-WAIT T>
    <TELL "PLAYBACK:MUTATED" CR>>
