"TEST-ONLY RELEASE 1274 DIEGETIC PUZZLE FURNITURE PRECONDITIONS"

<SYNTAX DFBOOK = V-DF-BOOK-TEST>
<SYNTAX DFVAULT = V-DF-VAULT-TEST>
<SYNTAX DFCLOCK = V-DF-CLOCK-TEST>
<SYNTAX DFWET = V-DF-WET-TEST>
<SYNTAX DFDRY = V-DF-DRY-TEST>

<ROUTINE DF-TEST-RESET ()
    <SETG ALWAYS-LIT T>
    <DIEGETIC-PUT ,DF-SCRIPTORIUM-SHELF-OPEN 0>
    <DIEGETIC-PUT ,DF-VAULT-COMPARTMENT-OPEN 0>
    <DIEGETIC-PUT ,DF-CLOCK-HAND-ALIGNED 0>
    <DIEGETIC-PUT ,DF-CLOCK-RECESS-OPEN 0>
    <DIEGETIC-PUT ,DF-CISTERN-BRICK-OPEN 0>
    <DIEGETIC-PUT ,DF-CISTERN-DIVERTED 0>
    <MOVE ,DIEGETIC-BRONZE-STAR-WHEEL ,ASHGLASS-VAULT>
    <FSET ,DIEGETIC-BRONZE-STAR-WHEEL ,INVISIBLE>
    <FSET ,DIEGETIC-CLOCK-RECESS ,INVISIBLE>
    <FSET ,DIEGETIC-DRAIN-ROD ,INVISIBLE>
    <RTRUE>>

<ROUTINE V-DF-BOOK-TEST ()
    <DF-TEST-RESET>
    <GOTO ,ASHGLASS-SCRIPTORIUM>
    <TELL "TEST PRECONDITION: Scriptorium shelf shut; captive index volume untouched." CR>
    <RTRUE>>

<ROUTINE V-DF-VAULT-TEST ()
    <DF-TEST-RESET>
    <GOTO ,ASHGLASS-VAULT>
    <TELL "TEST PRECONDITION: proud mineral tray closed; star-wheel hidden behind false back." CR>
    <RTRUE>>

<ROUTINE V-DF-CLOCK-TEST ()
    <DF-TEST-RESET>
    <GOTO ,ASHGLASS-BELL-TOWER>
    <TELL "TEST PRECONDITION: weather clock stopped off-index; maintenance recess closed." CR>
    <RTRUE>>

<ROUTINE DF-TEST-CANDLES ()
    <DF-TEST-RESET>
    <CONSUMABLE-LIGHT-RESET>
    <COND (<LOC ,CANDLES> <REMOVE-CAREFULLY ,CANDLES>)>
    <MOVE ,CANDLES ,WINNER>
    <FCLEAR ,CANDLES ,RMUNGBIT>
    <FSET ,CANDLES ,ONBIT>
    <FSET ,CANDLES ,TOUCHBIT>
    <CONSUMABLE-LIGHT-PUT ,CL-CANDLE-WET 0>
    <GOTO ,ASHGLASS-LOW-CISTERN>
    <RTRUE>>

<ROUTINE V-DF-WET-TEST ()
    <DF-TEST-CANDLES>
    <TELL "TEST PRECONDITION: original cistern spill active; dry lit candles held." CR>
    <RTRUE>>

<ROUTINE V-DF-DRY-TEST ()
    <DF-TEST-CANDLES>
    <TELL "TEST PRECONDITION: cistern diversion closed; dry lit candles held." CR>
    <RTRUE>>
