"MARA COMPANION EXPEDITION FOUNDATION for Release 1243"

;"Mara Tallow is one authored human expedition partner with her own location,
  equipment, judgment, boundaries, field work, and evidence-limited memory.
  This release gives her a Dam-centered first chapter and regional company;
  it does not create a generic follower, party, chatbot, or approval system."

<SYNTAX SHOW OBJECT (HELD CARRIED HAVE) TO OBJECT (FIND ACTORBIT) (IN-ROOM)
    = V-MARA-SHOW>
<SYNONYM SHOW PRESENT>
<SYNTAX BRACE OBJECT = V-MARA-BRACE>
<SYNONYM BRACE STEADY>
<SYNTAX SURVEY OBJECT WITH OBJECT (FIND ACTORBIT) (IN-ROOM) = V-MARA-SURVEY>
<SYNONYM SURVEY MEASURE>
<SYNTAX THANK OBJECT (FIND ACTORBIT) (IN-ROOM) = V-MARA-THANK>
<SYNONYM THANK>
<SYNTAX APOLOGIZE TO OBJECT (FIND ACTORBIT) (IN-ROOM) = V-MARA-APOLOGIZE>
<SYNTAX APOLOGISE TO OBJECT (FIND ACTORBIT) (IN-ROOM) = V-MARA-APOLOGIZE>
<SYNONYM APOLOGIZE APOLOGISE>

<CONSTANT MARA-SCHEMA 2>
<CONSTANT MARA-SLOT-MET 1>
<CONSTANT MARA-SLOT-TRUST 2>
<CONSTANT MARA-SLOT-LAST-EVIDENCE 3>
<CONSTANT MARA-SLOT-RESPECT 4>
<CONSTANT MARA-SLOT-SAFETY 5>
<CONSTANT MARA-SLOT-MODE 6>
<CONSTANT MARA-SLOT-DAM-BRACED 7>
<CONSTANT MARA-SLOT-DAM-CYCLED 8>
<CONSTANT MARA-SLOT-DAM-SURVEY 9>
<CONSTANT MARA-SLOT-LEAK-WARNED 10>
<CONSTANT MARA-SLOT-LEAK-CAUSED 11>
<CONSTANT MARA-SLOT-LEAK-REPAIRED 12>
<CONSTANT MARA-SLOT-APOLOGY 13>
<CONSTANT MARA-SLOT-THANKED 14>
<CONSTANT MARA-SLOT-EVIDENCE-SHARED 15>
<CONSTANT MARA-SLOT-FISH-WITNESSED 16>
<CONSTANT MARA-SLOT-FISH-RELEASED 17>
<CONSTANT MARA-SLOT-HOUSE-VISITED 18>
<CONSTANT MARA-STATE <TABLE MARA-SCHEMA 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0>>

<CONSTANT MARA-MODE-INDEPENDENT 0>
<CONSTANT MARA-MODE-FOLLOWING 1>
<CONSTANT MARA-MODE-WAITING 2>

<OBJECT MARA-SURVEY-TOPIC
    (IN GLOBAL-OBJECTS)
    (SYNONYM SURVEY SURVEYS MAPPING MAPS GEOGRAPHY ROUTES RECORD)
    (ADJECTIVE HONEST LAST IMPERIAL UNDERGROUND)
    (DESC "Mara's survey work")
    (FLAGS NDESCBIT RMUNGBIT)>

<OBJECT MARA-COMPANY-TOPIC
    (IN GLOBAL-OBJECTS)
    (SYNONYM COMPANY COMPANION PARTNER PARTNERSHIP ALLIANCE FRIENDSHIP)
    (ADJECTIVE TRAVEL SHARED EXPEDITION)
    (DESC "travelling together")
    (FLAGS NDESCBIT RMUNGBIT)>

<OBJECT MARA-DAM-TOPIC
    (IN GLOBAL-OBJECTS)
    (SYNONYM DAM SPILLWAY SLUICE GATES INTERLOCK FLOOD)
    (ADJECTIVE CONTROL THIRD THREE)
    (DESC "Flood Control Dam #3")
    (FLAGS NDESCBIT RMUNGBIT)>

<OBJECT MARA-FIELD-PACK
    (IN DAM-BASE)
    (SYNONYM PACK SATCHEL BAG CAMP CACHE)
    (ADJECTIVE MARA MARAS FIELD SURVEY WAXED CANVAS PRIVATE)
    (DESC "Mara's waxed field pack")
    (LDESC "A waxed canvas field pack rests above the river spray, secured with a surveyor's locking hitch.")
    (FLAGS CONTBIT SEARCHBIT TRYTAKEBIT)
    (CAPACITY 30)
    (ACTION MARA-FIELD-PACK-FCN)>

<OBJECT MARA-NOTEBOOK
    (IN MARA-FIELD-PACK)
    (SYNONYM NOTEBOOK JOURNAL BOOK NOTES)
    (ADJECTIVE MARA MARAS FIELD SURVEY WAXED PRIVATE)
    (DESC "Mara's field notebook")
    (FLAGS TAKEBIT READBIT NDESCBIT)
    (ACTION MARA-PRIVATE-EQUIPMENT-FCN)>

<OBJECT MARA-FIELD-ROPE
    (SYNONYM ROPE LINE CORD)
    (ADJECTIVE MARA MARAS FIELD WAXED SURVEY)
    (DESC "Mara's waxed survey rope")
    (FLAGS TAKEBIT NDESCBIT)
    (SIZE 10)
    (ACTION MARA-PRIVATE-EQUIPMENT-FCN)>

<OBJECT MARA-FIELD-LANTERN
    (SYNONYM LANTERN LAMP LIGHT)
    (ADJECTIVE MARA MARAS FIELD HOODED RESERVE)
    (DESC "Mara's hooded field lantern")
    (FLAGS TAKEBIT LIGHTBIT NDESCBIT)
    (SIZE 8)
    (ACTION MARA-PRIVATE-EQUIPMENT-FCN)>

<OBJECT MARA-DAM-SURVEY-SHEET
    (SYNONYM SHEET SURVEY RECORD RUBBING MEASUREMENTS MAP)
    (ADJECTIVE MARA MARAS DAM JOINT HONEST WAXED FIELD)
    (DESC "joint Dam survey sheet")
    (FLAGS TAKEBIT READBIT NDESCBIT)
    (SIZE 2)
    (ACTION MARA-DAM-SURVEY-SHEET-FCN)>

<INSERT-FILE "mara_companion_state" T>
<INSERT-FILE "mara_companion_movement" T>
<INSERT-FILE "mara_companion_actions" T>
<INSERT-FILE "mara_companion_actor" T>
