"FLATHEAD FAIR TEST VERBS — test story only"

<SYNTAX FAIRHERE = V-FAIR-HERE>
<SYNTAX FAIRBANK = V-FAIR-BANK>
<SYNTAX FAIRDUSK = V-FAIR-DUSK>
<SYNTAX FAIRWIND = V-FAIR-WIND-SET>
<SYNTAX FAIRWATCH = V-FAIR-GALLERY-SET>
<SYNTAX FAIRFISH = V-FAIR-FISH-SET>

<ROUTINE V-FAIR-HERE ()
    <SETG HERE ,FAIR-ENTRANCE>
    <MOVE ,WINNER ,FAIR-ENTRANCE>
    <MARA-ENSURE>
    <MOVE ,MARA ,HERE>
    <FAIR-PLACE-CAST>
    <TELL "[TEST] Fair Entrance, Mara present." CR>
    <V-LOOK>>

<ROUTINE V-FAIR-BANK ()
    <SETG FAIR-ZORKMIDS 80>
    <SETG FAIR-TICKETS 12>
    <TELL "[TEST] 80 zm and 12 tickets." CR>>

<ROUTINE V-FAIR-DUSK ()
    <SETG FAIR-PHASE ,FAIR-DUSK>
    <FAIR-ON-PHASE>
    <TELL "[TEST] Dusk." CR>>

<ROUTINE V-FAIR-WIND-SET ()
    <SETG FAIR-WIND 2>
    <TELL "[TEST] Unsafe wind." CR>>

<ROUTINE V-FAIR-GALLERY-SET ()
    <SETG FAIR-GALLERY 2>
    <TELL "[TEST] Gallery cycle 2." CR>>

<ROUTINE V-FAIR-FISH-SET ()
    <SETG FAIR-CATCH 1>
    <TELL "A redfin bream. Ordinary, real, and not a legendary class. Committed." CR>>
