"TEST-ONLY GRUE COLONY PRECONDITIONS"

<SYNTAX GRUEWEAK = V-GRUE-WEAK-TEST>
<SYNTAX GRUESTRONG = V-GRUE-STRONG-TEST>
<SYNTAX GRUESTATUS = V-GRUE-STATUS-TEST>

<ROUTINE GRUE-COLONY-TEST-RESET ()
    <PUTP ,GRUE-FISSURES ,P?VALUE 0>
    <MOVE ,LAMP ,WINNER>
    <FSET ,LAMP ,ONBIT>
    <MOVE ,TORCH ,PEDESTAL>
    <RFALSE>>

<ROUTINE V-GRUE-WEAK-TEST ()
    <GRUE-COLONY-TEST-RESET>
    <GOTO ,DEAD-END-5>
    <PERFORM ,V?EXAMINE ,GRUE-FISSURES>
    <PERFORM ,V?LISTEN ,GRUE-FISSURES>
    <TELL "TEST PRECONDITION: ordinary-light colony evidence exercised." CR>
    <RTRUE>>

<ROUTINE V-GRUE-STRONG-TEST ()
    <GRUE-COLONY-TEST-RESET>
    <MOVE ,TORCH ,WINNER>
    <GOTO ,DEAD-END-5>
    <PERFORM ,V?EXAMINE ,GRUE>
    <PERFORM ,V?LISTEN ,GRUE>
    <PERFORM ,V?EXAMINE ,GRUE-FISSURES>
    <TELL "TEST PRECONDITION: permanent-torch colony reveal exercised." CR>
    <RTRUE>>

<ROUTINE V-GRUE-STATUS-TEST ()
    <COND (<G? <GETP ,GRUE-FISSURES ,P?VALUE> 0>
           <TELL "TEST grue colony reveal: active" CR>)
          (T <TELL "TEST grue colony reveal: hidden" CR>)>
    <RTRUE>>
