"TEST-ONLY RELEASE 1270 CAUSAL FAILURE PRECONDITIONS"

<SYNTAX CFFDRAGON = V-CFF-DRAGON-TEST>
<SYNTAX CFFDAM = V-CFF-DAM-TEST>
<SYNTAX CFFCANYON = V-CFF-CANYON-TEST>

<ROUTINE CFF-RESET-DRAGON ()
    <SETG ALWAYS-LIT T>
    <STRUCTURAL-DIFFICULTY-RESET>
    <DRAGON-RESET>
    <ABLATIVE-RESET>
    <FIRE-STRUCTURAL-RESET>
    <COND (<IN? ,CHALICE ,WINNER> <REMOVE-CAREFULLY ,CHALICE>)>
    <MOVE ,CHALICE ,WINNER>
    <RTRUE>>

<ROUTINE V-CFF-DRAGON-TEST ()
    <CFF-RESET-DRAGON>
    <STRUCTURAL-DIFFICULTY-SET ,SD-CLASSIC>
    <GOTO ,DRAGON-GALLERY>
    <TELL "TEST PRECONDITION: canonical Classic dragon situation ready for Release 1270 failure feedback." CR>
    <RTRUE>>

<ROUTINE V-CFF-DAM-TEST ()
    <SETG ALWAYS-LIT T>
    <SETG GATES-OPEN T>
    <SETG LOW-TIDE <>>
    <SETG MATERIAL-ROPE-ANCHOR <>>
    <COND (<IN? ,ROPE ,WINNER> <REMOVE-CAREFULLY ,ROPE>)>
    <GOTO ,DAM-BASE>
    <TELL "TEST PRECONDITION: open-sluice Frigid River at the canonical dam landing with no prepared restraint." CR>
    <RTRUE>>

<ROUTINE V-CFF-CANYON-TEST ()
    <SETG ALWAYS-LIT T>
    <COND (<IN? ,ROPE ,LIVING-CANYON-EDGE> <MOVE ,ROPE ,WEST-OF-HOUSE>)>
    <LIVING-CANYON-PUT ,LIVING-CANYON-SLOT-VERSION ,LIVING-CANYON-SCHEMA>
    <LIVING-CANYON-PUT ,LIVING-CANYON-SLOT-WARNED 0>
    <GOTO ,CANYON-VIEW>
    <TELL "TEST PRECONDITION: canonical Great Canyon rim restored without a secured rope." CR>
    <RTRUE>>
