"TEST-ONLY RELEASE 1263 ABLATIVE-PROTECTION PRECONDITIONS"

<SYNTAX APREP = V-ABLATIVE-PREP-TEST>
<SYNTAX ASCORCHED = V-ABLATIVE-SCORCHED-TEST>
<SYNTAX AWARPED = V-ABLATIVE-WARPED-TEST>
<SYNTAX ANOSCREEN = V-ABLATIVE-NO-SCREEN-TEST>
<SYNTAX ASTATUS = V-ABLATIVE-STATUS-TEST>

<ROUTINE ABLATIVE-TEST-BASE ()
    <DRAGON-RESET>
    <ABLATIVE-RESET>
    <FIRE-STRUCTURAL-RESET>
    <MOVE ,LAMP ,WINNER>
    <FSET ,LAMP ,ONBIT>
    <RTRUE>>

<ROUTINE V-ABLATIVE-PREP-TEST ()
    <ABLATIVE-TEST-BASE>
    <MOVE ,DRAGON-FIRE-SCREEN ,WINNER>
    <GOTO ,DRAGON-GALLERY>
    <TELL "TEST PRECONDITION: sound fire screen held in lit Dragon Gallery." CR>
    <RTRUE>>

<ROUTINE V-ABLATIVE-SCORCHED-TEST ()
    <ABLATIVE-TEST-BASE>
    <MOVE ,DRAGON-FIRE-SCREEN ,WINNER>
    <ABLATIVE-PUT ,APS-CONDITION ,AP-SCORCHED>
    <GOTO ,DRAGON-GALLERY>
    <TELL "TEST PRECONDITION: scorched fire screen held in lit Dragon Gallery." CR>
    <RTRUE>>

<ROUTINE V-ABLATIVE-WARPED-TEST ()
    <ABLATIVE-TEST-BASE>
    <MOVE ,DRAGON-FIRE-SCREEN ,WINNER>
    <ABLATIVE-PUT ,APS-CONDITION ,AP-WARPED>
    <GOTO ,DRAGON-GALLERY>
    <TELL "TEST PRECONDITION: warped fire screen held in lit Dragon Gallery." CR>
    <RTRUE>>

<ROUTINE V-ABLATIVE-NO-SCREEN-TEST ()
    <ABLATIVE-TEST-BASE>
    <MOVE ,DRAGON-FIRE-SCREEN ,DRAGON-APPROACH>
    <GOTO ,DRAGON-GALLERY>
    <TELL "TEST PRECONDITION: live dragon, no fire screen held." CR>
    <RTRUE>>

<ROUTINE V-ABLATIVE-STATUS-TEST ()
    <TELL "TEST ablative state: condition=" N <ABLATIVE-GET ,APS-CONDITION>
          " prepared=" N <ABLATIVE-GET ,APS-PREPARED>
          " screen-held=" N <COND (<IN? ,DRAGON-FIRE-SCREEN ,WINNER> 1) (T 0)> CR>
    <RTRUE>>
