"Test-only Attic archive setup, mutation, and reporting verbs for Release 1224 qualification."

<SYNTAX ASETUP = V-ARCHIVE-TEST-SETUP>
<SYNTAX AREPORT = V-ARCHIVE-TEST-REPORT>
<SYNTAX AMUTATE = V-ARCHIVE-TEST-MUTATE>

<ROUTINE ARCHIVE-TEST-REMOVE (OBJ)
    <COND (<LOC .OBJ> <REMOVE-CAREFULLY .OBJ>)>
    <RTRUE>>

<ROUTINE ARCHIVE-TEST-RESET ()
    <ARCHIVE-PUT ,AS-VERSION 1>
    <ARCHIVE-PUT ,AS-INDEXED 0>
    <ARCHIVE-PUT ,AS-FILED 0>
    <ARCHIVE-PUT ,AS-ANNOTATED 0>
    <ARCHIVE-PUT ,AS-EVENT-SCHEMA <>>
    <ARCHIVE-PUT ,AS-EVENT-MEDIA <>>
    <ARCHIVE-PUT ,AS-EVENT-CATALOG <>>
    <ARCHIVE-PUT ,AS-EVENT-FILING <>>
    <ARCHIVE-PUT ,AS-EVENT-RETRIEVAL <>>
    <ARCHIVE-PUT ,AS-EVENT-PROVENANCE <>>
    <ARCHIVE-PUT ,AS-EVENT-MIGRATION <>>
    <ARCHIVE-PUT ,AS-LAST-RECORD 0>
    <RTRUE>>

<ROUTINE ARCHIVE-TEST-CLEAR-SOURCES ()
    <ARCHIVE-TEST-REMOVE ,MAIL-CELLAR-NOTE>
    <ARCHIVE-TEST-REMOVE ,MAIL-MUSEUM-NOTE>
    <ARCHIVE-TEST-REMOVE ,MAIL-DAM-NOTE>
    <ARCHIVE-TEST-REMOVE ,MAIL-COURIER-NOTICE>
    <ARCHIVE-TEST-REMOVE ,MAIL-SURVEYOR-NOTICE>
    <ARCHIVE-TEST-REMOVE ,MAIL-RETURN-RECEIPT>
    <ARCHIVE-TEST-REMOVE ,MAIL-SURVEY-TAG>
    <MAIL-PUT ,MS-QUEUED 0>
    <MAIL-PUT ,MS-DELIVERED 0>
    <MAIL-PUT ,MS-READ 0>
    <MAIL-PUT ,MS-REPLIED 0>
    <MAIL-PUT ,MS-SENT 0>
    <MAIL-PUT ,MS-REPLY-TARGET 0>
    <MAIL-PUT ,MS-VISITOR-QUEUED 0>
    <MAIL-PUT ,MS-VISITOR-ACTIVE 0>
    <MAIL-PUT ,MS-VISITOR-MISSED 0>
    <MAIL-PUT ,MS-VISITOR-REFUSED 0>
    <MAIL-PUT ,MS-VISITOR-COMPLETE 0>
    <RTRUE>>

<ROUTINE V-ARCHIVE-TEST-SETUP ()
    <ARCHIVE-TEST-REMOVE ,ARCHIVE-THRESHOLD-FOLDER>
    <ARCHIVE-TEST-REMOVE ,ARCHIVE-DISPLAY-CARD>
    <ARCHIVE-TEST-REMOVE ,ARCHIVE-DAM-PRINTOUT>
    <ARCHIVE-TEST-REMOVE ,ARCHIVE-VISITOR-FICHE>
    <ARCHIVE-TEST-REMOVE ,ARCHIVE-CHRONOLOGY-CASSETTE>
    <ARCHIVE-TEST-CLEAR-SOURCES>
    <ARCHIVE-TEST-RESET>
    <MAIL-PUT ,MS-VERSION 1>
    <MAIL-PUT ,MS-QUEUED 7>
    <MAIL-PUT ,MS-DELIVERED 7>
    <MOVE ,MAIL-CELLAR-NOTE ,MAILBOX>
    <MOVE ,MAIL-MUSEUM-NOTE ,MAILBOX>
    <MOVE ,MAIL-DAM-NOTE ,MAILBOX>
    <MOVE ,MAIL-COURIER-NOTICE ,MAILBOX>
    <MOVE ,MAIL-SURVEYOR-NOTICE ,MAILBOX>
    <MOVE ,MAIL-RETURN-RECEIPT ,MAILBOX>
    <MOVE ,MAIL-SURVEY-TAG ,MAILBOX>
    <MOVE ,LAMP ,WINNER>
    <FSET ,LAMP ,ONBIT>
    <GOTO ,ATTIC>
    <ARCHIVE-ENSURE>
    <ARCHIVE-SYNC>
    <SETG CLOCK-WAIT T>
    <TELL "ARCHIVE-SETUP:READY" CR>>

<ROUTINE ARCHIVE-TEST-BOOL (VALUE)
    <COND (.VALUE <TELL "Y">) (T <TELL "N">)>>

<ROUTINE V-ARCHIVE-TEST-REPORT ()
    <TELL "ARCHIVE:VERSION=" N <ARCHIVE-GET ,AS-VERSION>
          ";INDEXED=" N <ARCHIVE-GET ,AS-INDEXED>
          ";FILED=" N <ARCHIVE-GET ,AS-FILED>
          ";ANNOTATED=" N <ARCHIVE-GET ,AS-ANNOTATED>
          ";THRESHOLD=">
    <ARCHIVE-TEST-BOOL <LOC ,ARCHIVE-THRESHOLD-FOLDER>>
    <TELL ";DISPLAY=">
    <ARCHIVE-TEST-BOOL <LOC ,ARCHIVE-DISPLAY-CARD>>
    <TELL ";DAM=">
    <ARCHIVE-TEST-BOOL <LOC ,ARCHIVE-DAM-PRINTOUT>>
    <TELL ";VISITOR=">
    <ARCHIVE-TEST-BOOL <LOC ,ARCHIVE-VISITOR-FICHE>>
    <TELL ";CASSETTE=">
    <ARCHIVE-TEST-BOOL <LOC ,ARCHIVE-CHRONOLOGY-CASSETTE>>
    <TELL ";THRESHOLD-CABINET=">
    <ARCHIVE-TEST-BOOL <IN? ,ARCHIVE-THRESHOLD-FOLDER ,ARCHIVE-CABINET>>
    <CRLF>>

<ROUTINE V-ARCHIVE-TEST-MUTATE ()
    <ARCHIVE-TEST-REMOVE ,ARCHIVE-THRESHOLD-FOLDER>
    <ARCHIVE-TEST-REMOVE ,ARCHIVE-DISPLAY-CARD>
    <ARCHIVE-TEST-REMOVE ,ARCHIVE-DAM-PRINTOUT>
    <ARCHIVE-TEST-REMOVE ,ARCHIVE-VISITOR-FICHE>
    <ARCHIVE-TEST-REMOVE ,ARCHIVE-CHRONOLOGY-CASSETTE>
    <ARCHIVE-TEST-CLEAR-SOURCES>
    <ARCHIVE-TEST-RESET>
    <GOTO ,NORTH-OF-HOUSE>
    <SETG CLOCK-WAIT T>
    <TELL "ARCHIVE:MUTATED" CR>>
