"Test-only actor-state setup, mutation, and reporting for Release 1225 qualification."

<SYNTAX NSETUP = V-NPC-TEST-SETUP>
<SYNTAX NREPORT = V-NPC-TEST-REPORT>
<SYNTAX NMUTATE = V-NPC-TEST-MUTATE>

<ROUTINE NPC-TEST-REMOVE (OBJ)
    <COND (<LOC .OBJ> <REMOVE-CAREFULLY .OBJ>)>
    <RTRUE>>

<ROUTINE NPC-TEST-RESET ()
    <NPC-PUT ,NS-VERSION 1>
    <NPC-PUT ,NS-SEEN 0>
    <NPC-PUT ,NS-TROLL 0>
    <NPC-PUT ,NS-CYCLOPS 0>
    <NPC-PUT ,NS-THIEF 0>
    <NPC-PUT ,NS-FILED 0>
    <NPC-PUT ,NS-QUOTES 0>
    <NPC-PUT ,NS-EVENTS 0>
    <NPC-PUT ,NS-EVENT-DOSSIER <>>
    <NPC-PUT ,NS-EVENT-QUOTE <>>
    <NPC-PUT ,NS-EVENT-COMPLETE <>>
    <NPC-PUT ,NS-EVENT-RESTORE <>>
    <RTRUE>>

<ROUTINE V-NPC-TEST-SETUP ()
    <NPC-TEST-REMOVE ,NPC-TROLL-DOSSIER>
    <NPC-TEST-REMOVE ,NPC-CYCLOPS-DOSSIER>
    <NPC-TEST-REMOVE ,NPC-THIEF-DOSSIER>
    <NPC-TEST-REMOVE ,NPC-TIMELINE-CASSETTE>
    <NPC-TEST-RESET>
    <MOVE ,LAMP ,WINNER>
    <FSET ,LAMP ,ONBIT>

    <GOTO ,TROLL-ROOM>
    <FSET ,TROLL ,FIGHTBIT>
    <SETG TROLL-FLAG T>
    <MOVE ,AXE ,TROLL>
    <NPC-OBSERVE-WORLD>
    <NPC-SET ,NS-TROLL ,NPC-GIFT>
    <NPC-SET ,NS-TROLL ,NPC-ATTACK>
    <NPC-SET ,NS-TROLL ,NPC-RESTRAINT>

    <GOTO ,CYCLOPS-ROOM>
    <FSET ,CYCLOPS ,FIGHTBIT>
    <SETG CYCLOWRATH -2>
    <SETG CYCLOPS-FLAG T>
    <SETG MAGIC-FLAG T>
    <NPC-OBSERVE-WORLD>
    <NPC-SET ,NS-CYCLOPS ,NPC-BARGAIN>

    <SETG THIEF-HERE T>
    <SETG MUSEUM-THEFT-OCCURRED T>
    <SETG THIEF-ENGROSSED T>
    <FSET ,THIEF ,FIGHTBIT>
    <MOVE ,STILETTO ,THIEF>
    <NPC-OBSERVE-WORLD>
    <NPC-SET ,NS-THIEF ,NPC-GIFT>
    <NPC-SET ,NS-THIEF ,NPC-ATTACK>

    <NPC-PUT ,NS-EVENTS T>
    <GOTO ,ATTIC>
    <SETG CLOCK-WAIT T>
    <TELL "NPC-SETUP:READY" CR>>

<ROUTINE NPC-TEST-BOOL (VALUE)
    <COND (.VALUE <TELL "Y">) (T <TELL "N">)>>

<ROUTINE V-NPC-TEST-REPORT ()
    <TELL "NPC:VERSION=" N <NPC-GET ,NS-VERSION>
          ";SEEN=" N <NPC-GET ,NS-SEEN>
          ";TROLL=" N <NPC-GET ,NS-TROLL>
          ";CYCLOPS=" N <NPC-GET ,NS-CYCLOPS>
          ";THIEF=" N <NPC-GET ,NS-THIEF>
          ";FILED=" N <NPC-GET ,NS-FILED>
          ";TROLL=">
    <NPC-TEST-BOOL <LOC ,NPC-TROLL-DOSSIER>>
    <TELL ";CYCLOPS=">
    <NPC-TEST-BOOL <LOC ,NPC-CYCLOPS-DOSSIER>>
    <TELL ";THIEF=">
    <NPC-TEST-BOOL <LOC ,NPC-THIEF-DOSSIER>>
    <TELL ";TIMELINE=">
    <NPC-TEST-BOOL <LOC ,NPC-TIMELINE-CASSETTE>>
    <TELL ";TROLL-CABINET=">
    <NPC-TEST-BOOL <IN? ,NPC-TROLL-DOSSIER ,ARCHIVE-CABINET>>
    <CRLF>>

<ROUTINE V-NPC-TEST-MUTATE ()
    <NPC-TEST-REMOVE ,NPC-TROLL-DOSSIER>
    <NPC-TEST-REMOVE ,NPC-CYCLOPS-DOSSIER>
    <NPC-TEST-REMOVE ,NPC-THIEF-DOSSIER>
    <NPC-TEST-REMOVE ,NPC-TIMELINE-CASSETTE>
    <NPC-TEST-RESET>
    <SETG TROLL-FLAG <>>
    <SETG CYCLOWRATH 0>
    <SETG CYCLOPS-FLAG <>>
    <SETG MAGIC-FLAG <>>
    <SETG THIEF-HERE <>>
    <SETG MUSEUM-THEFT-OCCURRED <>>
    <SETG THIEF-ENGROSSED <>>
    <FCLEAR ,TROLL ,FIGHTBIT>
    <FCLEAR ,CYCLOPS ,FIGHTBIT>
    <FCLEAR ,THIEF ,FIGHTBIT>
    <FCLEAR ,THIEF ,INVISIBLE>
    <GOTO ,NORTH-OF-HOUSE>
    <SETG CLOCK-WAIT T>
    <TELL "NPC:MUTATED" CR>>
