"Test-only positioning, completion, mutation, recovery, and reporting verbs for Release 1220 qualification."

<SYNTAX MSETUP = V-MUSEUM-TEST-SETUP>
<SYNTAX MCOMPLETE = V-MUSEUM-TEST-COMPLETE>
<SYNTAX MREPORT = V-MUSEUM-TEST-REPORT>
<SYNTAX MMUTATE = V-MUSEUM-TEST-MUTATE>
<SYNTAX MRECOVER = V-MUSEUM-TEST-RECOVER>

<ROUTINE MUSEUM-TEST-QUIET-WORLD ()
    <QUEUE I-THIEF 0>
    <SETG THIEF-HERE <>>
    <REMOVE-CAREFULLY ,THIEF>
    <PUTP ,THIEF ,P?STRENGTH 5>
    <FSET ,THIEF ,INVISIBLE>
    <MOVE ,STILETTO ,THIEF>
    <FSET ,STILETTO ,NDESCBIT>
    <REMOVE-CAREFULLY ,TROLL>
    <SETG TROLL-FLAG T>
    <RTRUE>>

<ROUTINE MUSEUM-TEST-CLEAR-SURFACE (SURFACE "AUX" ITEM NEXT)
    <SET ITEM <FIRST? .SURFACE>>
    <REPEAT ()
        <COND (<NOT .ITEM> <RETURN>)>
        <SET NEXT <NEXT? .ITEM>>
        <MOVE .ITEM ,WINNER>
        <FCLEAR .ITEM ,INVISIBLE>
        <SET ITEM .NEXT>>
    <RTRUE>>

<ROUTINE MUSEUM-TEST-CLEAR-STATE ()
    <SETG MUSEUM-VERSION 1>
    <SETG MUSEUM-EVENT-DISPLAYED <>>
    <SETG MUSEUM-EVENT-CASE <>>
    <SETG MUSEUM-GROUP-HOUSE <>>
    <SETG MUSEUM-GROUP-RITUAL <>>
    <SETG MUSEUM-GROUP-DAM <>>
    <SETG MUSEUM-GROUP-CONFLICT <>>
    <SETG MUSEUM-GROUP-CANARY <>>
    <SETG MUSEUM-THEFT-OCCURRED <>>
    <SETG MUSEUM-THEFT-OBJECT <>>
    <SETG MUSEUM-THEFT-FROM <>>
    <SETG MUSEUM-LAST-DISPLAYED <>>
    <FSET ,MUSEUM-THEFT-EVIDENCE ,INVISIBLE>
    <RTRUE>>

<ROUTINE V-MUSEUM-TEST-SETUP ()
    <MUSEUM-TEST-QUIET-WORLD>
    <GOTO ,LIVING-ROOM>
    <MUSEUM-TEST-CLEAR-SURFACE ,MUSEUM-FRAME>
    <MUSEUM-TEST-CLEAR-SURFACE ,MUSEUM-WEAPON-WALL>
    <MUSEUM-TEST-CLEAR-SURFACE ,MUSEUM-RECORD-SHELF>
    <MUSEUM-TEST-CLEAR-SURFACE ,MUSEUM-RELIC-STAND>
    <MUSEUM-TEST-CLEAR-STATE>
    <PUTP ,WINNER ,P?CAPACITY 1000>
    <SETG LLD-FLAG <>>
    <SETG EGG-SOLVE <>>
    <SETG WATER-LEVEL 0>
    <SETG KITCHEN-WINDOW-FLAG <>>
    <FCLEAR ,KITCHEN-WINDOW ,OPENBIT>
    <FCLEAR ,TROPHY-CASE ,OPENBIT>
    <MOVE ,PAINTING ,WINNER>
    <MOVE ,SWORD ,WINNER>
    <MOVE ,MAP ,WINNER>
    <MOVE ,GUIDE ,WINNER>
    <MOVE ,WRENCH ,WINNER>
    <MOVE ,SCREWDRIVER ,WINNER>
    <MOVE ,BELL ,WINNER>
    <MOVE ,CANDLES ,WINNER>
    <MOVE ,BOOK ,WINNER>
    <MOVE ,AXE ,WINNER>
    <MOVE ,TRIDENT ,WINNER>
    <MOVE ,EGG ,WINNER>
    <MOVE ,CANARY ,EGG>
    <FCLEAR ,PAINTING ,INVISIBLE>
    <FCLEAR ,SWORD ,INVISIBLE>
    <FCLEAR ,MAP ,INVISIBLE>
    <FCLEAR ,GUIDE ,INVISIBLE>
    <FCLEAR ,WRENCH ,INVISIBLE>
    <FCLEAR ,SCREWDRIVER ,INVISIBLE>
    <FCLEAR ,BELL ,INVISIBLE>
    <FCLEAR ,CANDLES ,INVISIBLE>
    <FCLEAR ,BOOK ,INVISIBLE>
    <FCLEAR ,AXE ,INVISIBLE>
    <FCLEAR ,TRIDENT ,INVISIBLE>
    <FCLEAR ,EGG ,INVISIBLE>
    <FCLEAR ,CANARY ,INVISIBLE>
    <SETG SCORE <+ ,BASE-SCORE <OTVAL-FROB>>>
    <SETG CLOCK-WAIT T>
    <TELL "MUSEUM-SETUP:READY" CR>>

<ROUTINE V-MUSEUM-TEST-COMPLETE ()
    <SETG LLD-FLAG T>
    <SETG EGG-SOLVE T>
    <SETG WATER-LEVEL -1>
    <SETG CLOCK-WAIT T>
    <TELL "MUSEUM-SETUP:COMPLETED-FIELD-HISTORY" CR>>

<ROUTINE MUSEUM-TEST-PRINT-BOOL (VALUE)
    <COND (.VALUE <TELL "Y">) (T <TELL "N">)>>

<ROUTINE V-MUSEUM-TEST-REPORT ()
    <MUSEUM-REFRESH-GROUPS>
    <TELL "MUSEUM:VERSION=" N ,MUSEUM-VERSION ";FRAME-PAINT=">
    <MUSEUM-TEST-PRINT-BOOL <IN? ,PAINTING ,MUSEUM-FRAME>>
    <TELL ";WALL-SWORD=">
    <MUSEUM-TEST-PRINT-BOOL <IN? ,SWORD ,MUSEUM-WEAPON-WALL>>
    <TELL ";WALL-AXE=">
    <MUSEUM-TEST-PRINT-BOOL <IN? ,AXE ,MUSEUM-WEAPON-WALL>>
    <TELL ";SHELF-MAP=">
    <MUSEUM-TEST-PRINT-BOOL <IN? ,MAP ,MUSEUM-RECORD-SHELF>>
    <TELL ";SHELF-GUIDE=">
    <MUSEUM-TEST-PRINT-BOOL <IN? ,GUIDE ,MUSEUM-RECORD-SHELF>>
    <TELL ";SHELF-BOOK=">
    <MUSEUM-TEST-PRINT-BOOL <IN? ,BOOK ,MUSEUM-RECORD-SHELF>>
    <TELL ";STAND-WRENCH=">
    <MUSEUM-TEST-PRINT-BOOL <IN? ,WRENCH ,MUSEUM-RELIC-STAND>>
    <TELL ";STAND-DRIVER=">
    <MUSEUM-TEST-PRINT-BOOL <IN? ,SCREWDRIVER ,MUSEUM-RELIC-STAND>>
    <TELL ";STAND-BELL=">
    <MUSEUM-TEST-PRINT-BOOL <IN? ,BELL ,MUSEUM-RELIC-STAND>>
    <TELL ";STAND-CANDLES=">
    <MUSEUM-TEST-PRINT-BOOL <IN? ,CANDLES ,MUSEUM-RELIC-STAND>>
    <TELL ";CASE-TRIDENT=">
    <MUSEUM-TEST-PRINT-BOOL <IN? ,TRIDENT ,TROPHY-CASE>>
    <TELL ";CASE-AUTH=">
    <MUSEUM-TEST-PRINT-BOOL <EQUAL? ,SCORE <+ ,BASE-SCORE <OTVAL-FROB>>>>
    <TELL ";HOUSE=">
    <MUSEUM-TEST-PRINT-BOOL ,MUSEUM-GROUP-HOUSE>
    <TELL ";RITUAL=">
    <MUSEUM-TEST-PRINT-BOOL ,MUSEUM-GROUP-RITUAL>
    <TELL ";DAM=">
    <MUSEUM-TEST-PRINT-BOOL ,MUSEUM-GROUP-DAM>
    <TELL ";CONFLICT=">
    <MUSEUM-TEST-PRINT-BOOL ,MUSEUM-GROUP-CONFLICT>
    <TELL ";THEFT=">
    <MUSEUM-TEST-PRINT-BOOL ,MUSEUM-THEFT-OCCURRED>
    <TELL ";PAINT-THIEF=">
    <MUSEUM-TEST-PRINT-BOOL <IN? ,PAINTING ,THIEF>>
    <TELL ";PAINT-TREASURE-ROOM=">
    <MUSEUM-TEST-PRINT-BOOL <IN? ,PAINTING ,TREASURE-ROOM>>
    <TELL ";EGG-NESTED=">
    <MUSEUM-TEST-PRINT-BOOL <IN? ,CANARY ,EGG>>
    <CRLF>>

<ROUTINE V-MUSEUM-TEST-MUTATE ()
    <MUSEUM-TEST-CLEAR-SURFACE ,MUSEUM-FRAME>
    <MUSEUM-TEST-CLEAR-SURFACE ,MUSEUM-WEAPON-WALL>
    <MUSEUM-TEST-CLEAR-SURFACE ,MUSEUM-RECORD-SHELF>
    <MUSEUM-TEST-CLEAR-SURFACE ,MUSEUM-RELIC-STAND>
    <COND (<IN? ,PAINTING ,THIEF>
           <MOVE ,PAINTING ,GALLERY>
           <FCLEAR ,PAINTING ,INVISIBLE>)>
    <COND (<IN? ,TRIDENT ,TROPHY-CASE> <MOVE ,TRIDENT ,WINNER>)>
    <MUSEUM-TEST-CLEAR-STATE>
    <SETG SCORE <+ ,BASE-SCORE <OTVAL-FROB>>>
    <SETG CLOCK-WAIT T>
    <TELL "MUSEUM:MUTATED" CR>>

<ROUTINE V-MUSEUM-TEST-RECOVER ()
    <GOTO ,TREASURE-ROOM>
    <MOVE ,THIEF ,TREASURE-ROOM>
    <FCLEAR ,THIEF ,INVISIBLE>
    <ROBBER-FUNCTION ,F-DEAD>
    <SETG CLOCK-WAIT T>
    <TELL "MUSEUM:CANONICAL-RECOVERY" CR>
    <V-MUSEUM-TEST-REPORT>>
