"TEST-ONLY RELEASE 1276 MARA FIELD GUIDANCE PRECONDITIONS"

<SYNTAX MFGCLASSIC = V-MFG-CLASSIC-TEST>
<SYNTAX MFGFORGIVING = V-MFG-FORGIVING-TEST>
<SYNTAX MFGEXACTING = V-MFG-EXACTING-TEST>
<SYNTAX MFGCACHE = V-MFG-CACHE-TEST>

<ROUTINE MFG-TEST-RESET ()
    <SETG ALWAYS-LIT T>
    <MARA-ENSURE>
    <MARA-PUT ,MARA-SLOT-MODE ,MARA-MODE-INDEPENDENT>
    <WILDERNESS-PUT ,WB-BRUSH-CLEARED 1>
    <WILDERNESS-PUT ,WB-FOX-TRAIL-SEEN 0>
    <MFG-PUT ,MFG-BRUSH-GATE-SEEN 0>
    <MFG-PUT ,MFG-SWALE-SEEN 0>
    <MFG-PUT ,MFG-BEAVER-SEEN 0>
    <MFG-PUT ,MFG-FOX-RUN-SEEN 0>
    <MFG-PUT ,MFG-WARMWIND-SEEN 0>
    <MFG-PUT ,MFG-OVERLOOK-SEEN 0>
    <MFG-PUT ,MFG-BLOCKED-ROOM 0>
    <MFG-PUT ,MFG-UNCERTAIN-ROOM 0>
    <MFG-PUT ,MFG-CACHE-OBJECT 0>
    <MFG-PUT ,MFG-CACHE-ROOM 0>
    <MFG-PUT ,MFG-FOX-DISCOVERED 0>
    <COND (<LOC ,WILDERNESS-MACHETE> <REMOVE-CAREFULLY ,WILDERNESS-MACHETE>)>
    <GOTO ,FOREST-1>
    <MOVE ,MARA ,FOREST-1>
    <MOVE ,WILDERNESS-MACHETE ,WINNER>
    <MARA-PUT ,MARA-SLOT-DAM-SURVEY 1>
    <MARA-PUT ,MARA-SLOT-MODE ,MARA-MODE-FOLLOWING>
    <STRUCTURAL-DIFFICULTY-PUT ,SD-LOCKED 0>
    <RTRUE>>

<ROUTINE V-MFG-CLASSIC-TEST ()
    <MFG-TEST-RESET>
    <STRUCTURAL-DIFFICULTY-PUT ,SD-MODE ,SD-CLASSIC>
    <TELL "TEST PRECONDITION: Mara and Adventurer share the cleared western forest threshold; Classic guidance cadence; field notebook empty." CR>
    <RTRUE>>

<ROUTINE V-MFG-FORGIVING-TEST ()
    <MFG-TEST-RESET>
    <STRUCTURAL-DIFFICULTY-PUT ,SD-MODE ,SD-FORGIVING>
    <TELL "TEST PRECONDITION: same earned field state; Forgiving changes only Mara's volunteer cadence." CR>
    <RTRUE>>

<ROUTINE V-MFG-EXACTING-TEST ()
    <MFG-TEST-RESET>
    <STRUCTURAL-DIFFICULTY-PUT ,SD-MODE ,SD-EXACTING>
    <TELL "TEST PRECONDITION: same earned field state; Exacting keeps findings private until directly asked." CR>
    <RTRUE>>

<ROUTINE V-MFG-CACHE-TEST ()
    <MFG-TEST-RESET>
    <STRUCTURAL-DIFFICULTY-PUT ,SD-MODE ,SD-CLASSIC>
    <GOTO ,BACKCOUNTRY-HEMLOCK-SWALE>
    <MOVE ,MARA ,BACKCOUNTRY-HEMLOCK-SWALE>
    <MARA-PUT ,MARA-SLOT-MODE ,MARA-MODE-FOLLOWING>
    <TELL "TEST PRECONDITION: Mara and Adventurer stand together in Hemlock Swale; real machete held; no cache memory." CR>
    <RTRUE>>
