"TEST-ONLY TROLL STOLEN-WEAPON PRECONDITIONS"

<SYNTAX TROLLCUSTODY = V-TROLL-CUSTODY-TEST>
<SYNTAX TROLLARMED = V-TROLL-ARMED-TEST>
<SYNTAX TROLLSUBDUE = V-TROLL-SUBDUE-TEST>

<ROUTINE TROLL-CUSTODY-TEST-RESET ()
    <MOVE ,TROLL ,TROLL-ROOM>
    <MOVE ,AXE ,TROLL>
    <FSET ,AXE ,NDESCBIT>
    <FSET ,AXE ,WEAPONBIT>
    <MOVE ,SWORD ,WINNER>
    <FCLEAR ,SWORD ,NDESCBIT>
    <FSET ,SWORD ,WEAPONBIT>
    <MOVE ,LUNCH ,WINNER>
    <MOVE ,LAMP ,WINNER>
    <FSET ,LAMP ,ONBIT>
    <FSET ,TROLL ,FIGHTBIT>
    <PUTP ,TROLL ,P?STRENGTH 2>
    <SETG TROLL-FLAG <>>
    <GOTO ,TROLL-ROOM>
    <RFALSE>>

<ROUTINE V-TROLL-CUSTODY-TEST ()
    <TROLL-CUSTODY-TEST-RESET>
    <TROLL-CAPTURE-WEAPON ,SWORD>
    <TELL "TEST PRECONDITION: canonical sword custody was transferred to the troll through the Release 1254 capture authority." CR>
    <RTRUE>>

<ROUTINE V-TROLL-ARMED-TEST ("AUX" W)
    <SET W <FIND-WEAPON ,TROLL>>
    <TELL "TEST troll preferred weapon: " D .W CR>
    <RTRUE>>

<ROUTINE V-TROLL-SUBDUE-TEST ()
    <TROLL-FCN ,F-UNCONSCIOUS>
    <TELL "TEST PRECONDITION: canonical troll unconsciousness resolved after stolen-weapon custody." CR>
    <RTRUE>>
