"TEST-ONLY LIVING COLLECTION PRECONDITIONS"

<SYNTAX LCSETUP = V-LC-TEST-RESERVOIR>
<SYNTAX LCSOLO = V-LC-TEST-SOLO-SILVER>
<SYNTAX LCHOME = V-LC-TEST-HOME>
<SYNTAX LCTIDE = V-LC-TEST-TIDE>
<SYNTAX LCKITCHEN = V-LC-TEST-KITCHEN>
<SYNTAX LCERRAND = V-LC-TEST-ERRAND>
<SYNTAX LCBANK = V-LC-TEST-BANK>

<ROUTINE V-LC-TEST-RESERVOIR ()
    <LC-ENSURE>
    <SETG LOW-TIDE <>>
    <REMOVE ,DAM-SILVERFIN>
    <REMOVE ,RESERVOIR-CHAR>
    <AQUATIC-PUT ,AQUATIC-SLOT-OBSERVED 0>
    <AQUATIC-PUT ,AQUATIC-SLOT-RELEASED 0>
    <LC-PUT ,LC-SLOT-CHAR-OBS 0>
    <LC-PUT ,LC-SLOT-CHAR-REL 0>
    <LC-PUT ,LC-SLOT-JAR-DEAD 0>
    <LC-PUT ,LC-SLOT-ERRAND 0>
    <LC-PUT ,LC-SLOT-TOLD-SILVER 0>
    <LC-PUT ,LC-SLOT-TOLD-CHAR 0>
    <MOVE ,MUSEUM-FISHING-ROD ,WINNER>
    <MOVE ,MUSEUM-FIELD-JAR ,WINNER>
    <MOVE ,MARA ,RESERVOIR-SOUTH>
    <MARA-PUT ,MARA-SLOT-MET 1>
    <MARA-PUT ,MARA-SLOT-DAM-SURVEY 1>
    <MARA-PUT ,MARA-SLOT-HOUSE-VISITED 1>
    <MARA-PUT ,MARA-SLOT-MODE ,MARA-MODE-FOLLOWING>
    <GOTO ,RESERVOIR-SOUTH>
    <TELL "TEST PRECONDITION: reservoir bank with water, rod, jar, and Mara who has surveyed the Dam." CR>
    <RTRUE>>

<ROUTINE V-LC-TEST-SOLO-SILVER ()
    <LC-ENSURE>
    <SETG LOW-TIDE <>>
    <REMOVE ,DAM-SILVERFIN>
    <AQUATIC-PUT ,AQUATIC-SLOT-OBSERVED 0>
    <AQUATIC-PUT ,AQUATIC-SLOT-RELEASED 0>
    <LC-PUT ,LC-SLOT-TOLD-SILVER 0>
    <MARA-PUT ,MARA-SLOT-FISH-WITNESSED 0>
    <MARA-PUT ,MARA-SLOT-FISH-RELEASED 0>
    <MOVE ,MARA ,LIVING-ROOM>
    <MARA-PUT ,MARA-SLOT-MODE ,MARA-MODE-WAITING>
    <MOVE ,MUSEUM-FISHING-ROD ,WINNER>
    <MOVE ,MUSEUM-FIELD-JAR ,WINNER>
    <GOTO ,DAM-BASE>
    <TELL "TEST PRECONDITION: River Frigid fishing site; Mara waiting in the Living Room, not witnessing." CR>
    <RTRUE>>

<ROUTINE V-LC-TEST-HOME ()
    <GOTO ,LIVING-ROOM>
    <TELL "TEST PRECONDITION: returned physically to the Living Room museum." CR>
    <RTRUE>>

<ROUTINE V-LC-TEST-TIDE ()
    <SETG LOW-TIDE T>
    <MOVE ,MUSEUM-FISHING-ROD ,WINNER>
    <MOVE ,MUSEUM-FIELD-JAR ,WINNER>
    <GOTO ,RESERVOIR-SOUTH>
    <TELL "TEST PRECONDITION: reservoir drawn down to mud." CR>
    <RTRUE>>

<ROUTINE V-LC-TEST-KITCHEN ()
    <MOVE ,MARA ,KITCHEN>
    <MARA-PUT ,MARA-SLOT-HOUSE-VISITED 1>
    <MARA-PUT ,MARA-SLOT-MET 1>
    <GOTO ,KITCHEN>
    <TELL "TEST PRECONDITION: Kitchen with Mara as a person who lives in the House." CR>
    <RTRUE>>

<ROUTINE V-LC-TEST-ERRAND ()
    <LC-ENSURE>
    <SETG LOW-TIDE <>>
    <LC-PUT ,LC-SLOT-JAR-DEAD 0>
    <LC-PUT ,LC-SLOT-ERRAND 0>
    <MOVE ,MUSEUM-FIELD-JAR ,HERE>
    <MOVE ,MARA ,RESERVOIR-SOUTH>
    <MARA-PUT ,MARA-SLOT-DAM-SURVEY 1>
    <MARA-PUT ,MARA-SLOT-MET 1>
    <MARA-PUT ,MARA-SLOT-MODE ,MARA-MODE-WAITING>
    <GOTO ,RESERVOIR-SOUTH>
    <TELL "TEST PRECONDITION: reservoir bank, field jar present, Mara knows the Dam route." CR>
    <RTRUE>>

<ROUTINE V-LC-TEST-BANK ()
    <SETG LOW-TIDE <>>
    <GOTO ,RESERVOIR-SOUTH>
    <TELL "TEST PRECONDITION: standing on the reservoir bank." CR>
    <RTRUE>>
