"Test-only Kitchen positioning, mutation, actor, and reporting verbs for Release 1221 qualification."

<SYNTAX KSETUP = V-KITCHEN-TEST-SETUP>
<SYNTAX KACTORS = V-KITCHEN-TEST-ACTORS>
<SYNTAX KREPORT = V-KITCHEN-TEST-REPORT>
<SYNTAX KMUTATE = V-KITCHEN-TEST-MUTATE>

<ROUTINE KITCHEN-TEST-QUIET-WORLD ()
    <QUEUE I-THIEF 0>
    <SETG THIEF-HERE <>>
    <REMOVE-CAREFULLY ,THIEF>
    <REMOVE-CAREFULLY ,TROLL>
    <REMOVE-CAREFULLY ,BAT>
    <REMOVE-CAREFULLY ,CYCLOPS>
    <SETG TROLL-FLAG T>
    <RTRUE>>

<ROUTINE KITCHEN-TEST-CLEAR-FIXTURE (FIXTURE "AUX" ITEM NEXT)
    <SET ITEM <FIRST? .FIXTURE>>
    <REPEAT ()
        <COND (<NOT .ITEM> <RETURN>)>
        <SET NEXT <NEXT? .ITEM>>
        <MOVE .ITEM ,WINNER>
        <FCLEAR .ITEM ,INVISIBLE>
        <SET ITEM .NEXT>>
    <RTRUE>>

<ROUTINE KITCHEN-TEST-RESET-STATE ()
    <KITCHEN-PUT ,KS-VERSION 1>
    <KITCHEN-PUT ,KS-STOVE-HEAT 0>
    <KITCHEN-PUT ,KS-LUNCH-WARM 0>
    <KITCHEN-PUT ,KS-WATER-WARM 0>
    <KITCHEN-PUT ,KS-GARLIC-WARM 0>
    <KITCHEN-PUT ,KS-SHOVEL-WET 0>
    <KITCHEN-PUT ,KS-WRENCH-WET 0>
    <KITCHEN-PUT ,KS-SCREWDRIVER-WET 0>
    <KITCHEN-PUT ,KS-AXE-WET 0>
    <KITCHEN-PUT ,KS-KNIFE-WET 0>
    <KITCHEN-PUT ,KS-BOTTLE-WET 0>
    <KITCHEN-PUT ,KS-WORKTOP-WET 0>
    <KITCHEN-PUT ,KS-KNIFE-CLEANED <>>
    <KITCHEN-PUT ,KS-BOTTLE-CLEANED <>>
    <KITCHEN-PUT ,KS-LUNCH-PREPARED <>>
    <KITCHEN-PUT ,KS-GARLIC-SLICED <>>
    <KITCHEN-PUT ,KS-WORKTOP-RESIDUE <>>
    <KITCHEN-PUT ,KS-EVENT-WATER <>>
    <KITCHEN-PUT ,KS-EVENT-CLEANING <>>
    <KITCHEN-PUT ,KS-EVENT-HEAT <>>
    <KITCHEN-PUT ,KS-EVENT-FOOD <>>
    <KITCHEN-PUT ,KS-EVENT-EXPERIMENT <>>
    <KITCHEN-PUT ,KS-EVENT-STORAGE <>>
    <KITCHEN-PUT ,KS-EVENT-OFFERING <>>
    <SETG MATERIAL-WRENCH-CLEANED <>>
    <SETG MATERIAL-RUST-WET 0>
    <SETG MATERIAL-RUST-WORSE <>>
    <RTRUE>>

<ROUTINE V-KITCHEN-TEST-SETUP ()
    <KITCHEN-TEST-QUIET-WORLD>
    <GOTO ,KITCHEN>
    <KITCHEN-TEST-CLEAR-FIXTURE ,KITCHEN-SINK>
    <KITCHEN-TEST-CLEAR-FIXTURE ,KITCHEN-WORKTOP>
    <KITCHEN-TEST-CLEAR-FIXTURE ,KITCHEN-CUPBOARD>
    <KITCHEN-TEST-CLEAR-FIXTURE ,KITCHEN-RANGE>
    <KITCHEN-TEST-RESET-STATE>
    <REMOVE-CAREFULLY ,WATER>
    <MOVE ,BOTTLE ,WINNER>
    <MOVE ,LUNCH ,WINNER>
    <MOVE ,GARLIC ,WINNER>
    <MOVE ,KNIFE ,WINNER>
    <MOVE ,WRENCH ,WINNER>
    <MOVE ,RUSTY-KNIFE ,WINNER>
    <MOVE ,TORCH ,WINNER>
    <FSET ,BOTTLE ,OPENBIT>
    <FSET ,TORCH ,ONBIT>
    <FSET ,TORCH ,FLAMEBIT>
    <FCLEAR ,BOTTLE ,INVISIBLE>
    <FCLEAR ,LUNCH ,INVISIBLE>
    <FCLEAR ,GARLIC ,INVISIBLE>
    <FCLEAR ,KNIFE ,INVISIBLE>
    <FCLEAR ,WRENCH ,INVISIBLE>
    <FCLEAR ,RUSTY-KNIFE ,INVISIBLE>
    <FCLEAR ,TORCH ,INVISIBLE>
    <SETG CLOCK-WAIT T>
    <TELL "KITCHEN-SETUP:READY" CR>>

<ROUTINE V-KITCHEN-TEST-ACTORS ()
    <MOVE ,BAT ,KITCHEN>
    <MOVE ,CYCLOPS ,KITCHEN>
    <FCLEAR ,BAT ,INVISIBLE>
    <FCLEAR ,CYCLOPS ,INVISIBLE>
    <SETG CLOCK-WAIT T>
    <TELL "KITCHEN-ACTORS:READY" CR>>

<ROUTINE KITCHEN-TEST-PRINT-BOOL (VALUE)
    <COND (.VALUE <TELL "Y">) (T <TELL "N">)>>

<ROUTINE V-KITCHEN-TEST-REPORT ()
    <TELL "KITCHEN:VERSION=" N <KITCHEN-GET ,KS-VERSION> ";WATER-BOTTLE=">
    <KITCHEN-TEST-PRINT-BOOL <IN? ,WATER ,BOTTLE>>
    <TELL ";KNIFE-CLEAN=">
    <KITCHEN-TEST-PRINT-BOOL <KITCHEN-GET ,KS-KNIFE-CLEANED>>
    <TELL ";KNIFE-WET=">
    <KITCHEN-TEST-PRINT-BOOL <KITCHEN-WET? ,KNIFE>>
    <TELL ";GARLIC-SLICED=">
    <KITCHEN-TEST-PRINT-BOOL <KITCHEN-GET ,KS-GARLIC-SLICED>>
    <TELL ";GARLIC-CUPBOARD=">
    <KITCHEN-TEST-PRINT-BOOL <IN? ,GARLIC ,KITCHEN-CUPBOARD>>
    <TELL ";LUNCH-PREP=">
    <KITCHEN-TEST-PRINT-BOOL <KITCHEN-GET ,KS-LUNCH-PREPARED>>
    <TELL ";LUNCH-CUPBOARD=">
    <KITCHEN-TEST-PRINT-BOOL <IN? ,LUNCH ,KITCHEN-CUPBOARD>>
    <TELL ";WRENCH-CLEAN=">
    <KITCHEN-TEST-PRINT-BOOL ,MATERIAL-WRENCH-CLEANED>
    <TELL ";WRENCH-WET=">
    <KITCHEN-TEST-PRINT-BOOL <KITCHEN-WET? ,WRENCH>>
    <TELL ";RANGE-HOT=">
    <KITCHEN-TEST-PRINT-BOOL <G? <KITCHEN-GET ,KS-STOVE-HEAT> 0>>
    <TELL ";WATER-WARM=">
    <KITCHEN-TEST-PRINT-BOOL <G? <KITCHEN-GET ,KS-WATER-WARM> 0>>
    <TELL ";RESIDUE=">
    <KITCHEN-TEST-PRINT-BOOL <KITCHEN-GET ,KS-WORKTOP-RESIDUE>>
    <TELL ";STORAGE=">
    <KITCHEN-TEST-PRINT-BOOL <KITCHEN-GET ,KS-EVENT-STORAGE>>
    <TELL ";RUST-WORSE=">
    <KITCHEN-TEST-PRINT-BOOL ,MATERIAL-RUST-WORSE>
    <CRLF>>

<ROUTINE V-KITCHEN-TEST-MUTATE ()
    <KITCHEN-TEST-CLEAR-FIXTURE ,KITCHEN-SINK>
    <KITCHEN-TEST-CLEAR-FIXTURE ,KITCHEN-WORKTOP>
    <KITCHEN-TEST-CLEAR-FIXTURE ,KITCHEN-CUPBOARD>
    <KITCHEN-TEST-CLEAR-FIXTURE ,KITCHEN-RANGE>
    <REMOVE-CAREFULLY ,WATER>
    <MOVE ,BOTTLE ,WINNER>
    <MOVE ,LUNCH ,WINNER>
    <MOVE ,GARLIC ,WINNER>
    <MOVE ,KNIFE ,WINNER>
    <MOVE ,WRENCH ,WINNER>
    <KITCHEN-TEST-RESET-STATE>
    <FCLEAR ,KITCHEN-CUPBOARD ,OPENBIT>
    <SETG CLOCK-WAIT T>
    <TELL "KITCHEN:MUTATED" CR>>
