"TEST-ONLY MUSEUM SONGBIRD PRECONDITIONS"

<SYNTAX BIRDREADY = V-MUSEUM-SONGBIRD-TEST-FOREST>
<SYNTAX NESTHIGH = V-MUSEUM-SONGBIRD-TEST-NEST>
<SYNTAX MUSEUMHOME = V-MUSEUM-SONGBIRD-TEST-HOME>

<ROUTINE V-MUSEUM-SONGBIRD-TEST-FOREST ()
    <SETG SING-SONG <>>
    <REMOVE ,BAUBLE>
    <REMOVE ,SONGBIRD-FEATHER>
    <MOVE ,CANARY ,WINNER>
    <GOTO ,PATH>
    <TELL "TEST PRECONDITION: intact canary carried to the forest path; canonical exchange reset." CR>
    <RTRUE>>

<ROUTINE V-MUSEUM-SONGBIRD-TEST-NEST ()
    <GOTO ,UP-A-TREE>
    <TELL "TEST PRECONDITION: climbed to the real branch nest with carried evidence unchanged." CR>
    <RTRUE>>

<ROUTINE V-MUSEUM-SONGBIRD-TEST-HOME ()
    <GOTO ,LIVING-ROOM>
    <TELL "TEST PRECONDITION: returned physically to the Living Room museum." CR>
    <RTRUE>>
