"FLATHEAD FAIR SYNTAX for Release 1310"

;"Parser grammar only. Routines live in flathead_fair.zil / flathead_fair_life.zil.
  BUY/PLAY/RIDE/FISH/DANCE are fair-native. ASK ABOUT reaches vendor knowledge
  without a generic carnival engine."

<SYNTAX BUY OBJECT = V-FAIR-BUY>
<SYNTAX BUY OBJECT FROM OBJECT (FIND ACTORBIT) = V-FAIR-BUY>
<SYNTAX PURCHASE OBJECT = V-FAIR-BUY>
<SYNTAX PLAY OBJECT = V-FAIR-PLAY>
<SYNTAX PLAY OBJECT WITH OBJECT = V-FAIR-PLAY>
<SYNTAX RIDE OBJECT = V-FAIR-RIDE>
<SYNTAX BOARD OBJECT = V-FAIR-RIDE>
<SYNTAX FISH = V-FAIR-FISH>
<SYNTAX FISH IN OBJECT = V-FAIR-FISH>
<SYNTAX DANCE = V-FAIR-DANCE>
<SYNTAX DANCE WITH OBJECT (FIND ACTORBIT) = V-FAIR-DANCE>
<SYNTAX ASK OBJECT (FIND ACTORBIT) ABOUT OBJECT = V-FAIR-ASK>
<SYNTAX REDEEM OBJECT = V-FAIR-REDEEM>
<SYNTAX WEIGH = V-FAIR-WEIGH>
<SYNTAX WEIGH OBJECT = V-FAIR-WEIGH>
<SYNTAX WATCH OBJECT = V-FAIR-WATCH>
