"FLATHEAD FAIR SYNTAX for Release 1310"

;"Parser grammar only. Routines live in flathead_fair.zil / flathead_fair_life.zil.
  Do not redeclare PLAY/BOARD/TELL/ASK: ASK is a TELL synonym, PLAY and BOARD
  already exist. Fair PLAY reaches booth ACTION as V-PLAY; V-PLAY is wrapped
  in flathead_fair_life.zil. ASK ABOUT reaches NPC ACTION as V-TELL."

<SYNTAX BUY OBJECT = V-FAIR-BUY>
<SYNTAX BUY OBJECT FROM OBJECT (FIND ACTORBIT) = V-FAIR-BUY>
<SYNTAX PURCHASE OBJECT = V-FAIR-BUY>
<SYNTAX RIDE OBJECT = V-FAIR-RIDE>
<SYNTAX FISH = V-FAIR-FISH>
<SYNTAX FISH IN OBJECT = V-FAIR-FISH>
<SYNTAX DANCE = V-FAIR-DANCE>
<SYNTAX DANCE WITH OBJECT (FIND ACTORBIT) = V-FAIR-DANCE>
<SYNTAX REDEEM OBJECT = V-FAIR-REDEEM>
<SYNTAX WEIGH = V-FAIR-WEIGH>
<SYNTAX WEIGH OBJECT = V-FAIR-WEIGH>
<SYNTAX WATCH OBJECT = V-FAIR-WATCH>
