"TEST-ONLY CELLAR RECOVERY LOCKER PRECONDITIONS"

<SYNTAX STASHREADY = V-RECOVERY-LOCKER-TEST-READY>
<SYNTAX STASHDIE = V-RECOVERY-LOCKER-TEST-DIE>

<ROUTINE V-RECOVERY-LOCKER-TEST-READY ()
    <SETG WON-FLAG T>
    <EXPEDITION-ENSURE>
    <COND (<NOT <EXPEDITION-HAS? ,ES-SEALED 1>>
           <EXPEDITION-CAPTURE-A>)>
    <COND (<NOT <EXPEDITION-HAS? ,ES-SEALED 2>>
           <EXPEDITION-CAPTURE-B>)>
    <RECOVERY-LOCKER-MATERIALIZE>
    <RECOVERY-LOCKER-PUT ,RLS-SEALED 0>
    <FSET ,EXPEDITION-RECOVERY-LOCKER ,OPENBIT>
    <MOVE ,LAMP ,WINNER>
    <MOVE ,ROPE ,WINNER>
    <MOVE ,GARLIC ,WINNER>
    <GOTO ,CELLAR>
    <TELL "TEST PRECONDITION: Expedition B sealed; lantern, rope, and garlic carried in the Cellar." CR>
    <RTRUE>>

<ROUTINE V-RECOVERY-LOCKER-TEST-DIE ()
    <JIGS-UP "A test-only cave-in ends this expedition.">
    <RTRUE>>
