"Test-only completed-expedition setup, alternate sealed history, corruption, and reporting for Release 1230 qualification."

<SYNTAX EXPRESET = V-EXPEDITION-TEST-RESET>
<SYNTAX EXPVICTORYA = V-EXPEDITION-TEST-A>
<SYNTAX EXPVICTORYB = V-EXPEDITION-TEST-B>
<SYNTAX EXPREPORT = V-EXPEDITION-TEST-REPORT>
<SYNTAX EXPMUTATE = V-EXPEDITION-TEST-MUTATE>

<ROUTINE EXPEDITION-TEST-REMOVE (OBJ)
    <COND (<LOC .OBJ> <REMOVE-CAREFULLY .OBJ>)>
    <RTRUE>>

<ROUTINE EXPEDITION-TEST-CLEAR-TABLE (TABLE MAX "AUX" (I 0))
    <REPEAT ()
        <COND (<G? .I .MAX> <RETURN>)>
        <PUT .TABLE .I 0>
        <SET I <+ .I 1>>>
    <RTRUE>>

<ROUTINE EXPEDITION-TEST-CLEAN ()
    <EXPEDITION-TEST-REMOVE ,EXPEDITION-A-MASTER>
    <EXPEDITION-TEST-REMOVE ,EXPEDITION-A-TIMELINE>
    <EXPEDITION-TEST-REMOVE ,EXPEDITION-A-SUMMARY>
    <EXPEDITION-TEST-REMOVE ,EXPEDITION-B-MASTER>
    <EXPEDITION-TEST-REMOVE ,EXPEDITION-B-TIMELINE>
    <EXPEDITION-TEST-REMOVE ,EXPEDITION-B-SUMMARY>
    <EXPEDITION-TEST-REMOVE ,EXPEDITION-COMPARISON-CARD>
    <EXPEDITION-TEST-REMOVE ,EXPEDITION-EXPORT-PRINTOUT>
    <EXPEDITION-TEST-CLEAR-TABLE ,EXPEDITION-STATE 19>
    <EXPEDITION-TEST-CLEAR-TABLE ,EXPEDITION-A-SEQUENCE 11>
    <EXPEDITION-TEST-CLEAR-TABLE ,EXPEDITION-B-SEQUENCE 11>
    <EXPEDITION-PUT ,ES-VERSION ,EXPEDITION-SCHEMA>
    <SETG WON-FLAG <>>
    <SETG SCORE 0>
    <SETG DEATHS 0>
    <PLAYBACK-PUT ,PB-SLOT-CAPTURED 0>
    <PLAYBACK-PUT ,PB-SLOT-COUNT 0>
    <HOUSE-RISK-PUT ,RV-VERSION ,HOUSE-RISK-SCHEMA>
    <HOUSE-RISK-PUT ,RV-HISTORY 0>
    <HOUSE-RISK-PUT ,RV-REPAIRED 0>
    <HOUSE-RISK-PUT ,RV-SECURITY 0>
    <MOVE ,TORCH ,WINNER>
    <FSET ,TORCH ,ONBIT>
    <GOTO ,ATTIC>
    <SETG CLOCK-WAIT T>
    <RTRUE>>

<ROUTINE V-EXPEDITION-TEST-RESET ()
    <EXPEDITION-TEST-CLEAN>
    <TELL "EXPEDITION-TEST:PRE-VICTORY" CR>>

<ROUTINE EXPEDITION-TEST-PLAYBACK-A ()
    <PLAYBACK-PUT ,PB-SLOT-CAPTURED 3475>
    <PLAYBACK-PUT ,PB-SLOT-COUNT 7>
    <PUT ,PLAYBACK-SEQUENCE 0 ,PB-EVT-HOUSE>
    <PUT ,PLAYBACK-SEQUENCE 1 ,PB-EVT-FOREST>
    <PUT ,PLAYBACK-SEQUENCE 2 ,PB-EVT-TROLL>
    <PUT ,PLAYBACK-SEQUENCE 3 ,PB-EVT-DAM-REPAIR>
    <PUT ,PLAYBACK-SEQUENCE 4 ,PB-EVT-HADES-COMPLETE>
    <PUT ,PLAYBACK-SEQUENCE 5 ,PB-EVT-THIEF>
    <PUT ,PLAYBACK-SEQUENCE 6 ,PB-EVT-SYNTHESIS>
    <RTRUE>>

<ROUTINE EXPEDITION-TEST-PLAYBACK-B ()
    <PLAYBACK-PUT ,PB-SLOT-CAPTURED 1615>
    <PLAYBACK-PUT ,PB-SLOT-COUNT 7>
    <PUT ,PLAYBACK-SEQUENCE 0 ,PB-EVT-HOUSE>
    <PUT ,PLAYBACK-SEQUENCE 1 ,PB-EVT-FOREST>
    <PUT ,PLAYBACK-SEQUENCE 2 ,PB-EVT-DAM-DIAG>
    <PUT ,PLAYBACK-SEQUENCE 3 ,PB-EVT-DAM-FAIL>
    <PUT ,PLAYBACK-SEQUENCE 4 ,PB-EVT-HADES-WRONG>
    <PUT ,PLAYBACK-SEQUENCE 5 ,PB-EVT-CYCLOPS>
    <PUT ,PLAYBACK-SEQUENCE 6 ,PB-EVT-THIEF>
    <RTRUE>>

<ROUTINE V-EXPEDITION-TEST-A ()
    <SETG WON-FLAG T>
    <SETG SCORE 350>
    <SETG DEATHS 1>
    <EXPEDITION-TEST-PLAYBACK-A>
    <HOUSE-RISK-PUT ,RV-HISTORY 127>
    <HOUSE-RISK-PUT ,RV-REPAIRED 119>
    <HOUSE-RISK-PUT ,RV-SECURITY 1>
    <FCLEAR ,KITCHEN-WINDOW ,OPENBIT>
    <FCLEAR ,TRAP-DOOR ,OPENBIT>
    <FCLEAR ,TROPHY-CASE ,OPENBIT>
    <GOTO ,ATTIC>
    <SETG CLOCK-WAIT T>
    <TELL "EXPEDITION-TEST:VICTORY-A" CR>>

<ROUTINE V-EXPEDITION-TEST-B ()
    <SETG WON-FLAG T>
    <SETG SCORE 340>
    <SETG DEATHS 2>
    <EXPEDITION-TEST-PLAYBACK-B>
    <HOUSE-RISK-PUT ,RV-HISTORY 63>
    <HOUSE-RISK-PUT ,RV-REPAIRED 55>
    <HOUSE-RISK-PUT ,RV-SECURITY 0>
    <FSET ,KITCHEN-WINDOW ,OPENBIT>
    <GOTO ,ATTIC>
    <SETG CLOCK-WAIT T>
    <TELL "EXPEDITION-TEST:VICTORY-B" CR>>

<ROUTINE EXPEDITION-TEST-YES-NO (VALUE)
    <COND (.VALUE <TELL "Y">) (T <TELL "N">)>
    <RTRUE>>

<ROUTINE V-EXPEDITION-TEST-REPORT ()
    <TELL "EXPEDITION:VERSION=" N <EXPEDITION-GET ,ES-VERSION>
          ";SEALED=" N <EXPEDITION-GET ,ES-SEALED>
          ";EXPORTED=" N <EXPEDITION-GET ,ES-EXPORTED>
          ";LAST=" N <EXPEDITION-GET ,ES-LAST-BOX>
          ";A-SCORE=" N <EXPEDITION-GET ,ES-A-SCORE>
          ";A-DEATHS=" N <EXPEDITION-GET ,ES-A-DEATHS>
          ";A-PLAYBACK=" N <EXPEDITION-GET ,ES-A-PLAYBACK>
          ";A-RISK=" N <EXPEDITION-GET ,ES-A-RISK>
          ";A-REPAIRED=" N <EXPEDITION-GET ,ES-A-REPAIRED>
          ";A-SECURITY=" N <EXPEDITION-GET ,ES-A-SECURITY>
          ";B-SCORE=" N <EXPEDITION-GET ,ES-B-SCORE>
          ";B-DEATHS=" N <EXPEDITION-GET ,ES-B-DEATHS>
          ";B-PLAYBACK=" N <EXPEDITION-GET ,ES-B-PLAYBACK>
          ";B-RISK=" N <EXPEDITION-GET ,ES-B-RISK>
          ";B-REPAIRED=" N <EXPEDITION-GET ,ES-B-REPAIRED>
          ";B-SECURITY=" N <EXPEDITION-GET ,ES-B-SECURITY>
          ";A-BOX=">
    <EXPEDITION-TEST-YES-NO <EQUAL? <LOC ,EXPEDITION-A-MASTER> ,EXPEDITION-BOX-A>>
    <TELL ";B-BOX=">
    <EXPEDITION-TEST-YES-NO <EQUAL? <LOC ,EXPEDITION-B-MASTER> ,EXPEDITION-BOX-B>>
    <TELL ";COMPARE-CARD=">
    <EXPEDITION-TEST-YES-NO <EQUAL? <LOC ,EXPEDITION-COMPARISON-CARD> ,ARCHIVE-CABINET>>
    <TELL ";EXPORT=">
    <EXPEDITION-TEST-YES-NO <EQUAL? <LOC ,EXPEDITION-EXPORT-PRINTOUT> ,ARCHIVE-CABINET>>
    <CRLF>
    <SETG CLOCK-WAIT T>>

<ROUTINE V-EXPEDITION-TEST-MUTATE ()
    <EXPEDITION-TEST-REMOVE ,EXPEDITION-A-MASTER>
    <EXPEDITION-TEST-REMOVE ,EXPEDITION-A-TIMELINE>
    <EXPEDITION-TEST-REMOVE ,EXPEDITION-A-SUMMARY>
    <EXPEDITION-TEST-REMOVE ,EXPEDITION-B-MASTER>
    <EXPEDITION-TEST-REMOVE ,EXPEDITION-B-TIMELINE>
    <EXPEDITION-TEST-REMOVE ,EXPEDITION-B-SUMMARY>
    <EXPEDITION-TEST-REMOVE ,EXPEDITION-COMPARISON-CARD>
    <EXPEDITION-TEST-REMOVE ,EXPEDITION-EXPORT-PRINTOUT>
    <EXPEDITION-TEST-CLEAR-TABLE ,EXPEDITION-STATE 19>
    <EXPEDITION-TEST-CLEAR-TABLE ,EXPEDITION-A-SEQUENCE 11>
    <EXPEDITION-TEST-CLEAR-TABLE ,EXPEDITION-B-SEQUENCE 11>
    <SETG WON-FLAG <>>
    <SETG SCORE 7>
    <SETG DEATHS 0>
    <GOTO ,NORTH-OF-HOUSE>
    <SETG CLOCK-WAIT T>
    <TELL "EXPEDITION:MUTATED" CR>
    <V-EXPEDITION-TEST-REPORT>>
