"TEST-ONLY RELEASE 1277 PRODUCT PRECONDITIONS"

<SYNTAX RUGSET = V-R1277-RUG-TEST>
<SYNONYM RUGSET R1277RUG>
<SYNTAX TABLESET = V-R1277-PROMISE-TEST>
<SYNONYM TABLESET R1277PROMISE>
<SYNTAX PHOTOSET = V-R1277-PHOTO-TEST>
<SYNONYM PHOTOSET R1277PHOTO>
<SYNTAX COFFEESET = V-R1277-COFFEE-TEST>
<SYNONYM COFFEESET R1277COFFEE>
<SYNTAX HIVESET = V-R1277-HIVE-TEST>
<SYNONYM HIVESET R1277HIVE>

<ROUTINE R1277-TEST-RESET (ROOM)
    <SETG ALWAYS-LIT T>
    <MARA-RESET-STATE>
    <MARA-PUT ,MARA-SLOT-MET 1>
    <MARA-PUT ,MARA-SLOT-MODE ,MARA-MODE-FOLLOWING>
    <R1277-PUT ,R1277-SLOT-EXPOSURES 0>
    <R1277-PUT ,R1277-SLOT-RUG-CUT 0>
    <R1277-PUT ,R1277-SLOT-MARA-HELPING 0>
    <R1277-PUT ,R1277-SLOT-MARA-PROMISE 0>
    <R1277-PUT ,R1277-SLOT-MARA-HELPED-CARPET 0>
    <R1277-PUT ,R1277-SLOT-COFFEE-START 0>
    <R1277-HOUSE-PUT ,R1277-HS-PROMISE-NOTED 0>
    <SETG RUG-MOVED <>>
    <FCLEAR ,RUG ,RMUNGBIT>
    <FSET ,TRAP-DOOR ,INVISIBLE>
    <COND (<LOC ,R1277-RUG-PIECE-ONE> <REMOVE-CAREFULLY ,R1277-RUG-PIECE-ONE>)>
    <COND (<LOC ,R1277-RUG-PIECE-TWO> <REMOVE-CAREFULLY ,R1277-RUG-PIECE-TWO>)>
    <COND (<LOC ,R1277-RUG-PIECE-THREE> <REMOVE-CAREFULLY ,R1277-RUG-PIECE-THREE>)>
    <COND (<LOC ,R1277-PHOTO-ONE> <REMOVE-CAREFULLY ,R1277-PHOTO-ONE>)>
    <COND (<LOC ,R1277-PHOTO-TWO> <REMOVE-CAREFULLY ,R1277-PHOTO-TWO>)>
    <COND (<LOC ,R1277-PHOTO-THREE> <REMOVE-CAREFULLY ,R1277-PHOTO-THREE>)>
    <GOTO .ROOM>
    <MOVE ,MARA .ROOM>
    <RTRUE>>

<ROUTINE V-R1277-RUG-TEST ()
    <R1277-TEST-RESET ,LIVING-ROOM>
    <MOVE ,RUG ,LIVING-ROOM>
    <TELL "TEST PRECONDITION: Mara and Adventurer share the Living Room with the one canonical oriental carpet; cooperation state is clean." CR>
    <RTRUE>>

<ROUTINE V-R1277-PROMISE-TEST ()
    <R1277-TEST-RESET ,LIVING-ROOM>
    <MOVE ,KITCHEN-TABLE ,KITCHEN>
    <MOVE ,SANDWICH-BAG ,KITCHEN-TABLE>
    <TELL "TEST PRECONDITION: Mara and Adventurer share the Living Room; the real loaded kitchen table remains in the Kitchen; no deferred hauling promise exists." CR>
    <RTRUE>>

<ROUTINE V-R1277-PHOTO-TEST ()
    <R1277-TEST-RESET ,LIVING-ROOM>
    <MOVE ,RUG ,LIVING-ROOM>
    <MOVE ,R1277-INSTANT-CAMERA ,ADVENTURER>
    <TELL "TEST PRECONDITION: Mara, Adventurer, and the whole rug share the Living Room; the instant camera is held with all three exposures unused." CR>
    <RTRUE>>

<ROUTINE V-R1277-COFFEE-TEST ()
    <R1277-TEST-RESET ,DEEP-CANYON>
    <MOVE ,R1277-HOT-COFFEE ,DEEP-CANYON>
    <TELL "TEST PRECONDITION: Adventurer stands by the freshly encountered coffee in Deep Canyon; its cooling clock has not started." CR>
    <RTRUE>>

<ROUTINE V-R1277-HIVE-TEST ()
    <R1277-TEST-RESET ,BACKCOUNTRY-BEAVER-MEADOW>
    <MOVE ,R1277-BEEHIVE ,BACKCOUNTRY-BEAVER-MEADOW>
    <TELL "TEST PRECONDITION: Adventurer stands beside the living beehive at Beaver Meadow; the colony is physically present and undisturbed." CR>
    <RTRUE>>
