"Test-only setup and positioning verbs for Release 1215 qualification."

<SYNTAX DAMRESET = V-DAM-MECH-TEST-RESET>
<SYNTAX DAMTOP = V-DAM-MECH-TEST-TOP>
<SYNTAX DAMMAINT = V-DAM-MECH-TEST-MAINT>

<ROUTINE DAM-MECH-TEST-CLEAR-DISCOVERY ()
	<SETG DAM-MECH-PANEL-DIAGNOSED <>>
	<SETG DAM-MECH-INTERLOCK-SEEN <>>
	<SETG DAM-MECH-BOLT-ATTEMPTED <>>
	<SETG DAM-MECH-GATES-CYCLED <>>
	<SETG DAM-MECH-LIGHTS-TOGGLED <>>
	<SETG DAM-MECH-LEAK-TRIGGERED <>>
	<SETG DAM-MECH-LEAK-REPAIRED <>>
	<SETG DAM-MECH-TOOL-PROBED <>>
	<RTRUE>>

<ROUTINE V-DAM-MECH-TEST-RESET ()
	<QUEUE I-RFILL 0>
	<QUEUE I-REMPTY 0>
	<QUEUE I-MAINT-ROOM 0>
	<SETG GATE-FLAG <>>
	<SETG GATES-OPEN <>>
	<SETG LOW-TIDE <>>
	<SETG WATER-LEVEL 0>
	<SETG SHADOW-MELZAR-KNOWN T>
	<FSET ,LEAK ,INVISIBLE>
	<FSET ,MAINTENANCE-ROOM ,ONBIT>
	<MOVE ,WRENCH ,WINNER>
	<MOVE ,SCREWDRIVER ,WINNER>
	<MOVE ,GUIDE ,WINNER>
	<MOVE ,PUTTY ,WINNER>
	<MOVE ,BOTTLE ,WINNER>
	<MOVE ,WATER ,BOTTLE>
	<FSET ,BOTTLE ,OPENBIT>
	<DAM-MECH-TEST-CLEAR-DISCOVERY>
	<GOTO ,MAINTENANCE-ROOM>
	<TELL "[Test-only dam mechanism state reset at the maintenance controls.]" CR>>

<ROUTINE V-DAM-MECH-TEST-TOP ()
	<GOTO ,DAM-ROOM>
	<TELL "[Test-only movement to the top of Flood Control Dam #3.]" CR>>

<ROUTINE V-DAM-MECH-TEST-MAINT ()
	<GOTO ,MAINTENANCE-ROOM>
	<TELL "[Test-only movement to the maintenance controls.]" CR>>
