"Test-only removal of live intrusion causes before proving real-water evidence cleanup."

<SYNTAX CCLEAR = V-CELLAR-TEST-CLEAR-INTRUDERS>

<ROUTINE V-CELLAR-TEST-CLEAR-INTRUDERS ()
    <REMOVE-CAREFULLY ,THIEF>
    <REMOVE-CAREFULLY ,BAT>
    <REMOVE-CAREFULLY ,HOT-BELL>
    <REMOVE-CAREFULLY ,WATER>
    <FCLEAR ,TORCH ,ONBIT>
    <FCLEAR ,TORCH ,FLAMEBIT>
    <SETG CLOCK-WAIT T>
    <TELL "CELLAR-INTRUSION:CLEARED" CR>>
