"Test-only Cellar positioning, intrusion, water, mutation, and reporting verbs for Release 1222 qualification."

<SYNTAX CSETUP = V-CELLAR-TEST-SETUP>
<SYNTAX CINTRUDE = V-CELLAR-TEST-INTRUDE>
<SYNTAX CWATER = V-CELLAR-TEST-WATER>
<SYNTAX CREPORT = V-CELLAR-TEST-REPORT>
<SYNTAX CMUTATE = V-CELLAR-TEST-MUTATE>

<ROUTINE CELLAR-TEST-QUIET-WORLD ()
    <QUEUE I-THIEF 0>
    <SETG THIEF-HERE <>>
    <REMOVE-CAREFULLY ,THIEF>
    <REMOVE-CAREFULLY ,TROLL>
    <REMOVE-CAREFULLY ,BAT>
    <SETG TROLL-FLAG T>
    <RTRUE>>

<ROUTINE CELLAR-TEST-CLEAR-FIXTURE (FIXTURE "AUX" ITEM NEXT)
    <SET ITEM <FIRST? .FIXTURE>>
    <REPEAT ()
        <COND (<NOT .ITEM> <RETURN>)>
        <SET NEXT <NEXT? .ITEM>>
        <MOVE .ITEM ,WINNER>
        <FCLEAR .ITEM ,INVISIBLE>
        <SET ITEM .NEXT>>
    <RTRUE>>

<ROUTINE CELLAR-TEST-RESET-STATE ("AUX" SLOT)
    <SET SLOT 0>
    <REPEAT ()
        <COND (<G? .SLOT ,CS-EVENT-READINESS> <RETURN>)>
        <CELLAR-PUT .SLOT 0>
        <SET SLOT <+ .SLOT 1>>>
    <CELLAR-PUT ,CS-VERSION 1>
    <FSET ,CELLAR-THRESHOLD-MARKS ,INVISIBLE>
    <RTRUE>>

<ROUTINE V-CELLAR-TEST-SETUP ()
    <CELLAR-TEST-QUIET-WORLD>
    <GOTO ,LIVING-ROOM>
    <CELLAR-TEST-CLEAR-FIXTURE ,CELLAR-STAGING-BENCH>
    <CELLAR-TEST-CLEAR-FIXTURE ,CELLAR-GEAR-HOOKS>
    <CELLAR-TEST-CLEAR-FIXTURE ,CELLAR-QUARANTINE-NICHE>
    <CELLAR-TEST-RESET-STATE>
    <REMOVE-CAREFULLY ,WATER>
    <MOVE ,BOTTLE ,WINNER>
    <MOVE ,WATER ,BOTTLE>
    <MOVE ,LAMP ,WINNER>
    <MOVE ,TORCH ,WINNER>
    <MOVE ,ROPE ,WINNER>
    <MOVE ,WRENCH ,WINNER>
    <MOVE ,BOOK ,WINNER>
    <MOVE ,RUSTY-KNIFE ,WINNER>
    <FSET ,BOTTLE ,OPENBIT>
    <FSET ,LAMP ,ONBIT>
    <FSET ,TORCH ,ONBIT>
    <FSET ,TORCH ,FLAMEBIT>
    <FSET ,CELLAR-QUARANTINE-NICHE ,OPENBIT>
    <FSET ,TRAP-DOOR ,OPENBIT>
    <FCLEAR ,TRAP-DOOR ,TOUCHBIT>
    <SETG RUG-MOVED T>
    <SETG MATERIAL-RUST-WET 3>
    <KITCHEN-SET-WET ,RUSTY-KNIFE 3>
    <FCLEAR ,BOTTLE ,INVISIBLE>
    <FCLEAR ,LAMP ,INVISIBLE>
    <FCLEAR ,TORCH ,INVISIBLE>
    <FCLEAR ,ROPE ,INVISIBLE>
    <FCLEAR ,WRENCH ,INVISIBLE>
    <FCLEAR ,BOOK ,INVISIBLE>
    <FCLEAR ,RUSTY-KNIFE ,INVISIBLE>
    <SETG CLOCK-WAIT T>
    <TELL "CELLAR-SETUP:READY" CR>>

<ROUTINE V-CELLAR-TEST-INTRUDE ()
    <MOVE ,THIEF ,CELLAR>
    <MOVE ,BAT ,CELLAR>
    <MOVE ,WATER ,CELLAR>
    <MOVE ,HOT-BELL ,CELLAR>
    <FCLEAR ,THIEF ,INVISIBLE>
    <FCLEAR ,BAT ,INVISIBLE>
    <FCLEAR ,WATER ,INVISIBLE>
    <FCLEAR ,HOT-BELL ,INVISIBLE>
    <CELLAR-INTRUSION-SCAN>
    <SETG CLOCK-WAIT T>
    <TELL "CELLAR-INTRUSION:READY" CR>>

<ROUTINE V-CELLAR-TEST-WATER ()
    <MOVE ,BOTTLE ,WINNER>
    <MOVE ,WATER ,BOTTLE>
    <FSET ,BOTTLE ,OPENBIT>
    <FCLEAR ,BOTTLE ,INVISIBLE>
    <FCLEAR ,WATER ,INVISIBLE>
    <SETG CLOCK-WAIT T>
    <TELL "CELLAR-WATER:READY" CR>>

<ROUTINE CELLAR-TEST-PRINT-BOOL (VALUE)
    <COND (.VALUE <TELL "Y">) (T <TELL "N">)>>

<ROUTINE V-CELLAR-TEST-REPORT ()
    <TELL "CELLAR:VERSION=" N <CELLAR-GET ,CS-VERSION>
          ";DESCENTS=" N <CELLAR-GET ,CS-DESCENTS>
          ";RETURNS=" N <CELLAR-GET ,CS-RETURNS>
          ";SENSE=" N <CELLAR-GET ,CS-SENSE-BITS>
          ";HAZARDS=" N <CELLAR-GET ,CS-HAZARD-BITS>
          ";INTRUSIONS=" N <CELLAR-GET ,CS-INTRUSION-BITS>
          ";ROPE-HOOKS=">
    <CELLAR-TEST-PRINT-BOOL <CELLAR-WITHIN? ,ROPE ,CELLAR-GEAR-HOOKS>>
    <TELL ";WRENCH-BENCH=">
    <CELLAR-TEST-PRINT-BOOL <CELLAR-WITHIN? ,WRENCH ,CELLAR-STAGING-BENCH>>
    <TELL ";BOOK-NICHE=">
    <CELLAR-TEST-PRINT-BOOL <CELLAR-WITHIN? ,BOOK ,CELLAR-QUARANTINE-NICHE>>
    <TELL ";NICHE-CLOSED=">
    <CELLAR-TEST-PRINT-BOOL <NOT <FSET? ,CELLAR-QUARANTINE-NICHE ,OPENBIT>>>
    <TELL ";MARKS=">
    <CELLAR-TEST-PRINT-BOOL <NOT <FSET? ,CELLAR-THRESHOLD-MARKS ,INVISIBLE>>>
    <TELL ";TRAP-BARRED=">
    <CELLAR-TEST-PRINT-BOOL <AND <NOT <FSET? ,TRAP-DOOR ,OPENBIT>>
                                   <FSET? ,TRAP-DOOR ,TOUCHBIT>>>
    <TELL ";WATER-BOTTLE=">
    <CELLAR-TEST-PRINT-BOOL <IN? ,WATER ,BOTTLE>>
    <CRLF>>

<ROUTINE V-CELLAR-TEST-MUTATE ("AUX" SLOT)
    <CELLAR-TEST-CLEAR-FIXTURE ,CELLAR-STAGING-BENCH>
    <CELLAR-TEST-CLEAR-FIXTURE ,CELLAR-GEAR-HOOKS>
    <CELLAR-TEST-CLEAR-FIXTURE ,CELLAR-QUARANTINE-NICHE>
    <SET SLOT 0>
    <REPEAT ()
        <COND (<G? .SLOT ,CS-EVENT-READINESS> <RETURN>)>
        <CELLAR-PUT .SLOT 0>
        <SET SLOT <+ .SLOT 1>>>
    <CELLAR-PUT ,CS-VERSION 1>
    <FSET ,CELLAR-THRESHOLD-MARKS ,INVISIBLE>
    <FSET ,CELLAR-QUARANTINE-NICHE ,OPENBIT>
    <FSET ,TRAP-DOOR ,OPENBIT>
    <FCLEAR ,TRAP-DOOR ,TOUCHBIT>
    <MOVE ,BOTTLE ,WINNER>
    <REMOVE-CAREFULLY ,WATER>
    <REMOVE-CAREFULLY ,THIEF>
    <REMOVE-CAREFULLY ,BAT>
    <REMOVE-CAREFULLY ,HOT-BELL>
    <SETG CLOCK-WAIT T>
    <TELL "CELLAR:MUTATED" CR>>
