"Test-only setup and positioning verbs for Release 1216 qualification."

<SYNTAX RITUALRESET = V-RITUAL-TEST-RESET>
<SYNTAX RITUALTEMPLE = V-RITUAL-TEST-TEMPLE>
<SYNTAX RITUALHADES = V-RITUAL-TEST-HADES>
<SYNTAX RITUALMIRROR = V-RITUAL-TEST-MIRROR>

<ROUTINE RITUAL-TEST-CLEAR-DISCOVERY ()
	<SETG RITUAL-CEREMONY-KNOWN <>>
	<SETG RITUAL-BELL-RESONANCE-HEARD <>>
	<SETG RITUAL-BELL-ANSWERED <>>
	<SETG RITUAL-CANDLES-ANSWERED <>>
	<SETG RITUAL-PRAYER-COMPLETED <>>
	<SETG RITUAL-MIRROR-RESONANCE <>>
	<SETG RITUAL-HOT-BELL-COOLED <>>
	<SETG RITUAL-WRONG-ORDER-SEEN <>>
	<RTRUE>>

<ROUTINE V-RITUAL-TEST-RESET ()
	<QUEUE I-XB 0>
	<QUEUE I-XC 0>
	<QUEUE I-XBH 0>
	<QUEUE I-CANDLES 0>
	<QUEUE I-MATCH 0>
	<QUEUE I-THIEF 0>
	<SETG THIEF-HERE <>>
	<REMOVE-CAREFULLY ,THIEF>
	<SETG XB <>>
	<SETG XC <>>
	<SETG LLD-FLAG <>>
	<SETG MATCH-COUNT 6>
	<REMOVE-CAREFULLY ,HOT-BELL>
	<MOVE ,GHOSTS ,ENTRANCE-TO-HADES>
	<MOVE ,BELL ,WINNER>
	<MOVE ,BOOK ,WINNER>
	<MOVE ,CANDLES ,WINNER>
	<FCLEAR ,CANDLES ,ONBIT>
	<FCLEAR ,CANDLES ,RMUNGBIT>
	<FCLEAR ,CANDLES ,TOUCHBIT>
	<MOVE ,MATCH ,WINNER>
	<FCLEAR ,MATCH ,ONBIT>
	<FCLEAR ,MATCH ,FLAMEBIT>
	<MOVE ,BOTTLE ,WINNER>
	<MOVE ,WATER ,BOTTLE>
	<FSET ,BOTTLE ,OPENBIT>
	<MOVE ,LAMP ,WINNER>
	<FSET ,LAMP ,ONBIT>
	<RITUAL-TEST-CLEAR-DISCOVERY>
	<GOTO ,SOUTH-TEMPLE>
	<TELL "[Test-only ritual state reset with the real bell, book, candles, match, and bottled water.]" CR>>

<ROUTINE V-RITUAL-TEST-TEMPLE ()
	<GOTO ,SOUTH-TEMPLE>
	<TELL "[Test-only movement to the South Temple altar.]" CR>>

<ROUTINE V-RITUAL-TEST-HADES ()
	<GOTO ,ENTRANCE-TO-HADES>
	<TELL "[Test-only movement to the canonical exorcism gateway.]" CR>>

<ROUTINE V-RITUAL-TEST-MIRROR ()
	<GOTO ,MIRROR-ROOM-1>
	<TELL "[Test-only movement to the first enormous mirror.]" CR>>
