"Test-only setup, refill, positioning, mutation, and state-report verbs for Release 1217 qualification."

<SYNTAX MRESET = V-MATERIAL-TEST-RESET>
<SYNTAX MSURF = V-MATERIAL-TEST-SURFACE>
<SYNTAX MANCH = V-MATERIAL-TEST-ANCHOR>
<SYNTAX MTOOLS = V-MATERIAL-TEST-TOOLS>
<SYNTAX MNEST = V-MATERIAL-TEST-NEST>
<SYNTAX MREFIL = V-MATERIAL-TEST-REFILL>
<SYNTAX MREPORT = V-MATERIAL-TEST-REPORT>
<SYNTAX MPSTART = V-MATERIAL-PERSIST-START>
<SYNTAX MPPATH = V-MATERIAL-PERSIST-PATH>
<SYNTAX MPTREE = V-MATERIAL-PERSIST-TREE>
<SYNTAX MPMUTATE = V-MATERIAL-PERSIST-MUTATE>
<SYNTAX MPREPORT = V-MATERIAL-PERSIST-REPORT>

<ROUTINE MATERIAL-TEST-CLEAR ()
	<SETG MATERIAL-ROPE-ANCHOR <>>
	<SETG MATERIAL-SACK-CINCHED <>>
	<SETG MATERIAL-NEST-WET 0>
	<SETG MATERIAL-SHOVEL-CLEANED <>>
	<SETG MATERIAL-WRENCH-CLEANED <>>
	<SETG MATERIAL-SCREWDRIVER-CLEANED <>>
	<SETG MATERIAL-AXE-CLEANED <>>
	<SETG MATERIAL-RUST-WET 0>
	<SETG MATERIAL-RUST-WORSE <>>
	<SETG MATERIAL-BOARDS-PRIED <>>
	<SETG MATERIAL-BOARDS-HARDWARE-KNOWN <>>
	<SETG SURFACE-BOARDS-SCARRED <>>
	<SETG GLULX-ALT-SACK-PREPARED <>>
	<SETG GLULX-ALT-NEST-BURNED <>>
	<SETG GLULX-ALT-EGG-CAUGHT <>>
	<REMOVE-CAREFULLY ,HOUSE-SPLINTER>
	<RTRUE>>

<ROUTINE MATERIAL-TEST-QUIET-WORLD ()
	<QUEUE I-THIEF 0>
	<SETG THIEF-HERE <>>
	<REMOVE-CAREFULLY ,THIEF>
	<MOVE ,LAMP ,WINNER>
	<FSET ,LAMP ,ONBIT>
	<RTRUE>>

<ROUTINE MATERIAL-TEST-WATER ()
	<MOVE ,BOTTLE ,WINNER>
	<MOVE ,WATER ,BOTTLE>
	<FSET ,BOTTLE ,OPENBIT>
	<RTRUE>>

<ROUTINE MATERIAL-TEST-EGG ()
	<REMOVE-CAREFULLY ,BROKEN-EGG>
	<MOVE ,CANARY ,EGG>
	<MOVE ,NEST ,UP-A-TREE>
	<MOVE ,EGG ,NEST>
	<RTRUE>>

<ROUTINE V-MATERIAL-TEST-RESET ()
	<MATERIAL-TEST-CLEAR>
	<MATERIAL-TEST-QUIET-WORLD>
	<MATERIAL-TEST-EGG>
	<MOVE ,ROPE ,WINNER>
	<MOVE ,SANDWICH-BAG ,WINNER>
	<FSET ,SANDWICH-BAG ,OPENBIT>
	<MATERIAL-TEST-WATER>
	<GOTO ,PATH>
	<SETG CLOCK-WAIT T>
	<TELL "MATERIAL-SETUP:RESET" CR>>

<ROUTINE V-MATERIAL-TEST-SURFACE ()
	<MATERIAL-TEST-CLEAR>
	<MATERIAL-TEST-QUIET-WORLD>
	<MOVE ,SHOVEL ,WINNER>
	<MOVE ,SCREWDRIVER ,WINNER>
	<MOVE ,WRENCH ,WINNER>
	<GOTO ,WEST-OF-HOUSE>
	<SETG CLOCK-WAIT T>
	<TELL "MATERIAL-SETUP:SURFACE" CR>>

<ROUTINE V-MATERIAL-TEST-ANCHOR ()
	<MATERIAL-TEST-CLEAR>
	<MATERIAL-TEST-QUIET-WORLD>
	<MOVE ,RAILING ,PATH>
	<MOVE ,ROPE ,WINNER>
	<MOVE ,SANDWICH-BAG ,WINNER>
	<FCLEAR ,SANDWICH-BAG ,OPENBIT>
	<GOTO ,PATH>
	<SETG CLOCK-WAIT T>
	<TELL "MATERIAL-SETUP:ANCHOR" CR>>

<ROUTINE V-MATERIAL-TEST-TOOLS ()
	<MATERIAL-TEST-CLEAR>
	<MATERIAL-TEST-QUIET-WORLD>
	<MOVE ,SHOVEL ,WINNER>
	<MOVE ,WRENCH ,WINNER>
	<MOVE ,SCREWDRIVER ,WINNER>
	<MOVE ,AXE ,WINNER>
	<MOVE ,RUSTY-KNIFE ,WINNER>
	<MATERIAL-TEST-WATER>
	<GOTO ,PATH>
	<SETG CLOCK-WAIT T>
	<TELL "MATERIAL-SETUP:TOOLS" CR>>

<ROUTINE V-MATERIAL-TEST-NEST ()
	<MATERIAL-TEST-CLEAR>
	<MATERIAL-TEST-QUIET-WORLD>
	<MATERIAL-TEST-EGG>
	<MOVE ,TORCH ,WINNER>
	<FSET ,TORCH ,ONBIT>
	<FSET ,TORCH ,FLAMEBIT>
	<MATERIAL-TEST-WATER>
	<GOTO ,UP-A-TREE>
	<SETG CLOCK-WAIT T>
	<TELL "MATERIAL-SETUP:NEST" CR>>

<ROUTINE V-MATERIAL-TEST-REFILL ()
	<MATERIAL-TEST-WATER>
	<SETG CLOCK-WAIT T>
	<TELL "MATERIAL-SETUP:REFILL" CR>>

<ROUTINE V-MATERIAL-TEST-REPORT ()
	<TELL "MATERIAL-REPORT:ROPE=">
	<COND (,MATERIAL-SACK-CINCHED <TELL "SACK-CINCHED">)
	      (,MATERIAL-ROPE-ANCHOR <TELL "ANCHORED">)
	      (T <TELL "FREE">)>
	<TELL ";BOARDS=">
	<COND (,MATERIAL-BOARDS-PRIED <TELL "PRIED">)
	      (,MATERIAL-BOARDS-HARDWARE-KNOWN <TELL "DIAGNOSED">)
	      (T <TELL "UNTESTED">)>
	<TELL ";SHOVEL=">
	<COND (,MATERIAL-SHOVEL-CLEANED <TELL "CLEAN">)
	      (T <TELL "DIRTY">)>
	<TELL ";RUST=">
	<COND (,MATERIAL-RUST-WORSE <TELL "WORSE">)
	      (<G? ,MATERIAL-RUST-WET 0> <TELL "WET">)
	      (T <TELL "OLD">)>
	<TELL ";NEST=">
	<COND (<G? ,MATERIAL-NEST-WET 0> <TELL "WET">)
	      (T <TELL "DRY">)>
	<CRLF>>

<ROUTINE V-MATERIAL-PERSIST-START ()
	<MATERIAL-TEST-CLEAR>
	<MATERIAL-TEST-QUIET-WORLD>
	<MATERIAL-TEST-EGG>
	<MOVE ,RAILING ,PATH>
	<MOVE ,ROPE ,WINNER>
	<MOVE ,SANDWICH-BAG ,WINNER>
	<FSET ,SANDWICH-BAG ,OPENBIT>
	<MOVE ,SHOVEL ,WINNER>
	<MOVE ,SCREWDRIVER ,WINNER>
	<MOVE ,WRENCH ,WINNER>
	<MOVE ,RUSTY-KNIFE ,WINNER>
	<MATERIAL-TEST-WATER>
	<GOTO ,WEST-OF-HOUSE>
	<SETG CLOCK-WAIT T>
	<TELL "MATERIAL-PERSIST:START" CR>>

<ROUTINE V-MATERIAL-PERSIST-PATH ()
	<GOTO ,PATH>
	<SETG CLOCK-WAIT T>
	<TELL "MATERIAL-PERSIST:PATH" CR>>

<ROUTINE V-MATERIAL-PERSIST-TREE ()
	<GOTO ,UP-A-TREE>
	<SETG CLOCK-WAIT T>
	<TELL "MATERIAL-PERSIST:TREE" CR>>

<ROUTINE V-MATERIAL-PERSIST-MUTATE ()
	<MATERIAL-TEST-CLEAR>
	<MOVE ,ROPE ,WINNER>
	<MOVE ,SANDWICH-BAG ,WINNER>
	<FSET ,SANDWICH-BAG ,OPENBIT>
	<SETG CLOCK-WAIT T>
	<TELL "MATERIAL-PERSIST:MUTATED" CR>>

<ROUTINE V-MATERIAL-PERSIST-REPORT ()
	<TELL "MATERIAL-PERSIST:ROPE=">
	<COND (<EQUAL? ,MATERIAL-ROPE-ANCHOR ,RAILING> <TELL "RAILING">)
	      (,MATERIAL-SACK-CINCHED <TELL "SACK">)
	      (,MATERIAL-ROPE-ANCHOR <TELL "OTHER">)
	      (T <TELL "FREE">)>
	<TELL ";SACK=">
	<COND (,MATERIAL-SACK-CINCHED <TELL "CINCHED">)
	      (<FSET? ,SANDWICH-BAG ,OPENBIT> <TELL "OPEN">)
	      (T <TELL "CLOSED">)>
	<TELL ";BOARDS=">
	<COND (<AND ,MATERIAL-BOARDS-PRIED ,MATERIAL-BOARDS-HARDWARE-KNOWN>
	       <TELL "PRIED-HARDWARE">)
	      (,MATERIAL-BOARDS-PRIED <TELL "PRIED">)
	      (,MATERIAL-BOARDS-HARDWARE-KNOWN <TELL "HARDWARE">)
	      (T <TELL "CLEAR">)>
	<TELL ";SHOVEL=">
	<COND (,MATERIAL-SHOVEL-CLEANED <TELL "CLEAN">)
	      (T <TELL "DIRTY">)>
	<TELL ";RUST=">
	<COND (,MATERIAL-RUST-WORSE <TELL "WORSE">)
	      (<G? ,MATERIAL-RUST-WET 0> <TELL "WET">)
	      (T <TELL "OLD">)>
	<TELL ";NEST=">
	<COND (<G? ,MATERIAL-NEST-WET 0> <TELL "WET">)
	      (T <TELL "DRY">)>
	<CRLF>>
