"Test-only setup, refill, and state-report verbs for Release 1217 qualification."

<SYNTAX MRESET = V-MATERIAL-TEST-RESET>
<SYNTAX MSURF = V-MATERIAL-TEST-SURFACE>
<SYNTAX MANCH = V-MATERIAL-TEST-ANCHOR>
<SYNTAX MTOOLS = V-MATERIAL-TEST-TOOLS>
<SYNTAX MNEST = V-MATERIAL-TEST-NEST>
<SYNTAX MREFIL = V-MATERIAL-TEST-REFILL>
<SYNTAX MREPORT = V-MATERIAL-TEST-REPORT>

<ROUTINE MATERIAL-TEST-CLEAR ()
	<SETG MATERIAL-ROPE-ANCHOR <>>
	<SETG MATERIAL-SACK-CINCHED <>>
	<SETG MATERIAL-NEST-WET 0>
	<SETG MATERIAL-SHOVEL-CLEANED <>>
	<SETG MATERIAL-WRENCH-CLEANED <>>
	<SETG MATERIAL-SCREWDRIVER-CLEANED <>>
	<SETG MATERIAL-AXE-CLEANED <>>
	<SETG MATERIAL-RUST-WET 0>
	<SETG MATERIAL-RUST-WORSE <>>
	<SETG MATERIAL-BOARDS-PRIED <>>
	<SETG MATERIAL-BOARDS-HARDWARE-KNOWN <>>
	<SETG SURFACE-BOARDS-SCARRED <>>
	<SETG GLULX-ALT-SACK-PREPARED <>>
	<SETG GLULX-ALT-NEST-BURNED <>>
	<SETG GLULX-ALT-EGG-CAUGHT <>>
	<REMOVE-CAREFULLY ,HOUSE-SPLINTER>
	<RTRUE>>

<ROUTINE MATERIAL-TEST-QUIET-WORLD ()
	<QUEUE I-THIEF 0>
	<SETG THIEF-HERE <>>
	<REMOVE-CAREFULLY ,THIEF>
	<MOVE ,LAMP ,WINNER>
	<FSET ,LAMP ,ONBIT>
	<RTRUE>>

<ROUTINE MATERIAL-TEST-WATER ()
	<MOVE ,BOTTLE ,WINNER>
	<MOVE ,WATER ,BOTTLE>
	<FSET ,BOTTLE ,OPENBIT>
	<RTRUE>>

<ROUTINE V-MATERIAL-TEST-RESET ()
	<MATERIAL-TEST-CLEAR>
	<MATERIAL-TEST-QUIET-WORLD>
	<REMOVE-CAREFULLY ,BROKEN-EGG>
	<MOVE ,CANARY ,EGG>
	<MOVE ,NEST ,UP-A-TREE>
	<MOVE ,EGG ,NEST>
	<MOVE ,ROPE ,WINNER>
	<MOVE ,SANDWICH-BAG ,WINNER>
	<FSET ,SANDWICH-BAG ,OPENBIT>
	<MATERIAL-TEST-WATER>
	<GOTO ,PATH>
	<SETG CLOCK-WAIT T>
	<TELL "MATERIAL-SETUP:RESET" CR>>

<ROUTINE V-MATERIAL-TEST-SURFACE ()
	<MATERIAL-TEST-CLEAR>
	<MATERIAL-TEST-QUIET-WORLD>
	<MOVE ,SHOVEL ,WINNER>
	<MOVE ,SCREWDRIVER ,WINNER>
	<MOVE ,WRENCH ,WINNER>
	<GOTO ,WEST-OF-HOUSE>
	<SETG CLOCK-WAIT T>
	<TELL "MATERIAL-SETUP:SURFACE" CR>>

<ROUTINE V-MATERIAL-TEST-ANCHOR ()
	<MATERIAL-TEST-CLEAR>
	<MATERIAL-TEST-QUIET-WORLD>
	<MOVE ,RAILING ,PATH>
	<MOVE ,ROPE ,WINNER>
	<MOVE ,SANDWICH-BAG ,WINNER>
	<FCLEAR ,SANDWICH-BAG ,OPENBIT>
	<GOTO ,PATH>
	<SETG CLOCK-WAIT T>
	<TELL "MATERIAL-SETUP:ANCHOR" CR>>

<ROUTINE V-MATERIAL-TEST-TOOLS ()
	<MATERIAL-TEST-CLEAR>
	<MATERIAL-TEST-QUIET-WORLD>
	<MOVE ,SHOVEL ,WINNER>
	<MOVE ,WRENCH ,WINNER>
	<MOVE ,SCREWDRIVER ,WINNER>
	<MOVE ,AXE ,WINNER>
	<MOVE ,RUSTY-KNIFE ,WINNER>
	<MATERIAL-TEST-WATER>
	<GOTO ,PATH>
	<SETG CLOCK-WAIT T>
	<TELL "MATERIAL-SETUP:TOOLS" CR>>

<ROUTINE V-MATERIAL-TEST-NEST ()
	<MATERIAL-TEST-CLEAR>
	<MATERIAL-TEST-QUIET-WORLD>
	<REMOVE-CAREFULLY ,BROKEN-EGG>
	<MOVE ,CANARY ,EGG>
	<MOVE ,NEST ,UP-A-TREE>
	<MOVE ,EGG ,NEST>
	<MOVE ,TORCH ,WINNER>
	<FSET ,TORCH ,ONBIT>
	<FSET ,TORCH ,FLAMEBIT>
	<MATERIAL-TEST-WATER>
	<GOTO ,UP-A-TREE>
	<SETG CLOCK-WAIT T>
	<TELL "MATERIAL-SETUP:NEST" CR>>

<ROUTINE V-MATERIAL-TEST-REFILL ()
	<MATERIAL-TEST-WATER>
	<SETG CLOCK-WAIT T>
	<TELL "MATERIAL-SETUP:REFILL" CR>>

<ROUTINE V-MATERIAL-TEST-REPORT ()
	<TELL "MATERIAL-REPORT:ROPE=">
	<COND (,MATERIAL-SACK-CINCHED <TELL "SACK-CINCHED">)
	      (,MATERIAL-ROPE-ANCHOR <TELL "ANCHORED">)
	      (T <TELL "FREE">)>
	<TELL ";BOARDS=">
	<COND (,MATERIAL-BOARDS-PRIED <TELL "PRIED">)
	      (,MATERIAL-BOARDS-HARDWARE-KNOWN <TELL "DIAGNOSED">)
	      (T <TELL "UNTESTED">)>
	<TELL ";SHOVEL=">
	<COND (,MATERIAL-SHOVEL-CLEANED <TELL "CLEAN">)
	      (T <TELL "DIRTY">)>
	<TELL ";RUST=">
	<COND (,MATERIAL-RUST-WORSE <TELL "WORSE">)
	      (<G? ,MATERIAL-RUST-WET 0> <TELL "WET">)
	      (T <TELL "OLD">)>
	<TELL ";NEST=">
	<COND (<G? ,MATERIAL-NEST-WET 0> <TELL "WET">)
	      (T <TELL "DRY">)>
	<CRLF>>
