"Test-only setup verbs for Glulx absurd-alternate parity qualification."

<SYNTAX ALTSAFE = V-GLULX-ALT-SAFE>
<SYNTAX ALTEMPTY = V-GLULX-ALT-EMPTY>
<SYNTAX ALTBREAK = V-GLULX-ALT-BREAK>
<SYNTAX ALTCANON = V-GLULX-ALT-CANON>
<SYNTAX ALTTROLL = V-GLULX-ALT-TROLL-SETUP>
<SYNTAX ALTUNARM = V-GLULX-ALT-UNARMED-TROLL-SETUP>
<SYNTAX ALTBOUND = V-GLULX-ALT-BOUND-TROLL-SETUP>

<ROUTINE GLULX-ALT-TEST-NEST-BASE ()
	<MOVE ,TORCH ,WINNER>
	<FSET ,TORCH ,ONBIT>
	<FSET ,TORCH ,FLAMEBIT>
	<MOVE ,NEST ,UP-A-TREE>
	<MOVE ,EGG ,NEST>
	<MOVE ,CANARY ,EGG>
	<SETG GLULX-ALT-NEST-BURNED <>>
	<SETG GLULX-ALT-EGG-CAUGHT <>>
	<SETG GLULX-ALT-SACK-PREPARED <>>
	<GOTO ,PATH>
	<RTRUE>>

<ROUTINE V-GLULX-ALT-SAFE ()
	<GLULX-ALT-TEST-NEST-BASE>
	<MOVE ,SANDWICH-BAG ,WINNER>
	<MOVE ,LUNCH ,SANDWICH-BAG>
	<TELL "[Test-only prepared-catcher scenario.]" CR>>

<ROUTINE V-GLULX-ALT-EMPTY ()
	<GLULX-ALT-TEST-NEST-BASE>
	<MOVE ,SANDWICH-BAG ,WINNER>
	<MOVE ,LUNCH ,KITCHEN-TABLE>
	<TELL "[Test-only prepared empty-catcher scenario.]" CR>>

<ROUTINE V-GLULX-ALT-BREAK ()
	<GLULX-ALT-TEST-NEST-BASE>
	<MOVE ,SANDWICH-BAG ,PATH>
	<TELL "[Test-only unprepared-fall scenario with an unprepared sack beneath the tree.]" CR>>

<ROUTINE V-GLULX-ALT-CANON ()
	<MOVE ,NEST ,PATH>
	<MOVE ,EGG ,NEST>
	<MOVE ,CANARY ,EGG>
	<MOVE ,CANDLES ,WINNER>
	<FSET ,CANDLES ,ONBIT>
	<FSET ,CANDLES ,FLAMEBIT>
	<GOTO ,PATH>
	<TELL "[Test-only canonical nest-burning scenario.]" CR>>

<ROUTINE GLULX-ALT-TEST-TROLL-BASE ()
	<MOVE ,ROPE ,WINNER>
	<MOVE ,LAMP ,WINNER>
	<FSET ,LAMP ,ONBIT>
	<FSET ,LAMP ,LIGHTBIT>
	<FCLEAR ,ROPE ,NDESCBIT>
	<FSET ,TROLL ,FIGHTBIT>
	<PUTP ,TROLL ,P?LDESC "A nasty-looking troll blocks all passages.">
	<SETG GLULX-ALT-TROLL-DISTRACTED <>>
	<SETG GLULX-ALT-TROLL-TRICK-USED <>>
	<SETG GLULX-ALT-TROLL-BOUND <>>
	<SETG TROLL-FLAG <>>
	<GOTO ,TROLL-ROOM>
	<SETG CLOCK-WAIT T>
	<RTRUE>>

<ROUTINE V-GLULX-ALT-TROLL-SETUP ()
	<GLULX-ALT-TEST-TROLL-BASE>
	<MOVE ,AXE ,TROLL>
	<TELL "[Test-only troll recovery scenario.]" CR>>

<ROUTINE V-GLULX-ALT-UNARMED-TROLL-SETUP ()
	<GLULX-ALT-TEST-TROLL-BASE>
	<MOVE ,AXE ,KITCHEN-TABLE>
	<TELL "[Test-only unarmed troll scenario.]" CR>>

<ROUTINE V-GLULX-ALT-BOUND-TROLL-SETUP ()
	<GLULX-ALT-TEST-TROLL-BASE>
	<MOVE ,AXE ,TROLL>
	<MOVE ,ROPE ,TROLL>
	<FSET ,ROPE ,NDESCBIT>
	<FCLEAR ,TROLL ,FIGHTBIT>
	<SETG GLULX-ALT-TROLL-BOUND T>
	<SETG TROLL-FLAG T>
	<PUTP ,TROLL ,P?LDESC
"A nasty-looking troll is tied securely with the rope and wedged resentfully against the wall. All passages are open.">
	<TELL "[Test-only bound troll restoration scenario.]" CR>>
